verdaccio/verdaccio

- .gitignore
- bin/verdaccio
- test/functional/scoped.js
This works for me. 
Environment: v6.3.0
Solves #48 #16
It was too easy, I'm missing something?
> Fix test node6

- README.md
I'm not 100% if all those names terms should be renamed, but, please take a look.
> update readme,  sinopia renamed to verdaccio

- lib/cli.js
- lib/plugins/htpasswd/index.js
> rename clean up

- .travis.yml
> remove travis io.js support

- .gitignore
- package.json
It adds Istanbul as unit test coverage reporter 
https://github.com/gotwarlost/istanbul
> Unit testing coverage

- .github/issue_template.md
- CONTRIBUTING.md
A guidelines notes how to contribute and also a github issue template in order to get more information for each ticket.
> Contribute guidelines

- lib/plugin-loader.js
And overwrite by null if no sinopia plugin exist :(
> fix(plugin-loader): plugins verdaccio-* overwrite by sinopia-*

- README.md
- SERVER.md
- Add docs about run behind proxy with different domain and port
- Add server-side configure document link in README.md
> add docs about run behind proxy

- lib/plugin-loader.js
- test/unit/partials/test-plugin-storage/invalid-package/package.json
- test/unit/partials/test-plugin-storage/invalid-plugin-sanity/index.js
- test/unit/partials/test-plugin-storage/invalid-plugin-sanity/package.json
- test/unit/partials/test-plugin-storage/invalid-plugin/index.js
- test/unit/partials/test-plugin-storage/invalid-plugin/package.json
- test/unit/partials/test-plugin-storage/verdaccio-plugin/index.js
- test/unit/partials/test-plugin-storage/verdaccio-plugin/package.json
- test/unit/plugin_loader.js
Increase coverage for plugin-loader
> Add unit test for plugin-loader

- lib/index-api.js
- lib/up-storage.js
Almost all changes have comment, so, please read it.
💩 Official registry's strange behavior made me headache
> fix upstream search

- lib/config.js
- lib/index.js
- lib/plugin-loader.js
- lib/search.js
- lib/status-cats.js
- lib/streams.js
- lib/utils.js
- test/unit/search.js
> Clean eslint

- README.md
- lib/index-api.js
- lib/storage.js
Add an endpoint for the command
`npm ping`
> Implement npm ping endpoint

- SERVER.md
> Apache reverse proxy configuration

- lib/middleware.js
* There is a related issue
Add remote ip address to request log for security
Close #215
> Add remote ip to request log

- .eslintignore
- .npmignore
- wiki/ansible.md
- wiki/home.md
- wiki/iss-server.md
- wiki/plugins.md
- wiki/reverse-proxy.md
- wiki/ssl.md
- wiki/windows.md
This commit move the wiki section to markdown into repository file, it would be easier to track changes.
> Add wiki section

- wiki/README.md
- wiki/cli.md
- wiki/notifications.md
- wiki/packages.md
- wiki/uplinks.md
It will solve the lack of documentation or usage and configuration. It will cover
* Uplinks
* Packages
* Authentification / Access
* Plugin (Developing your plugins)
* Logging
* Web UI
* Notifications
* CLI
* Configuration file
* Understanding the Storage
Resolves #105
> Increase Documentation

- README.md
The current command was installing the packages "global" and "verdaccio" locally instead of installing verdaccio globally.
**Type:** bug / feature
Resolves #???
> fixing yarn syntax

- README.md
update readme, add docker badge
> doc: update readme, add docker badge

- lib/index-web.js
- lib/utils.js
**Type:** bug
This PR resolves issue when verdaccio is running behind loadbalancer with TLS termination.
> fix running behind of loadbalancer with TLS termination

- wiki/README.md
- wiki/auth.md
- wiki/plugins.md
Improve the following wiki sections:
Resolves #105
> (doc): Upload wiki documentation

- package-lock.json
- src/api/web/api.js
- src/webui/src/components/PackageList/index.js
- src/webui/src/components/PackageList/packageList.scss
> Add publish introduce

- conf/full.yaml
- src/lib/storage.js
**Type:** bug 
* X There is a related issue
* Unit or Functional tests are included in the PR (WIP)
Resolves #78 and https://github.com/rlidwka/sinopia/issues/356
> Fix #78 Add new setting to allow publish when uplinks are offline

- src/api/web/middleware.js
- src/webui/src/router.js
**Type:** bug
**Resolve:**
Fix detail page can't handle scoped package
Fix readme leak
> Detail page can't handle scoped package

- src/api/web/index.js
- tools/webpack.prod.config.babel.js
**Type:** bug
Restore set title by config file
Resolves #265
> fix: Param web.title from config.yaml does not work on docker image #265

- src/lib/storage/up-storage.js
**Type:** bug
Detail: https://github.com/verdaccio/verdaccio/issues/268#issuecomment-318815603
Resolves #268
> refactor: fix #268 in a better way

- Dockerfile
Update `node-alpine` to `8.4.0`
> feat: Update node alpine version to 8.4.0

- conf/docker.yaml
- conf/full.yaml
**Type:** refactor / configure file update
**Description:** See linked issue
Resolves #307
> refactor: remove invalid section and modify comment

- CONTRIBUTING.md
- README.md
- wiki/README.md
- wiki/cli.md
- wiki/config.md
- wiki/install.md
- wiki/logger.md
- wiki/web.md
Increase `verdaccio` documentation
Resolves #???
> docs:  Add new sections to documentation

- .eslintrc
- .flowconfig
- package.json
- yarn.lock
This project has been moving to a more modern syntax progressively. I've introduced two new projects as a proof of concept.
* https://github.com/verdaccio/flow-types (typings)
* https://github.com/verdaccio/local-storage (implemention)
My reasons to introduce Flow:
* Unluckily we don't use Typescript
* We use babel already for UI and eslint
* It will help with the new plugin system
* Much clear and maintainable code base
* We can progressively enable flow for an easy migration
* Interfaces are clearly helpful
> feat: Using flow

- src/lib/logger.js
**Type:** bug
*  There is a related issue. I have changed debug color to green.
Resolves #311
> Fix #311: Debug text in green color

- src/api/web/index.js
- src/webui/src/components/Header/index.js
**Type:** bug 
*  There is a related issue #319 
*  Unit or Functional tests are included in the PR - All test passed.
Resolves #319
> Load logo from config

- src/webui/src/components/Header/index.js
**Type:** bug 
*  There is a related issue #322 
I have replaced MessageBox with Alert.
Resolves #322
> MessageBox replaced with Alert in login dialog

- wiki/iis-server.md
- wiki/windows.md
Commit 7fef14c322c1c73727c349389e036b3e5bde3bcc refactored the directory structure - reflect these changes in the documentation.
**Type:** Typo
> Use current directory structure in documentation

- src/lib/storage/up-storage.js
> Remove extra query parameters on Accept headers

- .babelrc
- package.json
- tools/webpack.config.js
- tools/webpack.prod.config.babel.js
- yarn.lock
**Type:** bug 
Add support for old browsers.
Resolves #334
> fix: Fix  #334 UI failure on IE 11, add support for old browsers.

- src/lib/plugin-loader.js
Plugin loader improvement with logger
**Type:** Improvement
*  Unit or Functional tests are included in the PR.
Resolves #321 
* I tried to improve plugin loading system using promise and added logs functionality.
> Plugin loader with logs

- src/lib/cli.js
Adds support to use a certificate in pfx file format with an optional passphrase
Resolves #359
> Support pfx certificates

- CONTRIBUTING.md
> docs: add commit guidelines

- wiki/ssl.md
*  There is a related issue #359
Documentation for the pfx support feature
> docs: add pfx support for https

- Dockerfile
> refactor: upgrade docker to node 8.7

- wiki/uplinks.md
**Type:** bug
A typo was corrected
Improves documentation
> fixed a typo

- README.md
This adds some minor spelling improvements to the README.
Thanks for the awesome project!
> Improve spelling in README.md

- src/api/web/index.js
- src/webui/src/components/Header/index.js
- src/webui/src/components/Help/index.js
**Type:** bug
**The following has been addressed in the PR:**
Same as the title
Resolves #384
> fix: :bug: incorrect resource and registry url while install on sub directory

- src/api/web/index.js
- src/utils/string.js
**Type:** bug
- fix: :bug: incorrect logo url with slash at the end of `url_prefix`
Resolves #398
> fix: :bug: incorrect logo url with slash at the end of `url_prefix`

- README.md
> fixes 2 typos in Readme

- conf/full.yaml
- src/api/index.js
- test/functional/fixtures/plugins/middlewares.js
- test/functional/index.js
- test/functional/plugins/middleware.spec.js
- test/functional/store/config-2.yaml
This is basically PR fl4re/sinopia#18 by @fredr
While waiting for a new plugin system (#169), we need to allow middleware plugins.
Some sinopia plugins needs this, as mentioned in #353
> Add middleware plugins from fl4re/sinopia

- wiki/dev/README.md
**Type:** bug / feature / documentation / unit test / build
Fixes spelling typo.
> spelling correction in wiki-dev

- CHANGELOG.md
- src/lib/logger.js
- wiki/logger.md
**Type:** bug
*  No mechanism exists to rotate Verdaccio logs without a full restart
Resolves #420
> Add signal-handling to allow proper log-rotation.

- wiki/README.md
- wiki/kubernetes.md
*  Add instruction to install Verdaccio on a Kubernetes cluster
Resolves https://github.com/verdaccio/docker-examples/issues/8
> Add Kubernetes instructions

- src/lib/notify.js
- test/functional/notifications/notify.js
> Notification for multiple endpoints

- package.json
- yarn.lock
**Type:** bug / feature / documentation / unit test / build
*  This is PR related to marked dependency issue.
*  Updated marked to 0.3.9
Resolves #447
> fix: marked dependency to latest

- docs/plugins.md
*  add a reference to the verdaccio-gitlab plugin
> docs: add verdaccio-gitlab plugin

- README.md
**Type:** bug / feature / documentation / unit test / build
Resolves #???
> fix link to server.md

- README.md
- package.json
> use david-dm instead of greenkeeper

- package.json
- src/lib/local-storage.js
- src/lib/plugin-loader.js
- yarn.lock
**Type:** feature 
Refactor:
- Storage path is handled by storage plugin
- Update versions
- Allow ES6 transpiled plugins
> refactor: resolve local storage path on the plugin it self

- .github/pull_request_template.md
- docs/contributing.md
* Update chef name
* Replace broken link
* Fix image (GitHub seemed to have changed their markdown syntax)
* Improve language in pull request template
> Improve docs

- docs/uplinks.md
**Type:** bug 
Add `ca` property on uplink documentation
Resolves #493
> fix #493 Update uplink documentation adding CA property

- docs/config.md
**Type:** bug / documentation
Resolves #445
> fix: IPv6 set up

- website/siteConfig.js
**Type:** feature / documentation
Enable algolia search on website
> chore(website): enable algolia

- website/languages.js
**Type:** feature / documentation
Enable Português on website
> chore(docs): Enable Português

- docs/config.md
**Type:** bug / documentation
add http proxy configuration
Resolves #525
> docs(config): add http proxy configuration

- CONTRIBUTING.md
* Fix spelling errors in **CONTRIBUTING.md** file.
> docs: small spelling fix

- renovate.json
> chore(deps): force renovate to resolve only 1 day per month

- docs/ssl.md
- src/lib/bootstrap.js
Improve ssl certs generation
Resolves #574
> fix: update doc and output console to generate https

- src/lib/up-storage.js
- test/functional/sanity/nullstorage.js
- test/unit/up-storage.spec.js
**Type:** bug 
Discussing how to fix it.
Resolves #571
> test: add unit test for isUplinkValid #571

- package.json
- test/unit/api.spec.js
- yarn.lock
**Type:** Fix/Improvement
- Bumps verdaccio-htpasswd to v0.1.4
> verdaccio-htpasswd v0.1.4

- docs/iis-server.md
**Type:** Documentaton
*  There is a related issue #622 
- updates documentation with troubleshooting information
> docs: adds troubleshooting of IIS server with https

- docs/install.md
**Type: documentation**
This PR tries to improve grammar and readability of the docs/install.md documentation.
> Improve grammar and wording in docs/install.md

- AUTHORS
- conf/full.yaml
- docs/uplinks.md
- package.json
- src/lib/up-storage.js
- test/webui/components/PackageSidebar/lastsync.spec.js
- yarn.lock
Resolves #587 - Add strict_ssl parameter in uplink section which allows for self-signed certificates
> feat: add strict_ssl option, fixes #587

- src/webui/src/modules/home/index.js
**Type:**
*  There is a related issue #385 
- adds debounce to avoid excessive api calls to search endpoint.
- fixes laggy UX on searching packages.
> fix: adds debounce to search api call

- package.json
- src/api/web/endpoint/user.js
- src/lib/auth.js
- src/webui/src/components/Header/index.js
- src/webui/src/components/PackageSidebar/index.jsx
- src/webui/src/modules/detail/index.jsx
- src/webui/src/modules/home/index.js
- src/webui/utils/api.js
- test/webui/components/PackageSidebar/packageSidebar.spec.js
- test/webui/components/__mocks__/api.js
- test/webui/components/header.spec.js
- test/webui/components/store/login.js
- test/webui/components/store/logo.js
- tools/webpack.dev.config.babel.js
- tools/webpack.prod.config.babel.js
- yarn.lock
* Remove `axios` as request handler in favor of `fetch`
This will reduce the bundle size, one less dependency to handle and is Promise native. I had to update mock for test and modify a bit how responses are received. 
* Remove logout endpoint (it's not being used).
It does not make sense to have it, misleading. 
* Refactor login
Part of the `fetch` migration
> feat: using fetch on UI

- package.json
- test/unit/api.spec.js
- yarn.lock
Update **verdaccio-htpasswd** plugin
* feat: add support for reading bcrypt encrypted password https://github.com/verdaccio/verdaccio-htpasswd/pull/23
* fix: change sanity check to return 409 error on matching username and password https://github.com/verdaccio/verdaccio-htpasswd/pull/22
Close #191
> chore(deps): update verdaccio-htpasswd plugin

- docs/ci.md
- website/sidebars.json
**Type:** Documentation
**The following has been addressed in the PR:**
Few days ago, I faced an issue while integrating Verdaccio with gitlab CI. I think attached information in PR will improve the documentation. It consists different scenario to use authentication in CI environment. 
- adds continuous integration details with travis, circle and gitlab
> docs(ci): adds integration information with travis, circle & gitlab ci

- package.json
- src/api/index.js
- src/lib/bootstrap.js
- src/lib/cli.js
- src/lib/config.js
- src/lib/local-storage.js
- src/lib/metadata-utils.js
- src/lib/storage-utils.js
- src/lib/storage.js
- src/lib/uplink-util.js
- src/lib/utils.js
- test/unit/api.pkg.access.spec.js
- test/unit/api.spec.js
- test/unit/basic_system.spec.js
- test/unit/cli.spec.js
- test/unit/search.spec.js
- test/unit/st_merge.spec.js
- test/unit/store.spec.js
- types/index.js
- yarn.lock
* allows storage to initalize whether a async call is required on start up.
* using `async/await` approach
* split storage un functions for easy testing
> Refactor storage

- src/lib/up-storage.js
- test/functional/uplink.auth.spec.js
- test/unit/up-storage.spec.js
I also refactor other parts as string and constants
**Type:** bug
Partially solves #693
> fix: avoid issues with missing token #693

- Dockerfile
- circle.yml
- test/functional/uplink.auth.spec.js
**Type:** build
Testing on Node 10
> chore(build): update circleci to node 10

- docs/packages.md
**Type:**
Documentation
Resolves #741
>  docs: packages.md - add scope proxy example and cleanup grammar/wording

- .circleci/config.yml
*  There is a related issue? Part of #612 
*  This PR does not include Unit or Functional tests
This PR is a fix over !738 , CircleCI 2.0 migration. With this fix, we can store coverage reports after one test execution and allow publish them in coverage step.
> chore: store coverage

- .eslintrc
> fix: fixed linebreaks lint issue

- docs/notifications.md
- src/api/endpoint/api/publish.js
- src/lib/notify.js
- test/functional/notifications/notify.js
> feat: added information about package publisher for notifications

- src/lib/storage-utils.js
- test/unit/storage-utils.spec.js
**Type:** bug
*  There is a related issue? #758
*  Unit or Functional tests are included in the PR (yes)
Resolves #758
> fix: normalize package was broken #758

- src/lib/utils.js
- test/unit/__snapshots__/utils.spec.js.snap
- test/unit/partials/readme/ascii.adoc
- test/unit/partials/readme/markdown.md
- test/unit/utils.spec.js
*  There is a related issue #464 
- Improves regex and unit test.
> fix: improves regex for ascii and test (#461)

- docs/plugins.md
- Updates broken link here https://www.verdaccio.org/docs/en/plugins
> docs: update broken link in plugins

- src/webui/src/components/Header/index.js
- src/webui/src/components/PackageSidebar/index.jsx
- src/webui/src/modules/detail/index.jsx
- src/webui/src/modules/home/index.js
- src/webui/utils/api.js
- test/unit/webui/components/__mocks__/api.js
- test/unit/webui/components/header.spec.js
- test/unit/webui/components/store/login.js
- test/unit/webui/components/store/logo.js
**Type:** Refactor
- Refactoring of webui api service and header component tests.
> refactor: unit tests and api service

- docs/web.md
**Type:**
Documentation
Indicate that access restrictions apply to web UI as well as npm access (fix to #804)
> Mention access restrictions to web UI

- .babelrc
- flow-typed/npm/express_v4.16.x.js
- package.json
- src/api/index.js
- src/lib/auth-utils.js
- src/lib/auth.js
- src/lib/constants.js
- src/lib/local-storage.js
- src/lib/plugin-loader.js
- src/lib/storage.js
- src/lib/up-storage.js
- src/lib/utils.js
- test/flow/plugins/auth/complete.js
- test/flow/plugins/auth/example.auth.plugin.js
- test/flow/plugins/middleware/example.middleware.plugin.js
- test/flow/plugins/storage/example.storage.plugin.js
- test/unit/api/plugin_loader.spec.js
- test/unit/partials/plugin/authenticate.js
- types/index.js
- yarn.lock
* Update flow the latest version
* Add types for plugins examples
* Storage Types
* Middleware Types
* Auth Types
> refactor: flow 0.7x.0

- README.md
> chore: adds discord badge

- src/webui/components/PackageSidebar/modules/Dependencies/index.jsx
> fix: solves dependency bug for one dependency (#857)

- src/lib/constants.js
- src/lib/utils.js
- src/utils/user.js
- test/unit/api/utils.spec.js
**Type:** Feature
*  Unit tests are included in the PR
- Adds gravatar support for maintainers
- Removes mutable code https://github.com/verdaccio/verdaccio/blob/8627aac21dca51c20569c34e31cfdbc209373271/src/lib/utils.js#L434
> feat: adds gravatar support for maintainers

- README.md
- docs/contributing.md
- website/core/Footer.js
> Changes gitter links to Discord

- Dockerfile
Related https://github.com/nodejs/docker-node/issues/384
* Update node to `v10.7`
Resolves #883
> fix: fix docker python issue #883

- src/webui/modules/home/index.js
- test/unit/webui/modules/home.spec.js
**Type:**
*  Issue Fixed: [#898](https://github.com/verdaccio/verdaccio/issues/898)
Resolves the above issue where search crashes on entering ' ' (spaces) as a value
> fix(webui): search crash on ' ' as a value #898

- website/data/team.yml
- website/pages/en/team.js
remove twitter for one member
**Type:**
fix small typos
> chore: fix typo

- .eslintrc
- .prettierrc
- package.json
- src/webui/.eslintrc
- yarn.lock
Added Prettier
Resolved the closed PR [#821](https://github.com/verdaccio/verdaccio/pull/821)
> feat: added prettier

- docs/install.md
> Add Cloudron to install.md

- docs/cli.md
- package.json
- yarn.lock
*  There is a related issue? #936 
*  This PR doesn't include Unit or Functional tests
**Description:** Rename .sinopia-db.json to .verdaccio-db.json.
* Updating package.json / yarn.lock ```+ @verdaccio/local-storage@1.2.0```
* Add a new section of "Default database file location" to docs/cli.md
> feat: rename database file name

- src/webui/components/PackageSidebar/index.jsx
- src/webui/modules/detail/index.jsx
**Type:**
*  There is a related issue #959
*  Unit or Functional tests are included in the PR.
- Checks props condition as well for component update.
- Some indentation/formatting chages as well. 
Resolves #959
> fix: ui change details issue in props update (#959)

- src/lib/crypto-utils.js
- src/webui/modules/home/index.js
**Type:** bug
*  There is a related issue? #992 
Resolves #992
> fix: load package list undefined

- flow-typed/npm/chalk_v2.x.x.js
- package.json
- src/lib/cli.js
- src/lib/constants.js
- src/lib/update-banner.js
- test/unit/api/__snapshots__/update-banner.spec.js.snap
- test/unit/api/update-banner.spec.js
**Type:** Feature
*  There is a related issue #988 
*  Unit or Functional tests are included in the PR. **YES**
-
> feat: verdaccio update notification on CLI

- src/api/endpoint/api/publish.js
- src/api/middleware.js
- src/lib/bootstrap.js
- src/lib/config-path.js
- src/lib/constants.js
- src/lib/storage.js
- src/lib/utils.js
- test/unit/api/listen_addr.spec.js
**Type:**
- No Need
- Naming improvements
- Flow
> refactor: utils method exports

- README.md
**Type:** Documentation (README) update
**Description:** Fixes typo in Readme
> docs: Fixed typo in Readme

- src/webui/components/Footer/footer.scss
- src/webui/components/Spinner/index.js
- src/webui/components/Spinner/interfaces.js
- src/webui/components/Spinner/styles.js
- src/webui/modules/detail/detail.scss
- src/webui/modules/detail/index.jsx
- src/webui/modules/home/index.js
- src/webui/router.js
- src/webui/styles/global.scss
Type: Refactor
Description: "Centralize Loading "
Task: #1036
* Done:
> Centralize Loading

- src/lib/notify/notify-request.js
- test/unit/api/notify-request.spec.js
**Type:**  unit test
*  There is a related issue? No Issue
- Includes test for notify request service
> refactor: tests for notify request service

- src/api/web/endpoint/package.js
- src/lib/local-storage.js
- test/functional/tags/tags.js
- test/unit/api/api.pkg.access.spec.js
- test/unit/api/local-storage.spec.js
- test/unit/api/up-storage.spec.js
- test/unit/functionalLibs/request.spec.js
Resolve one eslint warning
**Type:**
> refactor: replace all 404 with NOT_FOUND constant

- src/api/endpoint/api/publish.js
- src/api/web/api.js
- src/lib/local-storage.js
- src/lib/storage-utils.js
- src/lib/storage.js
- src/lib/up-storage.js
- test/unit/api/config-utils.spec.js
> refactor: remove unnecessary FlowFixMe

- test/unit/api/search.spec.js
- test/unit/api/utils.spec.js
> refactor: remove all assert imports

- src/api/endpoint/index.js
- src/api/middleware.js
Rename function anti_loop to antiLoop
> refactor: rename anti_loop function to antiLoop

- src/api/endpoint/api/publish.js
- src/lib/constants.js
- creates TARBALL_UPLOADED & BAD_PACKAGE_DATA constant
**Type:**
> refactor: moving API response to constants

- src/webui/components/Package/package.scss
**Type:** bug
*  There is a related issue #1074 
- Wraps longer description.
> fix: word wrap longer description

- package.json
**Type:** Chore
*  Package json updated
https://github.com/verdaccio/verdaccio-audit/releases/tag/v1.0.0
> chore: updates verdaccio-audit to v1.0.0

- docs/packages.md
Fixes:
> error: unregistered users are not allowed to access package ...
> docs: use `$all` access

- CONTRIBUTING.md
Cleanup the contribution guide -- grammar, spelling, clarity, structure, etc.
> docs: cleanup contribution guide

- src/webui/app.js
**Type:**
- Removes unused code
> refactor: removes unused getFilteredPackage method

- docs/where-are-docs.md
Add some context about where the docs are located now.
> chore: add info where the new docs are

- src/lib/local-storage.js
- src/lib/utils.js
- test/functional/sanity/security.js
- test/unit/api/local-storage.spec.js
- test/unit/api/utils.spec.js
**Type:** feature request
*  There is a related issue? #1127
*  Unit or Functional tests are included in the PR [yes]
This PR allows packages with name **package.json** 
Resolves #1127
> feat: allows package.json as package name

- Dockerfile
**Type:** fix
Update Docker node base to `v10.14.1`
> fix: update docker node to 10.14.1

- .circleci/config.yml
**Type:** bug
Uses CircleCI with Node11
> Circle CI node 11

- .circleci/config.yml
**Description:** Use the alias for Node 11 alias in the correct stage of the workflow
> chore: fix the use of Node 11 in CircleCI

- .eslintignore
- src/api/web/endpoint/package.js
- src/lib/constants.js
- src/webui/components/PackageSidebar/index.jsx
- src/webui/components/PackageSidebar/modules/DistTags/index.jsx
- src/webui/components/PackageSidebar/modules/DistTags/style.scss
> Add dist-tag column on UI

- src/lib/local-storage.js
**Type:**
bug
There is an object which is never used.
> Remove unused object

- src/lib/storage.js
--
Before Pull Request check whether your commits follow this convention
https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#git-commit-guidelines
* If your PR fix an issue don't forget to update the unit test and documentation in /docs folder
* If your PR delivers a new feature, please, provide examples and why such feature should be considered.
* Document your changes /docs
* Add unit test
* Follow the commit guidelines in order to get a quick approval
Pick one/multiple type, if none apply please suggest one, we might be included it by default
eg: bug / feature / documentation / unit test / build
-->
**Type:**
bug
The comma operator …
> Remove use of comma separator

- src/lib/storage.js
- src/lib/up-storage.js
**Type:**
bug
*  There are some unnecessary checks.
Remove some unnecessary checks.
> Remove some unneeded checks

- src/utils/user.js
**Type:**
bug
*  Our linting tests found a local variable which is not really needed.
Remove unneeded local variable.
> Remove useless assignment to local variable emailCopy

- package.json
- src/api/endpoint/api/search.js
- src/api/middleware.js
- src/api/web/endpoint/package.js
- src/api/web/endpoint/search.js
- src/lib/auth.js
- src/lib/utils.js
- test/flow/plugins/middleware/example.middleware.plugin.js
- test/unit/api/utils.spec.js
- yarn.lock
> feat: Package version gets send to plugin (Reopen)

- src/lib/storage-utils.js
**Type:** Bug
*  There is a related issue #1194 
- Normalizes the package data to have `_id` for the package metadata.
> fix: adds _id to normalize metadata (#1194)

- src/lib/bootstrap.js
**Type:** fix
Related to issue #301, fixup of PR #1207 
Server keepAliveTimeout is in milliseconds, config value in seconds, so multiply by 1000 to fix.
> fix: server keepAliveTimeout is in milliseconds, config value in seconds.

- package.json
- src/lib/local-storage.js
- test/unit/api/local-storage.spec.js
- yarn.lock
Publishing existing package overrides existing package to 0 bytes file
Context on  #1191
Resolves #1191
> fix: overrides existing package to zero bytes file #1191

- contrib/aws/cloudformation-ec2-efs.yaml
In a new contrib/ directory.
**Type:**
> docs: Add example AWS CloudFormation template

- .circleci/config.yml
- .github/main.workflow
- scripts/github-release.sh
- scripts/publish.sh
- scripts/puppeteer-setup-ci.sh
- scripts/trigger-release.js
- test/e2e/setup.js
- yarn.lock
- Adds github actions to for releasing verdaccio to npm
- bumps verdaccio-htpasswd to v2.0.0
> Npm publish using GitHub actions

- src/api/web/index.js
**Type:** Feature
- Issue: https://github.com/verdaccio/ui/issues/11
- Corresponding PR: https://github.com/verdaccio/ui/pull/36
> Accept web.primary_color as config option and inject into webui

- .circleci/config.yml
**Type:**
build
This PR adds a Node.js 12 job to the CircleCI setup.
> build: test Node.js 12

- package.json
- src/lib/logger.js
- yarn.lock
**Type:**
chore
This PR replaces `date-fns` with `dayjs` which is smaller and faster.
> chore: replace date-fns with dayjs

- package.json
- src/api/endpoint/api/publish.js
- src/api/middleware.js
- src/api/web/endpoint/package.js
- src/lib/utils.js
- src/webui/components/PackageSidebar/modules/Infos/index.jsx
- src/webui/components/Readme/index.js
- src/webui/utils/url.js
- test/functional/readme/readme.js
- test/unit/api/__snapshots__/utils.spec.js.snap
- test/unit/api/api.spec.js
- test/unit/api/utils.spec.js
- yarn.lock
**Type:** feat
* Uses a new readme parser (sanitize content).  https://github.com/verdaccio/readme
* Avoid no-URL content to be included as a link 
🔴 This update `verdaccio@3.x`
```
docker run -it --rm --name verdaccio_v3 -p 4873:4873 verdaccio/verdaccio:update-readme-v3
```
> feat: update readme v3

- package.json
- src/lib/utils.js
- test/functional/readme/readme.js
- test/unit/api/__snapshots__/utils.spec.js.snap
- test/unit/api/utils.spec.js
- test/unit/partials/config-unit-mock-server-test.yaml
- yarn.lock
**Type:** feat
* A better readme parser (security, xss on readme,  homepage, emails) https://github.com/verdaccio/readme
```
docker run -it --rm --name verdaccio_v4 -p 4873:4873 verdaccio/verdaccio:update-readme-v4
```
> feat: update readme v4

- .github/main.workflow
- test/unit/api/basic_system.spec.js
GitHub action workflow fails randomly, we need to investigate the reasons. This PR disable that and relies on CircleCI.
> chore: remove test workflow from actions

- SECURITY.md
New security policy addresses:
1. Intro to a Responsible Security Disclosure policy
2. Establish Security Processes
3. Adopt a Responsible Security Disclosure policy
The most notable changes from your current policy is removal of the following:
* *promise* - due to the nature of the project being open source, I think it is not very feasible to put an actual number of days as theoretically speaking the project’s team could be out on holiday or vacation. it also conflicts with the SLA of other programs which are mentioned like Snyk or npm because these have their own timeframe and processes set in place which is beyond your control
* *rules for reporting* - some of them go without mentioning, and some statements there relate more with online services which require no modification of the …
> fix: update security policy details

- README.md
> docs: minor tweaks

- package.json
- yarn.lock
**Type:** build
**Description:** this PR bumps detect-secrets to 1.0.4 in order to introduce a better workflow with detect-secrets mutating the secrets baseline and erroring out.
> chore(deps): bump detect-secrets for enhanced dev workflow

- Dockerfile
**Type:** feat
Update Docker to Node.js 10.16
> feat: docker image bump to node.js 10.16

- package.json
- yarn.lock
**Type:** feat
- fix: https://github.com/verdaccio/ui/issues/76
- fix: https://github.com/verdaccio/ui/issues/75
- fix: https://github.com/verdaccio/ui/pull/106
- feat: https://github.com/verdaccio/ui/pull/47
Co-Authored-By: Priscila Oliveira <priscilawebdev@gmail.com>
Co-Authored-By: Sergio Hg <sergiohgz@users.noreply.github.com>
Co-Authored-By: Griffith <griffithtp@users.noreply.github.com>
> feat: update to @verdaccio/ui-theme@0.2.2

- src/lib/utils.ts
Just an attempt made to eliminate code redundancy.
> chore: minor refactor to eliminate code redundancy

- README.md
**Type:** Documentation
*  Unit or Functional tests are included in the PR: N/A
The Donations section of the README had a couple of typos, so I tidied it up a little bit.
> Update language in README's Donations section

- .github/lock.yml
**Type:**
chore
Adds a missing word in the lock omment.
> Add missing word in lock comment

- Dockerfile
Update Docker image to Node.js **10.16.3**
> feat(docker): Node.js update to 10.16.3

- conf/default.yaml
**Description:** Remove JWT from the default config because users should not be using it by default
> chore: remove jwt from default config

- conf/docker.yaml
**Description:** Remove JWT from the default docker config because users should not be using it by default
> chore: remove jwt from docker config

- README.md
I have to tell, I've been willing this for a while, Daniel has been helping us since more than one year ago, constantly helping on different areas and would be a pleasure you will be part of our virtual team.
So, I guess only Daniel can approve this PR.
> chore(core): daniel ruf to core team

- .circleci/config.yml
**Type:** ci
*  There is a related issue? #1489
**Description:** In this PR I extracted repetitive steps to common commands and clean aliases section using executors section.
Note: This PR is marked as draft because it's a continuation of #1495. Draft state will be removed when #1495 will be completed.
> ci(circleci): use CircleCI 2.1 syntax improvements

- conf/default.yaml
- src/api/endpoint/api/publish.ts
- src/lib/logger.ts
- test/functional/lib/setup.ts
- test/functional/lib/simple_server.ts
- test/unit/modules/uplinks/up-storage.spec.ts
- test/unit/modules/utils/config-utils.spec.ts
- test/unit/partials/plugin/authenticate.success.js
**Type:**
Fixing typos in comments
> Fixing typos in comments

- src/api/endpoint/api/ping.ts
- src/api/endpoint/api/publish.ts
- src/api/endpoint/api/search.ts
- src/api/endpoint/api/star.ts
- src/api/endpoint/api/v1/token.ts
> Fixing the lint issues

- src/lib/up-storage.ts
Follow up of https://github.com/verdaccio/verdaccio/pull/1332
Documented here https://github.com/verdaccio/website/pull/126
Resolves: #1329
> fix: allow add to request agentOptions

- .circleci/config.yml
- .gitignore
- jest.config.js
- package.json
- yarn.lock
**Type:** ci
**Description:** Add JUnit reporter to save tests executions in a syntax that CircleCI understands, so we can have better metrics about testing. For more information, take a look in CircleCI docs about [collect test data](https://circleci.com/docs/2.0/collect-test-data), specially, in [Jest section](https://circleci.com/docs/2.0/collect-test-data/#jest).
Note: This PR is marked as draft because it's a continuation of #1495 and #1496. Draft state will be removed when #1495 and #1496 will be completed.
> ci(circleci): store test results in junit format

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- conf/README.md
- wiki/README.md
No
No tests needed.
Fixing some typos, minor formatting and update the commit message linter command text.
> fix: minor typos, formatting, and docs

- src/api/endpoint/api/publish.ts
> chore: minor tweak

- src/lib/logger.ts
**Type:** Chore / Tech Debt
* 3x unnecessary `@ts-ignore`  comments have been removed
* Removes unnecessary `any` explicit type on const object.
Ref: #973
> chore: removes 3x unnecessary @ts-ignore comments

- package.json
- yarn.lock
**Type:** build
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/
Let's see what we can do with this version.
It might helps with
- https://github.com/verdaccio/verdaccio/issues/991
> chore: update typescript@3.7.0-beta (PoC)

- package.json
- yarn.lock
Follow up of https://github.com/verdaccio/verdaccio/pulls?q=is%3Apr+is%3Aclosed
> Update Typescript 3.7.1-rc

- src/lib/config-utils.ts
> refactor: removes ts ignore comments

- src/api/endpoint/api/stars.ts
**Type:**
refactor
There is no need to use conditional operator, as `_.keys()` will always return an array.
Alternatively , `_.has()` maybe clearer but more heavier.
> refactor: simplify the conditional expression

- Dockerfile
Node 10 is active but 12 is the recommended way https://nodejs.org/en/about/releases/ we have been running against v12 for months, so we are safe
**Type:**
> feat: bumb up docker to node 12

- package.json
- test/e2e/e2e.spec.js
- yarn.lock
👏 👏 👏 👏 👏  Thanks guys awesome work
@priscilawebdev @ayusharma @tmkn @anikethsaha @antoinechalifour 
Reviews: @juanpicado @DanielRuf @sergiohgz 
**🐛 fixes**: all contributors I cannot add manually, thanks ! https://github.com/verdaccio/ui/graphs/contributors
* login Dialog Component - Replaced class by func. comp + added react-hook-form @priscilawebdev 
* Added Theme and migrate to emotion@10.x 🚀 ([#286](https://github.com/verdaccio/ui/issues/286)) ([111f0c5](https://github.com/verdaccio/ui/commit/111f0c50e5053202ca55fe4f3f28dd30e4932240)) @priscilawebdev 
* added download tarball button at list ([#237](https://github.com/verdaccio/ui/issues/237)) ([bdef686](https://github.com/verdaccio/ui/commit/bdef686)) @anikethsaha
* update date fns to v2 …
> feat: update @verdaccio/ui-theme@0.3.9

- package.json
- src/lib/local-storage.ts
- test/types-test/plugins/storage/example.storage.plugin.ts
- yarn.lock
**Type:** refactor
**Description:** 
Upgrade based on 
https://github.com/verdaccio/monorepo/pull/306
https://github.com/verdaccio/monorepo/pull/307
Basically provide way more info for plugin implementations.
> refactor: update monorepo deps and types

- package.json
- yarn.lock
**Type:** bug
More info here https://github.com/verdaccio/ui/blob/master/CHANGELOG.md#0313-2020-02-02
> fix: update @verdaccio/ui-theme@0.3.13

- src/api/web/endpoint/package.ts
**Type:** bug
tarball links not being preprocessed on `/-/packages` web api endpoint
*  Unit or Functional tests were not changed
**Resolves:** #1714
> fix: tarball urls for web/package (fix #1714)

- README.md
> Add TODOs badge to the README

- yarn.lock
https://app.snyk.io/org/juanpicado/project/0c76bae8-cfcd-43f7-aff5-70f221855049
https://www.npmjs.com/advisories/1488
> fix: update acorn@7.1.1

- .github/workflows/docker-publish-pre-check.yml
- package.json
- yarn.lock
**Type:** security
https://app.snyk.io/vuln/SNYK-JS-ACORN-559469
> fix: update @verdaccio/readme@9.3.2

- package.json
- yarn.lock
**Type:** security
update security dependencies
```
"@verdaccio/commons-api": "^9.3.2",
"@verdaccio/local-storage": "^9.3.4",
"@verdaccio/readme": "^9.3.3",
"@verdaccio/streams": "^9.3.2",
```
> fix: update dependencies security warnings

- Dockerfile
**Type:** feat
Update node docker base to 12.16.2
> feat: update docker base image node to 12.16.2

- package.json
- yarn.lock
**Type:**
* Dark mode on UI
* Chinese translation for UI
> feat: update @verdaccio/ui-theme@1.5.0

- src/lib/auth.ts
**Type:** bug
Improve token validation
> fix: improve token validation

- package.json
- yarn.lock
**Type:** dependencies
- @verdaccio/ui-theme@1.7.1 add language switch and fix bug translations powered by @priscilawebdev
- verdaccio-htpasswd@9.4.1 generate non-constant legacy 2 byte salt by @michaellotz-iart
- update dayjs and envinfo
https://github.com/verdaccio/monorepo/pull/357
> fix: update core dependencies

- src/api/web/endpoint/package.ts
**Type:** bug
Add access level to the sidebar endpoint.
> fix: avoid access to sidebar without login

- Dockerfile
updated nodejs version to fix vulnerability in 12.x -  https://nodejs.org/en/blog/vulnerability/june-2020-security-releases/
> updated nodejs version to fix vulnerability in 12.x

- .github/workflows/ci.yml
- README.md
- package.json
- yarn.lock
* add chinese trad for taiwan translations (#486) (bc4a246)
* ui: add new language filter autocomplete (#477) (4dcfdec)
* verdaccio-memory: race condition on save a package (#365) (70c1fb1)
* restore Node v8 support (#361) (9be55a1)
> feat: update verdaccio plugins and dependencies

- .github/workflows/e2e-angular-cli-workflow.yml
- .github/workflows/e2e-gatsbyjs-cli-workflow.yml
- .github/workflows/e2e-jest-workflow.yml
- scripts/e2e-setup-ci.sh
- scripts/run-verdaccio.js
- src/api/endpoint/api/package.ts
This PR introduce few acceptant tests that run in few popular projects to verify all works as expected. It only checks basic things but good enough for real taste with multiple package managers, pnpm, yarn and npm (all latest). I had big inspiration from berry project.
https://github.com/yarnpkg/berry/blob/master/.github/workflows/e2e-jest-workflow.yml
> build: e2e acceptance tests

- package.json
- test/unit/modules/utils/__snapshots__/utils.spec.ts.snap
- yarn.lock
Basically this one but https://github.com/verdaccio/verdaccio/pull/1891 with snapshots updated.
> fix: update readme library

- README.md
Fix syntax highlight in README.md
> Fix syntax highlight in README.md

- Dockerfile
> fix: upgrade docker base image nodejs

- Dockerfile
> fix: update Dockerfile to Node v12.18.4

- packages/auth/package.json
- packages/auth/src/auth.ts
- packages/auth/src/crypto-utils.ts
- packages/auth/src/index.ts
- packages/auth/src/utils.ts
- packages/auth/test/auth-utils.spec.ts
- packages/auth/test/crypto-utils.spec.ts
- packages/utils/package.json
- packages/utils/src/auth-utils.ts
- packages/utils/src/crypto-utils.ts
- packages/utils/test/auth-utils.spec.ts
- pnpm-lock.yaml
> refactor: auth-utils

- packages/core/commons-api/package.json
- packages/core/file-locking/package.json
- packages/core/readme/package.json
- packages/core/streams/package.json
- packages/core/types/package.json
some packages from monorepo still had outdated package.jsons
> fix urls in some packages/*/package.json

- .github/workflows/ci.yml
- .github/workflows/e2e-angular-cli-workflow.yml
- .github/workflows/e2e-config.yaml
- .github/workflows/e2e-gatsbyjs-cli-workflow.yml
- .github/workflows/e2e-jest-workflow.yml
- .npmrc
- scripts/e2e-config.yaml
- add custom config file for E2E
- add **yarn berry** to regular E2E
- add **npm 7 next release** to regular E2E
> test: add e2e config file

- .secrets-baseline
- src/api/middleware.ts
- test/unit/modules/api/api.spec.ts
- test/unit/partials/config/yaml/api.spec.yaml
Try to fix a bug on try to write the stream when has been already sent 
closes https://github.com/verdaccio/verdaccio/issues/877
I could not reproduce it.
> test: add test for socket timeout

- .github/FUNDING.yml
We just got the approval for GitHub sponsors 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
All donations will be routed to Open Colllective !
> chore: add GitHub sponsor as funding

- .github/workflows/ci.yml
> build: test on node 15

- .changeset/fifty-jars-rest.md
- packages/middleware/src/middleware.ts
- packages/web/src/endpoint/package.ts
Improving typescript practices mentioned in https://github.com/verdaccio/verdaccio/issues/1461 and trying to catch up with the contributing guide.
Changes:
1. Remove @ts-ignore in  in `packages/web/src/endpoint/package.ts `
2. Remove :any and infer from existed lib in `packages/web/src/endpoint/package.ts `
3. Prevent variable re-assign declare new variable instead in `packages/web/src/endpoint/package.ts `
4. Fix type in `packages/middleware/src/middleware.ts`
> Improving typescript practices in `packages/web/src/endpoint/package.ts`

- src/api/web/endpoint/package.ts
We use https://github.com/juanpicado/verdaccio-sentry and detected an error
> fix: check author if lastest is not found

- src/api/endpoint/api/publish.ts
- test/functional/readme/pkg-readme-npm6.json
- test/functional/readme/readme.ts
Fix missing readme on npm7
https://github.com/verdaccio/verdaccio/issues/1905
> fix: fix missing readme on npm7

- package.json
- yarn.lock
> feat: update UI theme

- .github/workflows/ci.yml
> chore: update pnpm on ci 

- README.md
* rearrange some based on the star count
* remove two duplicates
* add star count to "workshopper how to npm" because they
recently achieved 1k stars
> Update projects using Verdaccio and their stars

- .github/workflows/e2e-jest-workflow.yml
- add pnpm6 alpha to the e2e cli
> chore: add pnpm6 to e2e cli

- docs/env.variables.md
- src/lib/bootstrap.ts
follow up of https://github.com/verdaccio/verdaccio/pull/2121
Add env variable to enable gracefully shutdown `VERDACCIO_HANDLE_KILL_SIGNALS` on `SIGINT`, `SIGTERM` and `SIGHUP`
by @edify42
> feat: handle kill signals nicely 

- .eslintrc
- .github/workflows/ci-e2e-ui.yml
- .github/workflows/ci-e2e.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- test/unit/modules/cli/cli.spec.ts
CI was being running only on Node 10  🙈 due at typo
> build: fix node version issue on ci

- .changeset/big-lobsters-sin.md
- .github/workflows/ci.yml
- .prettierignore
- packages/core/local-storage/src/local-database.ts
- packages/core/local-storage/src/pkg-utils.ts
- packages/core/local-storage/src/read-file.ts
- packages/core/local-storage/src/token.ts
- packages/core/local-storage/src/utils.ts
- packages/core/local-storage/tests/local-database.test.ts
- packages/core/local-storage/tests/utils.test.ts
- packages/core/types/index.d.ts
- packages/mock/src/mock.ts
- packages/plugins/aws-storage/src/index.ts
- packages/plugins/google-cloud-storage/src/data-storage.ts
- packages/plugins/memory/src/local-memory.ts
- packages/server/test/storage/index.spec.ts
- packages/store/src/local-storage.ts
- packages/store/src/search.ts
- packages/store/src/storage.ts
- packages/store/test/local-storage.spec.ts
- packages/store/test/search.spec.ts
- packages/types/index.ts
Gives a storage plugin the ability to perform asynchronous tasks on initialization
Plugin must have an init method in which asynchronous tasks can be executed
```js
public async init(): Promise<void> {
this.data = await this._fetchLocalPackages();
this._sync();
}
```
> feat!: async storage plugin bootstrap

- src/api/endpoint/api/publish.ts
- src/api/endpoint/api/star.ts
- src/api/endpoint/api/user.ts
- src/api/endpoint/api/v1/token.ts
- src/api/middleware.ts
- src/lib/auth-utils.ts
- src/lib/auth.ts
- src/lib/local-storage.ts
- src/lib/notify/notify-request.ts
- src/lib/up-storage.ts
Using debug for trace and improve logging calls.
> refactor: improve logging

- package.json
- packages/api/tsconfig.json
- packages/auth/package.json
- packages/auth/tsconfig.json
- packages/cli/tsconfig.json
- packages/config/tsconfig.json
- packages/core/htpasswd/tsconfig.json
- packages/core/local-storage/tsconfig.json
- packages/core/tarball/tsconfig.json
- packages/core/url/tsconfig.json
- packages/hooks/tsconfig.json
- packages/loaders/tsconfig.json
- packages/logger-prettify/tsconfig.json
- packages/middleware/tsconfig.json
- packages/mock/tsconfig.json
- packages/node-api/tsconfig.json
- packages/plugins/active-directory/tsconfig.json
- packages/plugins/audit/tsconfig.json
- packages/plugins/auth-memory/tsconfig.json
- packages/plugins/aws-storage/tsconfig.json
- packages/plugins/google-cloud-storage/tsconfig.json
- packages/plugins/memory/tsconfig.json
- packages/plugins/ui-theme/tsconfig.json
- packages/proxy/tsconfig.json
- packages/server/tsconfig.json
- packages/store/tsconfig.json
- packages/utils/tsconfig.json
- packages/verdaccio/tsconfig.json
- packages/web/tsconfig.json
- pnpm-lock.yaml
Add script to update automatically the tsconfig.json [project references](https://www.typescriptlang.org/docs/handbook/project-references.html)
https://github.com/eBayClassifiedsGroup/update-ts-references
> chore: add update-ts-references

- .eslintignore
- .github/workflows/docker-publish.yml
- LICENSE
- README.md
- scripts/publish.sh
The last change before final release.
> feat: prepare release for v5

- conf/default.yaml
- conf/docker.yaml
- src/api/middleware.ts
- src/api/web/html/renderHTML.ts
Fix confusion with `logo` and `favicon` properties on web.
> fix: logo and favicon configuration

- .github/workflows/ci.yml
- .github/workflows/format.yml
> chore: format as separated workflow

- .changeset/healthy-poets-compare.md
- docs/env.variables.md
- packages/config/src/config.ts
- packages/config/test/config-parsing.spec.ts
- packages/config/test/config.spec.ts
- packages/config/test/package-access.spec.ts
- packages/config/test/partials/config/yaml/storage.yaml
- packages/config/test/uplinks.spec.ts
- packages/config/test/utils/index.ts
- packages/config/test/utils/parse-configuration-file.ts
> feat: environment variables support in configuration file

- src/lib/search.ts
- test/unit/modules/search/search.spec.ts
- test/unit/modules/web/api.web.spec.ts
Fix issue https://github.com/verdaccio/verdaccio/issues/1791
I know this is lunr's problem, but we can take a quick fix as soon as possible.
> fix: scoped query support

- .changeset/afraid-mice-obey.md
- packages/core/types/index.d.ts
- packages/plugins/ui-theme/src/App/Header/Header.test.tsx
- packages/plugins/ui-theme/src/App/Header/Header.tsx
- packages/plugins/ui-theme/src/App/Header/HeaderRight.tsx
- packages/plugins/ui-theme/src/providers/config/AppConfigurationProvider.tsx
- packages/plugins/ui-theme/tools/_verdaccio.config.yaml
- packages/plugins/ui-theme/types/index.ts
- packages/web/src/api/package.ts
- packages/web/src/api/readme.ts
- packages/web/src/middleware/web-api.ts
- packages/web/src/renderHTML.ts
- packages/web/src/utils/web-utils.ts
- packages/web/test/api.user.test.ts
- packages/web/test/config/login-disabled.yaml
- pnpm-lock.yaml
- test/e2e-ui/config/config-protected-e2e.yaml
- test/e2e-ui/config/config-scoped-e2e.yaml
- test/e2e-ui/e2e.spec.js
- test/e2e-ui/package.json
It might be the case the login could be disabled from UI, either for security reasons or any other preference.
Additionally (since UI test were failing)
- Update puppeteer
- Remove some warnings
- Add more checks
> UI: allow disable login UI

- packages/proxy/package.json
- packages/proxy/test/conf/proxy1.yaml
- packages/proxy/test/headers.auth.spec.ts
- packages/proxy/test/proxy.spec.ts
- pnpm-lock.yaml
> chore: add test for proxy

- packages/config/src/config-path.ts
- packages/config/src/config.ts
- packages/config/test/config.path.spec.ts
- packages/config/test/config.spec.ts
- packages/config/test/package-access.spec.ts
- packages/config/test/partials/config/yaml/config-getMatchedPackagesSpec.yaml
- 95% coverage
- Add test for creating configuration file
- Additional check if configuration file is readable or not (this is confusing sometimes since error returned is misleading) 
- Add debug code
> additional tests for config pkg

- src/lib/cli/commands/init.ts
> fix: add logger if init fails

- Dockerfile
update docker base image node 14.17.1
> fix: update docker base image node 14.17.1

- website/src/components/Features.tsx
- website/src/components/Header.tsx
- website/src/components/WhatIsVerdaccio.tsx
- website/src/pages/help.tsx
> fix: useBaseUrl on translated links

- pnpm-lock.yaml
- website/docusaurus.config.js
- website/package.json
Since it introduces a little breaking change I've decided to move fast and avoid any `pnpm install` that updates automatically to beta.4 and breaks the web.
There're some cool new features, many of them for mobile :)
> docs: update to @docusaurus/beta-4

- src/api/middleware.ts
[#2313](https://github.com/verdaccio/verdaccio/issues/2313)
[#2310](https://github.com/verdaccio/verdaccio/discussions/2310)
> fix: plugin allow_publish (pkg) got a undefined version #2313

- .github/workflows/website.yml
- website/src/components/FeatureCard.module.scss
- website/src/css/_buttons.scss
- website/src/css/_headers.scss
- website/src/css/custom.scss
I've got some reports that font size is too small and not accessible enough, actually yes it is a bit small, I have a big screen and looks really small and headers looks a bit bigger in comparison.
> website: updagre text size

- website/docs/articles.md
- website/docs/best-practices.md
- website/docs/caching.md
- website/docs/config.md
- website/docs/packages.md
- website/docs/plugin-auth.md
- website/docs/plugin-generator.md
- website/docs/plugins.md
- website/docs/puppet.md
Type: documentation
Description:
Made corrections to the typos i found in the documentations.
> docs: fix typos

- package.json
- packages/logger-prettify/package.json
- packages/node-api/package.json
- pnpm-lock.yaml
Always a joy to remove an unused dependency :)
> build: remove some unused dependencies

- crowdin.yaml
- packages/plugins/ui-theme/src/App/Header/LanguageSwitch.tsx
- packages/plugins/ui-theme/src/components/AutoComplete/AutoCompleteV2.tsx
- packages/plugins/ui-theme/src/i18n/config.ts
- packages/plugins/ui-theme/src/i18n/crowdin/en-US.json
- packages/plugins/ui-theme/src/i18n/enabledLanguages.ts
- website/src/components/Header.tsx
- easier configuration for adding more languages to UI
- upload en-US file to crowdin
> refactor: one single file for i18n conf ui

- packages/core/server/package.json
- packages/core/server/src/routes/web/api/readme.ts
- packages/core/server/src/server.ts
- pnpm-lock.yaml
implement readme web endpoint to fastify #2155
> feat: migrate readme to fastify

- packages/cli/src/commands/FastifyServer.ts
Introduce warning codes for better developer experience: VERDEP001
> use warning code for deprecation warnings

- .changeset/ten-parents-breathe.md
- packages/core/server/src/endpoints/dist-tags.ts
- packages/core/server/src/plugins/coreUtils.ts
- packages/core/server/src/server.ts
- packages/store/src/storage.ts
dist tags Implementation on Fastify part of #2623. Tagging a package endpoints are still missing
> dist-tags endpoint fastify

- packages/core/server/src/plugins/storage.ts
> fix initialization storage on fastify

- docker-examples/v5/reverse_proxy/nginx/relative_path/docker-compose.yml
- docker-examples/v5/reverse_proxy/nginx/relative_path/docker-compose_ssl.yml
- docker-examples/v5/reverse_proxy/nginx/root_path/docker-compose.yaml
Update the verdaccio image version to V5
> Docker examples v5

- website/src/components/Contributors.tsx
fix issues with accesibility(tabIndex and handleKeyDown) and eslint(material ui)
> Add total contributors to the header page and fix issues

- packages/core/server/src/routes/web/api/sidebar.ts
Add params schema validation for sidebar endpoints
#2623
> Add params validation for sidebar fastify web endpoints 

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
Upgrade to `pnpm@6.24.1` on CI
> chore: update pnpm on ci

- src/lib/auth-utils.ts
- src/lib/constants.ts
Reduce 7 days expiration time on website login to 1 hour as expiration time to improve security measures.
If you need more expiration time, you can do it via configuration. https://verdaccio.org/docs/configuration#security
> feat: jwt default time new set

- .github/workflows/ci.yml
- packages/server/test/storage/index.spec.ts
- packages/tools/mock/src/constants.ts
- packages/verdaccio/test/test.conf.js
- Enable CI for all node.js versions in master
> chore: enable ci node 15 and higher

- .babelrc
- .github/workflows/ci.yml
- Dockerfile
- README.md
Moving to active v16 
https://nodejs.org/en/about/releases/
> feat!: Node v16 as minimum for verdaccio 6

- .changeset/thick-countries-move.md
- packages/logger-prettify/package.json
- packages/logger/package.json
- pnpm-lock.yaml
ref https://github.com/pinojs/pino/releases?page=2
- pending use [transports](https://github.com/pinojs/pino/blob/v7.0.0/docs/transports.md) to replace prettify settings.
> feat: upgrade to pino v7

- packages/core/core/package.json
- packages/core/core/src/warning-utils.ts
- pnpm-lock.yaml
> Move from fastify-warning to process-warning

- package.json
- packages/auth/src/legacy-token.ts
- packages/core/types/package.json
- packages/plugins/audit/package.json
- packages/tools/benchmark/package.json
- pnpm-lock.yaml
consistency with node-fetch, types/node
> chore: consistency core dependencies

- Dockerfile
> fix: update docker to v14.18.2

- docker-examples/v4/docker-local-storage-volume/conf/config.yaml
- docker-examples/v4/ldap-verdaccio/conf/config.yaml
- docker-examples/v4/multi-registry-uplink/server1/conf/config.yaml
- docker-examples/v4/multi-registry-uplink/server2/conf/config.yaml
- docker-examples/v4/multi-registry-uplink/server3/conf/config.yaml
- docker-examples/v6/docker-local-storage-volume/conf/config.yaml
- packages/config/src/conf/default.yaml
- packages/config/src/conf/docker.yaml
- website/docs/config.md
These were broken by a70454c7b2c9.
> fix: Fix links to configuration in source tree.

- .changeset/red-yaks-sell.md
- packages/logger/src/logger.ts
> Fix re-opening log files using SIGUSR2

- docs/env.variables.md
- src/lib/config.ts
- test/unit/modules/config/config.spec.ts
Follow up of https://github.com/verdaccio/verdaccio/pull/2199 in v5
> feat: new environment variable (storage path) 

- packages/config/src/conf/default.yaml
- packages/config/src/conf/docker.yaml
found a very small typo while using Verdaccio (great tool!). here's a drive-by fix! :D
> fix: typo in config template

- .changeset/spicy-snakes-sip.md
- packages/plugins/ui-theme/src/store/models/manifest.ts
Fix https://github.com/verdaccio/verdaccio/issues/3006
> fix: specific version package detail page not showing

- .github/workflows/e2e-jest-workflow.yml
- test/unit/modules/basic_system.spec.ts
- Enable smoke test for pnpm 7 and npm8 latests
> chore: enable test e2e pnpm7

- .changeset/dull-monkeys-search.md
- packages/plugins/ui-theme/src/App/Footer/Footer.tsx
- packages/plugins/ui-theme/src/components/Logo/Logo.tsx
The link of the footer logo is verdaccio website, so the logo should be verdaccio's
> fix(ui-theme): show default logo in footer

- src/lib/logger/logger.ts
Fix regression ref https://github.com/verdaccio/verdaccio/pull/3011#issuecomment-1061379740
> fix: missing colors on terminal

- website/docs/config.md
- website/docs/plugins.md
- website/docs/web.md
- website/docusaurus.config.js
- website/package.json
Interesting info is being located here https://verdaccio.org/blog/2021/04/14/verdaccio-5-migration-guide but people does not find it.
> chore: move blog docs to pages

- conf/default.yaml
- conf/docker.yaml
- src/api/web/html/renderHTML.ts
This is a new PR related to [https://github.com/verdaccio/verdaccio/pull/3108](https://github.com/verdaccio/verdaccio/pull/3108).
> feat(web): add a config item to web，let the developer can select whether enable the html cache

- packages/config/src/conf/default.yaml
- packages/config/src/conf/docker.yaml
update configuration files with docs
> update configuration files with docs

- website/docs/who-is-using.md
Added a missing word; "We will happy..." -> "We will be happy..."
> fix: missing word

- src/api/web/html/renderHTML.ts
https://github.com/isaacs/node-lru-cache/blob/5b88486f2153822e1cbaec9293c13d77e644f8c1/CHANGELOG.md#v7---2022-02
> fix: remove lru deprecation warning

- website/docs/articles.md
Hi, I would like to contribute to the inclusion of my article about verdaccio in Portuguese Brazil.
> add portuguese-br article

- website/docs/uplinks.md
A small language tweak to uplinks.md.
> Small language tweak to uplinks.md.

- package.json
- packages/tools/docusaurus-plugin-contributors/src/contributors.json
- packages/tools/docusaurus-plugin-contributors/src/index.ts
- pnpm-lock.yaml
- website/package.json
- website/src/components/Contributors/Contributors.tsx
> chore: migrate material ui old dep

- website/docs/cli.md
- Minor corrections and additions
- Added link to possible formats for `listen` command
> Update docs for cli

- .changeset/smooth-owls-pump.md
- packages/plugins/ui-theme/src/App/Header/Support/Support.tsx
This PR contains some grammatical fixes to the Ukraine message.
> ui: basic grammatical fixes in the Ukraine Message

- .changeset/chilly-glasses-occur.md
- .changeset/config.json
- packages/api/src/package.ts
- packages/api/test/integration/package.spec.ts
- packages/core/core/src/constants.ts
- packages/core/core/src/index.ts
- packages/core/core/src/string-utils.ts
- packages/core/core/test/string-utils.spec.ts
- packages/server/fastify/src/endpoints/manifest.ts
- packages/store/src/storage.ts
follow up of https://github.com/verdaccio/verdaccio/pull/3359
> fix: abbreviated headers handle quality values

- src/api/middleware.ts
fix https://github.com/verdaccio/verdaccio/issues/3357#issuecomment-1238835711
> fix: remove stringify with space responses

- test/cli/README.md
- test/cli/cli-commons/src/process.ts
- test/cli/cli-commons/src/utils.ts
- test/cli/e2e-npm6/audit.spec.ts
- test/cli/e2e-npm7/audit.spec.ts
- test/cli/e2e-npm8/audit.spec.ts
- test/cli/e2e-pnpm6/audit.spec.ts
- test/cli/e2e-pnpm7/audit.spec.ts
- test/cli/e2e-yarn1/audit.spec.ts
- test/cli/e2e-yarn2/audit.spec.ts
- test/cli/e2e-yarn2/yarn-project/package.json
- test/cli/e2e-yarn3/audit.spec.ts
- test/cli/e2e-yarn3/info.spec.ts
- test/cli/e2e-yarn3/yarn-project/.yarnrc.yml
- test/cli/e2e-yarn3/yarn-project/package.json
- test/cli/e2e-yarn4/utils.ts
- test/cli/e2e-yarn4/yarn-project/package.json
> test: e2e audit cmd

- Dockerfile
Updated docker base to  14.20.1
> fix: docker base image upgraded 14.20.1

- .github/workflows/changesets.yml
- .github/workflows/ci.yml
- .github/workflows/website.yml
- crowdin.yaml
- website/docusaurus.config.js
mapping crowding versioned files
> chore: crowdin mapping

- .changeset/slow-snails-sniff.md
- e2e/ui/cypress/support/commands.ts
- packages/api/src/v1/search.ts
- packages/plugins/ui-theme/jest/jest.config.js
- packages/plugins/ui-theme/src/App/Header/Search/Search.tsx
- packages/plugins/ui-theme/src/providers/API/api.ts
- packages/plugins/ui-theme/src/store/models/search.ts
- packages/web/src/api/search.ts
- pnpm-lock.yaml
On search via UI the abort request is never triggered
> fix: improve abort request search

- .changeset/thick-geese-wash.md
- packages/api/src/user.ts
- packages/api/src/v1/token.ts
- packages/api/test/integration/_helper.ts
- packages/auth/src/auth.ts
- packages/auth/test/auth-utils.spec.ts
- packages/config/src/security.ts
- packages/config/src/user.ts
- packages/core/core/src/constants.ts
- packages/core/url/tests/getPublicUrl.spec.ts
- packages/middleware/src/middleware.ts
- packages/plugins/local-storage/package.json
- packages/web/package.json
- packages/web/src/api/user.ts
- packages/web/src/middleware/render-web.ts
- packages/web/src/renderHTML.ts
- packages/web/test/api.user.test.ts
- pnpm-lock.yaml
Migrate improvements form v5 to v6:
Query: https://github.com/verdaccio/verdaccio/issues?q=label%3A%22pending+6.x%22+is%3Aclosed
- https://github.com/verdaccio/verdaccio/pull/3158
- https://github.com/verdaccio/verdaccio/pull/3151
- https://github.com/verdaccio/verdaccio/pull/2271
- https://github.com/verdaccio/verdaccio/pull/2787
- https://github.com/verdaccio/verdaccio/pull/2791
- https://github.com/verdaccio/verdaccio/pull/2205
> chore: move improvements from v5 to v6

- docker-examples/v4/plugins/docker-extend/Dockerfile
- docker-examples/v5/plugins/docker-build-install-plugin/Dockerfile
- docker-examples/v5/plugins/docker-build-install-plugin/README.md
- docker-examples/v5/plugins/docker-build-install-plugin/docker.yaml
- docker-examples/v6/plugins/docker-build-install-plugin/docker.yaml
- website/versioned_docs/version-5.x/cli.md
- website/versioned_docs/version-5.x/config.md
- website/versioned_docs/version-5.x/docker.md
- website/versioned_docs/version-5.x/env.md
- website/versioned_sidebars/version-5.x-sidebars.json
-  Add env variables page
- Improve docker plugin docs
- Fix some bugs on docs
Follow up of https://github.com/verdaccio/verdaccio/pull/3475
Related to https://github.com/verdaccio/verdaccio/issues/1677
> docs: improve docker docs for 5.x

- .changeset/famous-bikes-kneel.md
- packages/plugins/ui-theme/src/i18n/crowdin/ui.json
- packages/plugins/ui-theme/src/pages/home/PackageList/Help/Help.tsx
- packages/plugins/ui-theme/src/pages/home/PackageList/Help/__snapshots__/Help.test.tsx.snap
- website/docs/setup-npm.md
- website/versioned_docs/version-5.x/install.md
- website/versioned_docs/version-5.x/setup-npm.md
Additional info regarding the npm login and npm adducer shipped by npm9
> chore: improve info regarding using private registries

- .changeset/brave-seahorses-press.md
- packages/plugins/ui-theme/package.json
- packages/plugins/ui-theme/src/pages/Version/DetailContainer/Readme/Readme.tsx
- packages/plugins/ui-theme/src/pages/Version/DetailContainer/Readme/__snapshots__/Readme.spec.tsx.snap
- pnpm-lock.yaml
> fix: markdown ul and img styles

- .github/workflows/release.yml
- .npmignore
- Add missing types into the package (reported some ticket I cannot find)
- Add `systemd` script by request https://github.com/verdaccio/verdaccio/discussions/3536#discussion-4682444
> fix: include build types and systemd

- .changeset/chatty-pillows-perform.md
- packages/api/test/integration/_helper.ts
- packages/config/package.json
- packages/config/test/config-parsing.spec.ts
- packages/core/core/package.json
- packages/core/core/src/file-utils.ts
- packages/core/file-locking/package.json
- packages/core/file-locking/src/utils.ts
- packages/core/tarball/package.json
- packages/core/types/package.json
- packages/core/url/package.json
- packages/hooks/package.json
- packages/loaders/package.json
- packages/loaders/src/plugin-async-loader.ts
- packages/logger-prettify/package.json
- packages/logger/package.json
- packages/plugins/local-storage/src/fs.ts
- packages/utils/package.json
- packages/verdaccio/src/server/registry.ts
Some internal improvements for https://github.com/verdaccio/verdaccio/pull/3569 and using v6 modules at v5
> fix: improve support for fs promises older nodejs

- .changeset/fluffy-papayas-lay.md
- packages/config/.babelrc
- packages/core/core/.babelrc
- packages/core/tarball/.babelrc
- packages/core/url/.babelrc
- packages/utils/.babelrc
Some package are used on #3569 need to run on Node 12
> Fix build target 5x

- Dockerfile
> fix: update docker base to 18.13.0

- .changeset/giant-years-trade.md
- e2e/cli/cli-commons/package.json
- e2e/cli/cli-commons/src/yarn-modern-utils.ts
- packages/config/package.json
- packages/config/src/parse.ts
- packages/config/test/__snapshots__/config-parsing.spec.ts.snap
- pnpm-lock.yaml
Unfortunatelly need node.js 12 for 5.x so need to rollback this dep
> rollback yaml support old nodejs versions

- .changeset/blue-cobras-study.md
- packages/cli/src/commands/init.ts
- packages/core/core/src/warning-utils.ts
- packages/core/types/src/configuration.ts
- packages/ui-components/.npmignore
improved context logging options and types
> fix: startup messages improved and logs support on types

- website/docs/config.md
Add section "Logger" to config page, with ref to full info on Features/logger
> Add section "Logger" to config page

- .changeset/honest-maps-hear.md
- e2e/cli/cli-commons/package.json
- e2e/cli/cli-commons/src/registry.ts
- e2e/ui/cypress.config.ts
- e2e/ui/package.json
- packages/verdaccio/src/server/registry.ts
- packages/verdaccio/test/basic.spec.ts
- packages/verdaccio/test/html.spec.ts
- packages/verdaccio/test/massive.spec.ts
- packages/verdaccio/test/proxy-multilpe-registry.spec.ts
- packages/verdaccio/test/race.spec.ts
- packages/verdaccio/test/server-query-spec.ts
- pnpm-lock.yaml
> fix: get-port missing dependency

- .changeset/pretty-clouds-help.md
- packages/config/src/conf/default.yaml
- packages/config/src/conf/docker.yaml
- packages/core/core/src/plugin-utils.ts
- packages/core/types/package.json
- packages/core/types/src/configuration.ts
- packages/core/types/src/manifest.ts
- packages/server/express/src/server.ts
- packages/store/src/storage.ts
same as https://github.com/verdaccio/verdaccio/pull/3274
> feat: trustProxy property

- .github/workflows/e2e-angular-cli-workflow.yml
- .github/workflows/smok-test-module.yml
- package.json
to avoid require is broken again
> chore: add test for require module

- src/lib/cli/commands/init.ts
> fix: package search

- .changeset/silly-moose-watch.md
- packages/plugins/htpasswd/src/htpasswd.ts
Add similar resolve path of htpasswd file same as 5.x plugin
> fix wrong htpasswd file location

- Dockerfile
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2023-04-12-version-18160-hydrogen-lts-danielleadams
> feat: update docker base image v18.16.0

- .changeset/tender-tigers-hammer.md
- packages/auth/test/auth.spec.ts
- packages/core/core/src/constants.ts
- packages/core/core/src/index.ts
- packages/core/types/src/configuration.ts
- packages/plugins/htpasswd/src/htpasswd.ts
- packages/plugins/htpasswd/src/utils.ts
- packages/plugins/htpasswd/tests/htpasswd.test.ts
- packages/plugins/htpasswd/tests/utils.test.ts
- Add https://github.com/verdaccio/monorepo/pull/589 feature from 5.x already used
- Follow up of #3712
> feat: async bcrypt hash

- website/docs/e2e.md
added simplified example that test the build and installation of the package
> added e2e example test

- packages/logger/logger-7/package.json
- packages/logger/logger-commons/package.json
- packages/logger/logger-prettify/package.json
- pnpm-lock.yaml
Reverts verdaccio/verdaccio#3834
> Revert "chore(deps): update dependency pino to v8.14.1 (master)"

- website/docs/cli-registry.md
Issue link : https://github.com/verdaccio/verdaccio/issues/3879
> fix(website): wrong spelling "depenging" to "depending" in documentation

- .changeset/rich-bananas-chew.md
- packages/api/src/index.ts
- packages/core/core/test/validation-utilts.spec.ts
- packages/middleware/src/middlewares/validation.ts
- packages/middleware/test/params.spec.ts
- packages/middleware/test/validation.spec.ts
- packages/server/express/jest.config.js
fix: #3915 for verdaccio 6 (5.x follow up)
> fix: official package - cannot be synced

- src/api/endpoint/api/package.ts
> fix: remove req.host deprecation warning

- Dockerfile
> fix: docker update v18.16.1

- .changeset/shiny-worms-retire.md
- package.json
- packages/search/package.json
- packages/search/src/indexer.ts
- packages/search/test/index.spec.ts
- pnpm-lock.yaml
Happens on upgrade orama 
```
fatal--- uncaught exception, please report this
Error: Cannot insert document due schema validation failure on "keywords" property.
at createError (/.yarn/cache/@verdaccio-search-
```
> fix: local search keyword undefined errors

- src/lib/cli.ts
- Allow only minimum Node.js 16
> fix: check if node.js minimum version is correct

- .github/workflows/e2e-ci.yml
- CONTRIBUTING.md
- e2e/cli/cli-commons/src/process.ts
- e2e/cli/cli-commons/src/utils.ts
- packages/api/src/index.ts
- packages/api/src/publish.ts
- packages/auth/src/auth.ts
- packages/core/types/src/manifest.ts
- packages/middleware/src/middlewares/antiLoop.ts
- packages/store/src/storage.ts
- Removed the silentNpm function as it was not being used anywhere
- Type guard for childProcess.stdout in process.ts
- fix type errors by adding type guards
- fix typos
- Attempted to remove some ts-ignore comments
> Get rid of @ts-ignore (iteration 1 or many more to go)

- website/docs/who-is-using.md
Hello!
I wanted to add my new tool [secco](https://secco.lekoarts.de) to the "Who is using Verdaccio" page :)
I used to work at Gatsby and we've been big fans of Verdaccio so it was a pleasure to continue using it.
Thanks for maintaining it!
> docs: Add secco to "Who is using"

- src/api/endpoint/api/search.ts
- src/api/endpoint/index.ts
regression of https://github.com/verdaccio/verdaccio/commit/43de79d46a9a41313489f30992dcd7cbecddc8ad#diff-725260c5be049ab2bc174657908cd3e53c08876276fb2ded1e0c2f0661a43475
> fix: restore search all endpoint

- CONTRIBUTING.md
Add a hint for others who want to contribute. It's certainly not a typical, little js package 😉
> chore: add note about disk space requirement to contribution guidelines

- scripts/addon-update.ts
Fixes [Incomplete multi-character sanitization](https://github.com/verdaccio/verdaccio/security/code-scanning/212)
> chore(website): addons update codeql

- .changeset/young-donuts-own.md
- packages/config/jest.config.js
- packages/config/src/package-access.ts
- packages/config/test/agent.spec.ts
- packages/config/test/builder.spec.ts
- packages/config/test/config.spec.ts
- packages/config/test/package-access.spec.ts
Test coverage had dropped below 85% (on windows):
I added some tests to get it over 90%:
> chore(config): increase test coverage

- .changeset/wild-otters-talk.md
- packages/api/jest.config.js
- packages/api/src/v1/profile.ts
- packages/api/test/integration/config/profile.yaml
- packages/api/test/integration/profile.spec.ts
- if password payload is not correct was not well. handled
> fix: bug on change password npm profile

- .changeset/thirty-toes-swim.md
- e2e/ui/README.md
- e2e/ui/cypress.config.ts
- e2e/ui/cypress/e2e/home.cy.ts
- packages/plugins/ui-theme/package.json
- packages/plugins/ui-theme/src/App/App.tsx
- packages/ui-components/package.json
- packages/ui-components/src/sections/Header/HeaderSettingsDialog.tsx
- packages/ui-components/src/sections/Header/RegistryInfoContent/RegistryInfoContent.tsx
- pnpm-lock.yaml
On click settings dialog the page crashes, due broken dependency (not used) bug only present at `v5.29.1`
> fix: ui dialog break pages on open due remark error

- CONTRIBUTING.md
> docs: fix typos in CONTRIBUTING

- src/lib/cli/commands/version.ts
> fix: newline after version command

- website/docs/who-is-using.md
Nx now supports Verdaccio officially.
> docs: update who-is-using.md

- .changeset/sharp-wolves-carry.md
- packages/signature/package.json
- packages/signature/src/index.ts
- packages/signature/src/legacy-signature/index.ts
- packages/signature/src/legacy-signature/legacy-backward-compatible.ts
- packages/signature/src/legacy-signature/legacy-crypto.ts
- packages/signature/src/signature.ts
- packages/signature/test/legacy-token-deprecated-backward-compatible.spec.ts
- packages/signature/test/legacy-token.spec.ts
- pnpm-lock.yaml
ref https://github.com/verdaccio/verdaccio/issues/4601
> support for createCipher backward compatible

- website/docs/plugin-generator.md
- website/versioned_docs/version-5.x/plugin-generator.md
- website/versioned_docs/version-6.x/plugin-generator.md
> docs: avoid using yo 5.x for plugin developer

- src/api/endpoint/index.ts
- src/api/index.ts
- src/api/middleware.ts
- test/helpers/initializeServer.ts
already used in master, not longer need it
> chore: clean up old code

- .changeset/big-cameras-invent.md
- packages/store/test/storage-utils.spec.ts
- packages/store/test/storage.spec.ts
- packages/store/test/versions.spec.ts
Fixes a few typescript warnings I got in VSCode.
> chore: fix types for some store tests

- website/docs/setup-bun.md
- website/docs/setup-deno.md
- website/sidebars.js
- website/versioned_docs/version-5.x/setup-bun.md
- website/versioned_docs/version-5.x/setup-deno.md
- website/versioned_docs/version-6.x/setup-bun.md
- website/versioned_docs/version-6.x/setup-deno.md
- website/versioned_sidebars/version-5.x-sidebars.json
- website/versioned_sidebars/version-6.x-sidebars.json
Not sure if is entirely accurate, looking for feedback
> Add documentation for bun and deno using private registry

- .changeset/dirty-islands-push.md
- packages/plugins/ui-theme/package.json
- packages/plugins/ui-theme/src/i18n/crowdin/ui.json
- packages/plugins/ui-theme/src/i18n/enabledLanguages.ts
- packages/ui-components/src/sections/Footer/Footer.tsx
- pnpm-lock.yaml
Avoid the following ts warning:
`Type 'FlagComponent' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>>'.ts(2322)`
Adds country description on hover:
> chore: fix type for country flags and hover titles

- .changeset/good-lions-rush.md
- packages/ui-components/package.json
- pnpm-lock.yaml
Fixing dependencies to the same versions in ui-components and ui-themes:
https://github.com/verdaccio/verdaccio/blob/master/packages/plugins/ui-theme/package.json
https://github.com/verdaccio/verdaccio/blob/master/packages/ui-components/package.json
> chore: sync dependency defs between ui-components and ui-theme

- .changeset/witty-meals-nail.md
- packages/api/src/index.ts
Remove TODO and clarify handling of express route parameters
> chore(api): update comment about route parameters

- .changeset/fluffy-onions-act.md
- packages/middleware/src/middlewares/web/utils/template.ts
- packages/middleware/test/__snapshots__/template.test.ts.snap
> fix(middleware): link to favicon in template

- .changeset/moody-mugs-pay.md
- package.json
- packages/config/package.json
- packages/config/src/config-path.ts
- packages/config/src/config-utils.ts
- packages/config/test/__snapshots__/builder.spec.ts.snap
- packages/config/test/__snapshots__/config-parsing.spec.ts.snap
- packages/config/test/agent.spec.ts
- packages/config/test/builder.spec.ts
- packages/config/test/config-parsing.spec.ts
- packages/config/test/config-utils.spec.ts
- packages/config/test/config.path.spec.ts
- packages/config/test/config.spec.ts
- packages/config/test/package-access.spec.ts
- packages/config/test/token.spec.ts
- packages/config/test/uplinks.spec.ts
- packages/config/test/utils.spec.ts
- pnpm-lock.yaml
- update vitest to 2.0
- migrate config package to vitest
- improve debug on config package
- improve coverage
> chore: migrate config package to vitest

- .changeset/swift-rabbits-vanish.md
- packages/config/test/config.path.spec.ts
> fix(config): test runs on Windows

- .changeset/violet-boxes-float.md
- packages/api/src/package.ts
- packages/core/tarball/tests/convertDistRemoteToLocalTarballUrls.spec.ts
- packages/core/tarball/tests/getLocalRegistryTarballUri.spec.ts
- packages/store/src/storage.ts
This might help track down the cause of tarball issues like #4070.
- Add logging for getting tarballs from storage
- Add tests for scoped tarball urls
> fix(store): add logging when requesting tarball

- .github/workflows/changesets.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-proxy-apache-e2e.yml
- .github/workflows/docker-proxy-nginx-e2e.yml
- .github/workflows/docker-publish.yml
- .github/workflows/e2e-ci.yml
- .github/workflows/e2e-ui.yml
- .github/workflows/plugin-generator-e2e.yaml
- .github/workflows/shared-docker-publish.yml
- .github/workflows/static-data.yml
- .github/workflows/ui-components.yml
- .github/workflows/website.yml
- .github/workflows/x-smok-test-docker.yml
Dependabot updates the comments only if they are full semver
> chore(deps): update version comments in actions

- .changeset/gentle-stingrays-repeat.md
- .github/workflows/codeql-analysis.yml
- packages/plugins/local-storage/src/local-database.ts
- packages/store/src/storage.ts
Closes https://github.com/verdaccio/verdaccio/security/code-scanning/137, https://github.com/verdaccio/verdaccio/security/code-scanning/176
Apply recommendations for action
> fix: code scan issues

- website/src/components/EcosystemSearch/addons.json
Set the correct category of plugins + one addition `verdaccio-downloads-count`
> chore(website): update addons list

- website/docs/articles.md
- website/versioned_docs/version-6.x/articles.md
> chore(docs): add links to more articles

- website/docs/packages.md
- website/versioned_docs/version-6.x/packages.md
"unpublish" was missing in the table
> chore: add unpublish to package access config

- .changeset/gold-squids-watch.md
- packages/auth/src/auth.ts
- packages/server/express/src/server.ts
- packages/store/src/local-storage.ts
- packages/web/src/middleware.ts
Now the log lists all built-in plugins and themes
> chore: add info to log when audit, htpasswd, theme are used

- .github/actions/build-app/action.yml
- .github/actions/cache-packages/action.yml
- .github/actions/cache-store/action.yml
- .github/actions/install-app-node/action.yml
- .github/actions/install-app/action.yml
- .github/workflows/ci.yml
- .github/workflows/e2e-ci.yml
- .github/workflows/e2e-ui.yml
- .github/workflows/plugin-generator-e2e.yaml
- .github/workflows/static-data.yml
- .github/workflows/ui-components.yml
- .github/workflows/website.yml
- e2e/ui/package.json
- Reduce maintenance with GitHub actions
- Reuse common workflows
> chore: reuse workflows configurations

- .changeset/tricky-impalas-shake.md
- packages/plugins/local-storage/src/local-fs.ts
- packages/store/src/storage.ts
- Fix parameter handling for some error messages
- Harmonize the format of error messages
> chore: tweak error logging messages

- .changeset/cool-seals-watch.md
- packages/config/src/config.ts
- packages/loaders/src/plugin-async-loader.ts
- packages/loaders/test/partials/config/valid-plugin-store.yaml
- packages/loaders/test/partials/test-plugin-storage/verdaccio-plugin-store/index.js
- packages/loaders/test/partials/test-plugin-storage/verdaccio-plugin-store/package.json
- packages/loaders/test/plugin_loader_async.spec.ts
- Replace `Params` with `pluginOptions`
- Add test for loading storage plugin
> chore(loader): fix types for plugin options

- website/docs/config.md
- website/versioned_docs/version-6.x/config.md
Ref https://github.com/orgs/verdaccio/discussions/4967
> docs: fix security jwt config example

- .changeset/thirty-comics-trade.md
- packages/plugins/local-storage/src/local-fs.ts
- Remove duplicate msg
- Fix spelling
> chore: local storage debug messages

- src/api/web/api/package.ts
> fix #4984 improved paths for web endpoint

- .changeset/smooth-games-share.md
- .github/workflows/plugin-generator-e2e.yaml
- packages/api/src/dist-tags.ts
- packages/api/src/package.ts
- packages/api/src/ping.ts
- packages/api/src/publish.ts
- packages/api/src/search.ts
- packages/api/src/stars.ts
- packages/api/src/v1/profile.ts
- packages/api/src/v1/search.ts
- packages/api/src/v1/token.ts
- packages/api/src/whoami.ts
- packages/auth/package.json
- packages/middleware/package.json
- packages/middleware/src/index.ts
- packages/middleware/src/middlewares/api_urls.ts
- packages/middleware/src/middlewares/web/web-urls.ts
- packages/plugins/audit/package.json
- packages/server/express/package.json
- packages/tools/helpers/package.json
- packages/web/src/api/package.ts
- packages/web/src/api/readme.ts
- packages/web/src/api/search.ts
- packages/web/src/api/sidebar.ts
- packages/web/src/api/user.ts
- pnpm-lock.yaml
> fix #4984 crashes with path-to-regexp v0.1.12

- .changeset/slow-cars-guess.md
- packages/ui-components/src/components/SideBarTitle/SideBarTitle.stories.tsx
- packages/ui-components/src/components/SideBarTitle/SideBarTitle.tsx
- packages/ui-components/src/sections/SideBar/Sidebar.tsx
Some packages provide both ESM and CJS support.
This PR add support for that.
> feat(ui-components): support packages with multiple module types

- website/src/css/custom.scss
> website: fix color of selection in dark mode

- .changeset/rotton-readers-shave.md
- packages/config/src/builder.ts
- packages/core/types/src/configuration.ts
Replace `LoggerConfItem` with `LoggerConfigItem` (which has more details)
Closes #3728
> fix: config builder `addLogger`

- packages/tools/docusaurus-plugin-downloads/package.json
- pnpm-lock.yaml
- website/package.json
- website/src/components/Chart/NpmjsVersionsChart.tsx
- website/src/components/Chart/VersionDownloadsChart.tsx
- website/src/components/Downloads.tsx
> chore: improve charts

- website/docs/plugin-filter.md
- website/docs/plugin-theme.md
- website/docs/plugins.md
- website/versioned_docs/version-6.x/plugin-filter.md
- website/versioned_docs/version-6.x/plugin-theme.md
- website/versioned_docs/version-6.x/plugins.md
> fix(docs): notification/alert box formatting

- .github/workflows/changesets-pr.yml
- packages/ui-components/.storybook/main.ts
- packages/ui-components/.storybook/preview-head.html
- packages/ui-components/.storybook/preview.tsx
- packages/ui-components/package.json
- packages/ui-components/src/AppTest/App.stories.tsx
- packages/ui-components/src/components/Search/Search.stories.tsx
- packages/ui-components/src/layouts/Version/Version.stories.tsx
- packages/ui-components/src/sections/Detail/Detail.stories.tsx
- packages/ui-components/src/sections/Header/Header.stories.tsx
- packages/ui-components/src/sections/Home/Home.stories.tsx
- packages/ui-components/src/sections/SideBar/Sidebar.stories.tsx
- packages/ui-components/vitest/api/home.json
- pnpm-lock.yaml
Fix msw, was broken here https://github.com/verdaccio/verdaccio/pull/5056 (storyboook v8 upgrade)
> chore: fix msw local development

- .changeset/violet-baboons-beg.md
- packages/middleware/src/middlewares/web/render-web.ts
- packages/middleware/src/middlewares/web/web-middleware.ts
- packages/middleware/src/middlewares/web/web-urls.ts
- packages/web/src/api/index.ts
Expand use of `WebUrlsNamespace`
Follow-up #5094
> chore: middleware package update

- .changeset/eighty-apes-think.md
- packages/plugins/ui-theme/lib/constants.ts
- packages/plugins/ui-theme/package.json
- packages/ui-components/package.json
- pnpm-lock.yaml
Update `@microlink/react-json-view` to latest and remove obsolete `react-json-view` from theme
PS: also removes obsolete `lib\constants.ts`
> chore(ui): update react-json-view

- .changeset/few-ears-deny.md
- packages/api/src/user.ts
- packages/api/src/v1/profile.ts
- packages/config/src/config.ts
- packages/core/core/src/index.ts
- packages/middleware/src/middlewares/json.ts
- packages/plugins/local-storage/src/dir-utils.ts
- packages/server/fastify/src/endpoints/user.ts
- packages/server/fastify/src/plugins/coreUtils.ts
- packages/server/fastify/src/routes/web/api/login.ts
- packages/store/src/lib/star-utils.ts
- packages/store/src/lib/storage-utils.ts
- packages/store/src/storage.ts
- packages/store/test/storage-utils.spec.ts
- packages/store/test/storage.spec.ts
- packages/utils/src/utils.ts
- packages/utils/test/utils.spec.ts
- packages/web/src/api/user.ts
- Replaced `utils/src/utils.ts` `isObject` -> `validationUtils.isObject`
- Removed typo: `validatioUtils` -> `validationUtils`
- Removed unused code from `store/src/lib/storage-utils.ts`
> chore: cleanup utils

- .changeset/odd-fishes-cry.md
- packages/middleware/src/middlewares/allow.ts
- packages/middleware/test/allow.spec.ts
> fix(middleware): scoped package for allow checks

- .changeset/yellow-flies-sniff.md
- packages/auth/src/auth.ts
- packages/loaders/src/plugin-async-loader.ts
- packages/loaders/test/partials/test-plugin-storage/verdaccio-plugin/index.js
- packages/loaders/test/plugin_loader_async.spec.ts
- packages/search-indexer/package.json
- packages/server/express/src/server.ts
- packages/store/src/local-storage.ts
- packages/store/src/storage.ts
- packages/web/src/middleware.ts
> fix: add legacyMergeConfigs legacy plugins

- docker-examples/v6/README.md
- docker-examples/v6/verdaccio-github-oauth-ui/README.md
- docker-examples/v6/verdaccio-github-oauth-ui/docker-compose.yaml
- docker-examples/v6/verdaccio-github-oauth-ui/plugin/Dockerfile
- docker-examples/v6/verdaccio-github-oauth-ui/plugin/config.yaml
Add docker example with https://github.com/n4bb12/verdaccio-github-oauth-ui/ plugin
> chore: add docker example for verdaccio-github-oauth-ui

- src/lib/config.ts
Issues: #5175, #5160
A bit overkill to make a PR from my side as @juanpicado found out the problem
> fix: add missing packages argument on getMatchedPackagesSpec

- .changeset/dirty-countries-play.md
- packages/ui-components/src/components/Deprecated/Deprecated.tsx
- packages/ui-components/src/components/NoItems/NoItems.tsx
- packages/ui-components/src/components/Versions/Versions.tsx
> chore(ui): avoid ts error for Alerts

- .changeset/wicked-points-relate.md
- package.json
- packages/auth/src/auth.ts
- packages/auth/src/signature-legacy.ts
- packages/auth/src/utils.ts
- packages/auth/test/auth-utils-middleware.spec.ts
- packages/core/types/package.json
- packages/core/types/src/configuration.ts
- packages/signature/src/index.ts
- packages/signature/src/jwt-token.ts
- packages/signature/test/jwt.spec.ts
- pnpm-lock.yaml
Support full set of options from [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) for signing and verifying JWTs.
Closes #3681
> fix: support JWT sign and verify options

- .github/workflows/static-data.yml
missing stats. quite an impressing increase 🚀 
```json
{"downloads":998293,"start":"2025-01-01","end":"2025-01-31","package":"verdaccio"}
{"downloads":1094114,"start":"2025-02-01","end":"2025-02-28","package":"verdaccio"}
{"downloads":1317634,"start":"2025-03-01","end":"2025-03-31","package":"verdaccio"}
{"downloads":1332841,"start":"2025-04-01","end":"2025-04-30","package":"verdaccio"}
{"downloads":596580,"start":"2025-05-01","end":"2025-05-16","package":"verdaccio"}
```
> fix: monthly npm stats

- .changeset/hip-deers-join.md
- packages/core/core/src/constants.ts
Same codes just ordered and with comments that show on hover:
Before:
After:
> chore(core): http status codes

- src/api/endpoint/api/publish.ts
- Regression of https://github.com/verdaccio/verdaccio/pull/5090
- Restore api matchers for publish
> fix: unpublish broken #5214

- src/api/web/api/package.ts
- test/unit/partials/config/yaml/api.web.spec.yaml
Closes #5201 
See 8.x:
https://github.com/verdaccio/verdaccio/blob/85d8ea16d628bf1a4574843ea3be133e8ec1b04d/packages/web/src/api/package.ts#L25-L36
> fix: anonymous access web ui (6.x)

- .changeset/sweet-bulldogs-doubt.md
- packages/tools/local-scripts/src/index.ts
- packages/tools/local-scripts/tsconfig.json
- website/blog/2018-09-06-verdaccio-and-deterministic-lock-files.md
- website/blog/2018-10-21-verdaccio-4-alpha-release.md
- website/blog/2018-11-19-setting-up-verdaccio-on-digitalocean.md
- website/blog/2019-02-08-the-crazy-story-of-verdaccio.md
- website/blog/2019-02-24-migrating-verdaccio.md
- website/blog/2019-04-19-diving-into-jwt-support-for-verdaccio-4.md
- website/blog/2019-05-13-the-new-docker-image-verdaccio-4.md
- website/blog/2019-05-19-15-verdaccio-4-release.md
- website/blog/2019-07-08-verdaccio-410-release.md
- website/blog/2019-07-30-verdaccio-420-release.md
- website/blog/2019-09-07-managing-multiples-projects-with-lerna-and-yarn-workspaces.md
- website/blog/2019-09-30-verdaccio-430-release.md
- website/blog/2019-10-05-verdaccio-4-with-ldap-and-docker.md
- website/blog/2021-04-14-verdaccio-5-migration-guide.md
- website/docusaurus.config.js
- More author fixes
- Change local-script to ES imports
Should run smoothly now
> fix(docs): warnings during website build (2)

- .changeset/mean-timers-look.md
- packages/server/express/partials/store/htpasswd
- packages/server/express/src/server.ts
- Remove obsolete partial
- Remove incorrect debug msg
- Remove unnecessary ts-ignore
> chore(express): housekeeping
