- .gitignore
- conf/full.yaml
- lib/config.js
- lib/local-storage.js
- lib/storage.js
- lib/utils.js
- test/unit/st_merge.js
- test/unit/tag_version.js
Changed the way package distribution tags are processed and stored to replicate more closely the behaviour of the upstream repository (npmjs.org).
> Change the way package distribution tags are processed and stored

- lib/cli.js
- lib/config.js
Fix version numbers that got lost as a consequence of #13. This meant the user agent string and version reported in the log were incomplete.
> Fix missing version numbers

- lib/file-locking.js
- lib/local-fs.js
- lib/local-storage.js
- lib/plugin-loader.js
- lib/plugins/htpasswd/crypt3.js
- lib/plugins/htpasswd/index.js
- lib/plugins/htpasswd/utils.js
- npm-shrinkwrap.json
- package.json
This relates to (and fixes) #12 and #13.
I have eliminated dependencies on [sendanor/node-crypt3](https://github.com/sendanor/node-crypt3) and [baudehlo/node-fs-ext](https://github.com/baudehlo/node-fs-ext) which were not fully cross-platform.
Instead of `node-fs-ext`, we now use [npm/lockfile](https://github.com/npm/lockfile). This creates and releases advisory locks, and can re-use stale locks after a timeout period, so if there's a crash, things don't stay locked forever.
There is a new helper called `lib/file-locking.js` which is responsible for locking and unlocking local files. It appends `.lock` to the filename, and has some hard-coded parameters for re-using stale locks etc. I did not want to overcomplicate matters by adding soft configuration values which no-one would probably …
> Remove optional dependencies that are not truly cross-platform

- .npmignore
Trying to install verdaccio 2.0.0 fails on create binary links, file not found. Removing the restrictions from .npmignore fix the problem
> Fix #52 binary file missing

- lib/cli.js
The process still named sinopia, that might be confuse.
```
Juans-MBP:verdaccio jpicado$ ps -ef |grep verdaccio
501 19904 18047   0  8:34PM ttys001    0:00.00 grep verdaccio
Juans-MBP:verdaccio jpicado$ ps -ef |grep sinopia
501 19906 18047   0  8:34PM ttys001    0:00.00 grep sinopia
501 19875 19616   0  8:30PM ttys003    0:01.05 sinopia 
Juans-MBP:verdaccio jpicado$ 
```
> rename process to verdaccio

- lib/index-web.js
When using a custom index.hbs, if you try to render the entry template (after login) an exception is thrown. It makes sense to register the official entry template so it can be used.
> Register entry partial even if custom template is provided

- lib/plugins/htpasswd/index.js
This otherwise logs the user's full username and password in plaintext on `npm adduser`.
> Prevent logging of user and password

- conf/docker.yaml
There is a problem with the docker.yaml file.
auth:
   htpasswd:
     file:/verdaccio/config/htpasswd
The file property should point to /verdaccio/conf/htpasswd because folder /verdaccio/config dosen't exist and therefore dosen't let to create users.
Thank you for working on this great tool.
Regards
> Problem with docker.yaml

- README.md
rename `proxy_access` to `proxy`
see 6075034521d8f3442efc0d44d9ef7b0c174b1754 for reference
> Docs: correct config attribute `proxy_access`

- lib/plugins/htpasswd/utils.js
- package.json
- test/functional/adduser.js
Right now, htpasswd's default (eg. ```htpasswd .htpasswd myuser```) seems to be md5. Verdaccio tries to authenticate these using crypt3 - and thus users created in this method cannot log in.
This PR fixes it and maintains backwards compatibility by trying to decrypt with either crypt3 or md5.
> Allow htpasswd-created users to log in

- .gitignore
- .travis.yml
- README.md
- conf/docker.yaml
- index.js
- lib/GUI/css/styles.less
- lib/auth.js
- lib/cli.js
- lib/config.js
- lib/local-storage.js
- lib/logger.js
- lib/middleware.js
- lib/plugin-loader.js
- lib/plugins/htpasswd/index.js
- lib/storage.js
- lib/up-storage.js
- lib/utils.js
- test/README.md
- test/functional/lib/startup.js
- test/functional/plugins/authenticate.js
- test/functional/plugins/authorize.js
- test/integration/config.yaml
- test/integration/test.pl
- test/unit/toplevel.js
- test/unit/utils.js
Based on issue #88
__CHANGES:__
* Aside from a few locations (such as links to issues & the history), 'sinopia' has been renamed to  'verdaccio'.
* The [.travis.yml](https://github.com/kgrubb/verdaccio/blob/master/.travis.yml) has been updated to run on officially supported node versions (I can switch this back if needed).
> [GH-88] rename to Verdaccio instead of Sinopia

- README.md
Fix for issue #86. 
Just updating the readme to point to new verdaccio chef cookbook
> [GH-86] updated readme to point to new chef cookbook

- lib/index-web.js
When trying to access readme's under private local scopes "@scopename/test" it fails to load the readme because the express.js route can't handle slash's in it's parameters. Added another parameter to the route to allow for the optional scope.
> optional scope in the readme package name.

- Dockerfile.rpi
- README.md
- package.json
- Added instructions for build rpi image
- Added npm scripts for building images
> Added docker image for rpi

- lib/notify.js
There was a lack of feedback on notifications. This commit add a bit of verbose if all goes well.
and a bit more for additional information 
I tested this against the hipchat REST API, perhaps needs an improvement for different sort of  integrations.
> Increase verbose on notify request, helps #144

- lib/notify.js
Fix #144 
Instead update full.yaml file, it's provide support for array of headers and simple literal object.
> #144 Add fallback support to previous config files

- .travis.yml
- lib/GUI/css/styles.less
- lib/GUI/entry.hbs
- lib/GUI/js/search.js
- lib/cli.js
- lib/index-web.js
- lib/local-fs.js
- lib/local-storage.js
- lib/middleware.js
- lib/static/main.css
- lib/static/main.js
- test/unit/search.js
- Check permission in search API
- Fix author's name not show in search result
- Remove unused 'allow_failures' from travis config
- Fix search not work for multiple storage
- Fix deprecared warning with fs.unlink
- Fix npm search not show author's name
- Fix loading icon not show after first search
- Fix loading icon not align to center
Pick from fl4re's fork:
- Allow set intermediate SSL certificate
- Partial fix of search leak private packages name
I'm not familiar with git and just destroyed my repo and lost some changes... So i deleted my GitHub repo and reopen a new PR here, sorry for this.
@juanpicado
> Fix search feature

- lib/cli.js
With out the ca parameter in the https config section the server fails to start with a 500 error and complains that path must be a string.
> Add additional requirement to output message

- SERVER.md
- lib/index-web.js
- lib/utils.js
* Define utils function `get_base_url`.
* If url_prefix start with `/` construct base URL using protocol and host form request.
* Update SERVER.md with description of new `url_prefix` option.
Resolves #193
> Allow url_prefix to be only the path

- lib/storage.js
- test/unit/st_merge.js
If packages are being published to verdaccio as well as upstream to
npmjs.org, then when the cache is updated from npmjs.org it uses the
dist-tags from the upstream even if the locally published version is
actually newer. This makes it very difficult to use verdaccio as a
staging registry for testing out potential releases.
This change partially reverts a change in behaviour that was introduced
in #8 which caused a regression for the staging style workflow that was
supported by sinopia.
**Type:** bug / feature
Replaces #80
> don't blindly clobber local dist-tags

- README.md
I moved the config part up and added some keywords. This way "proxy configuration" stands right next to "Installation". If you think that would help please merge my changes.
Resolves #205
> config section moved up, some keywords added.

- SERVER.md
**Type:** document
* There is a related issue: close #207
**Resolves:**
Update docs about configure verdaccio behind reverse proxy
> docs: update docs with behind reverse proxy

- lib/index-web.js
Static sources were fetched using http when verdaccio was running behind a https nginx reverse proxy, failing. Now they are fetched using https, succeeding.
Resolves #???
> enable verdaccio behind a https nginx proxy

- .dockerignore
- .env
- Dockerfile
- README.md
- conf/docker.yaml
- docker-compose.yaml
- wiki/README.md
- wiki/docker.md
**Type:** bug (according to the related issue)
- ~I wasn't sure how to verify the modified `Dockerfiie` works without any custom port config (just like it worked before defaulting to port 4873)~.
- ~Should I be able to run `npm test` inside the container? (didn't work for me)~
- ~Should I be able to visit http://localhost:4873 in the browser and see something? (didn't work for me)~
- when knowing how to ensure docker build is working I could add a `docker-compose.test.yaml` to enable automatic testing on docker hub/ docker cloud. Should this go into a separate PR?
Resolves #213
> allow to configure port for docker

- README.md
**Type:** bug
Grammar error in README.md has been fixed:
`More then just NPM dependencies -> More than just NPM ...`
> Fixed grammar error in README

- README.md
**Type:** bug 
Puppet #87 still not supported, this remove the information from the README
Resolves #109
> Fix #109 Remove puppet section from Readme file

- Dockerfile
**Type:** bug
The following has been addressed in the PR: Signal handling for stopping the container and not being able to use https with containers
Before this PR the stopsignal that the docker daemon was sending to verdaccio wasnt reaching the main program. Dumb-init makes sure that this happens. Also I've updated the dockerfile to use the latest alpine node image that is going to be the LTS version soon. There was also no way to listen on HTTPS protocol, so I've added the option to be able to do so
> Updated Dockerfile & added proper signal handling

- wiki/docker.md
The following has been addressed in the PR: Missing documentation for PROTOCOL config
Added the documentation that was missing for my last pull request.
> Added documentation to the PROTOCOL configuration

- Dockerfile
**Type:** bug
The following has been addressed in the PR: There was a typo in the command creating the verdaccio user
**Description:** This exceptionally huge change makes it possible to use the image without chowning the whole volume in an init-container as mentioned in #238. :)
To be able to use it just make a change in your deployment file, add this to your [PodSpec](https://kubernetes.io/docs/api-reference/v1.6/#podspec-v1-core) (101 is the verdaccio group id)
```json
"securityContext": {
"fsGroup": 101
}                        
```
Resolves #238 
**BUT**
There is still a problem while trying to use the image like this: 
`docker run -it -v ~/test:/verdaccio/storage verdaccio/verdaccio:latest`
I believe that it's a problem on [Docker side](https://github.com/moby/moby/issues/2259).
> Fixed adding the verdaccio user into the group

- Dockerfile
**Type:** bug
Due this announce Node version in docker image must be updated 
https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/
> build: update node version due security update announcement

- src/webui/src/components/Help/index.js
Uses light version of react syntax highlighter to remove 820kb from bundle size for client 
before:
after:
> use light version of syntax highlighter

- wiki/reverse-proxy.md
**Type:** docs
*  Addition to the reverse proxy wiki
The web ui code relies on [src/lib/utils.js#L319](https://github.com/verdaccio/verdaccio/blob/master/src/lib/utils.js#L319) to figure out the correct protocol for serving the assets (js, css, etc). Since it relies on the "X-Forwarded-Proto" header, I have updated the documentation to reflect this. Without this header, you get a mixed-content page when you are on https as the assets end up being served over http.
> Adding X-Forwarded-Proto header to docs

- wiki/reverse-proxy.md
Hi.
I had issues regarding to resources when accessing Verdaccio through Apache proxy.
I found out that removing ending slashes at `ProxyPass` and `ProxyPassReverse` settings solved it.
I also set Verdaccio's config `url_prefix` to match the proxy location.
Hope it helps.
**Type:** bug / documentation
> Amend proxy instructions for Apache

- src/lib/storage/up-storage.js
**Type:** bug
Issues #285 #289 seems to be affected by the use of.
`Accept: application/vnd.npm.install-v1+json; q=1.0`
Also makes fails the `npm search` command
Resolves #285
> fix: Remove accept header that seems cause issues #285 #289 

- src/lib/storage/up-storage.js
**Type:** bug
A semicolon is required after media type in accept header when quality specification is made. Necessary for more pedantic servers such as JFrog's Artifactory.
Resolves #294
> Correct accept header set for registry requests.

- wiki/ssl.md
Hi,
*  improve documentation for the SSL part
I had some troubles setting up SSL for my Verdaccio registry because document was not perfectly clear.
I made little improvements on the SSL wiki page by adding a section about Docker (`listen` config entry is ignored because it's already set on Dockerfile), and I also added a link to the Node documentation pointing at more documentation for the `ca`, `cert` and `key` options for the `https` entry on the configuration.
Hope it can help other people!
> Update SSL documentation

- src/lib/auth.js
**Type:** bug
When using some authentication plugins other than htpasswd (we're using [sinopia-github-oauth](https://github.com/soundtrackyourbrand/sinopia-github-oauth)) user gets `403` if package publish/access config is setup to use username. I.e.:
packages:
'**':
access: $authenticated
publish: aszmyd
Is not working as authentication is checking this `publish` field against user groups only. But because my user object looks like this:
{ 
name: 'aszmyd',
groups: [ 'org', '$all', '$authenticated', '@all', '@authenticated', 'all' ],
real_groups: [ 'org' ] 
}
And the current check fails. 
My PR is fixing this by changing the way authentication checks `publish`/`access` configurations - now it checks also against `user.name` and not just `user.groups`
> Fix auth process to check against username also and not just groups

- README.md
- package.json
- src/lib/storage/local/local-data.js
- src/lib/storage/local/local-storage.js
- test/unit/local-data.spec.js
- test/unit/partials/storage/verdaccio-corrupted.db.json
- test/unit/partials/storage/verdaccio.db.json
- wiki/cli.md
- yarn.lock
Author: @Meeeeow 
Follow up of #300
- Throw error when the error code is not ENOENT during reading package database file to prevent possible data loss
- Add warning about PM2 cluster mode to docs
- **new**: Add unit test for locking feature
**Result**
If for any reason the database is corrupted, the user will see that message. It won't be able to publish packages.
```bash
➜ npm publish                                 
npm ERR! publish Failed PUT 422
npm ERR! code E422
npm ERR! Verdaccio database is locked, please contact your administrator to checkout logs during verdaccio startup. : npm-test-hello-world
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2017-08-25T18_24_48_546Z-debug.log
````
Resolves #??? ==> …
> Fix possible data loss upstream

- src/lib/storage/local/local-storage.js
- test/functional/tags/preserve_tags.spec.js
modified:   src/lib/storage/local/local-storage.js
modified:   test/functional/tags/preserve_tags.spec.js
**Type:** bug
This fixes the issue: ```npm search``` result doesn't contain DATE and VERSION information
Without this fix: ```npm search``` result's DATE and VERSION column is empty.  
With this fix: DATE column has the DATE that modified. VERSION column has the latest version.
> fix: Add DATE and VERSION in search result

- wiki/docker.md
**Type:** typo
Typo in Docker Documentation
> docs: fixed Typo

- src/lib/storage.js
**Type:** bug
* Fix verdaccio request package metadata(package.info) in every request even it's not expired
Resolves #119
> fix: :bug: Package metadata cache does not work

- src/api/web/api.js
**Type:** bug
Fixes bug when accessing Verdaccio throught web browser it show loading and no published packages are shown. This is caused because Verdaccio have published more than 500 packages and call stack size is exceeded.
> Fixed bug with Maximum call stack size exceeded on packages web API.

- wiki/config.md
**Type:** bug
Just fix typo at wiki
> Fix typo at config wiki (uplinks section)

- Dockerfile
**Type:** bug
Docker build fails with Yarn `1.x` breaks the build. This PR set `v0.28.4` as fixed version
> fix: fix docker build failure due breaking changes in yarn

- src/api/endpoint/api/dist-tags.js
- test/functional/tags/tags.js
**Type:** improvement
Resolves #288 
I have removed set() method endpoint. 
https://github.com/npm/npm-registry-client/blob/c03a77aba3e86e191b4025e34da47afb452c684a/lib/dist-tags/set.js#L33
> Removes dist-tag put and delete endpoint

- circle.yml
- scripts/publish.sh
To avoid future incidents, we will deploy automatically from `circleci` after push a new `git tag`
Resolves #367
> build: allow publish from continous integration tool

- src/lib/cli.js
**Description - Also described at #372:**
This is a default behavior of the operation system, after the process has quit it's sockets will remain on disk.
The solution is to just remove the file before trying to use it again, preventing any **EADDRINUSE** error
Resolves #372
> Unlink socket before listening

- wiki/ssl.md
**Description:** Fixed a typo in wiki/ssl.md
> Fix typo in wiki/ssl.md

- src/lib/cli.js
**Type:** Bug
Hello,
I want to apologize, but while fixing a bug on #373, i've managed to create another bug.
Removing the socket before a `listen` call will prevent `EADDRINUSE`, but blindly removing that file will throw an `EADDRINUSE ` error if the file does not exists.
This definitely fix errors while using unix sockets.
My sincere apologies.
Lucius.
> fix: Check if socket exists before removing

- wiki/notifications.md
**Type:** 
documentation
Just saw this while reading your docs:
1. It would be nice to have the default value for optional parameters (but I don't know what the values are and will leave it up to the maintainers to update them in this file).
2. Also fixes a small typo.
Keep up the great work !
> Add default column and fix typo

- Dockerfile
Type: bug
The following has been addressed in the PR: Sockets doesn't timeout before download is complete
Description: Socket timeouts on connections
This is a known nodejs issue which has been fixed on node 8.9.0
https://github.com/nodejs/node/pull/15791/commits
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.9.0
Anyone not running in docker should upgrade to node 8.9.0
Resolves #301
> upgrade node to fix long standing socket timeout issue

- systemd/verdaccio.service
**Type:** improvement
* The problem discussed in issue #396
> Using the env path in the systemd service

- README.md
- circle.yml
- package.json
- wiki/install.md
**Type:** feature 
Node 4 LTS support ends on April 2018, Verdaccio `3.x` won't support officially anymore less than Node6.
This PR also add Node9 support on circleci.
> Feature remove node4 support

- src/lib/cli.js
**Type:** feature 
just an initiative...
I'm using verdaccio to evaluate CI tools and publish tools.
I'm running few instances to mimic different registries of different scopes.
I found that the config supports `config.web.title` - which is propagated to the web-ui.
I decided to propose to match the `process.title` with `config.web.title` so I can track which of the instances was hit as part of the processes
> Match shell title with web title

- src/webui/src/components/PackageSidebar/index.jsx
- src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx
**Type:** bug
Package components loading before API call resolves.
It fixes the following thing:
- author function returns `undefined` on the first load. I found this writing test cases.
https://github.com/verdaccio/verdaccio/blob/704253a08d5db5209baabffb92caf7d88d2183e3/src/webui/src/components/PackageSidebar/modules/Maintainers/index.jsx#L21
- removes loading statement.
https://github.com/verdaccio/verdaccio/blob/704253a08d5db5209baabffb92caf7d88d2183e3/src/webui/src/components/PackageSidebar/modules/LastSync/index.jsx#L13
> packageInfo : child components' methods gives undefined in api call

- wiki/notifications.md
* `packagePatternFlags` config option for `notify:` wasn't documented, but is in the [full example config file](https://github.com/verdaccio/verdaccio/blob/master/conf/full.yaml)
* This ports the comment from that file to the relevant wiki doc
> Add packagePatternFlags to Notifications doc

- wiki/plugins.md
2 typos are fixed in `plugins.md`
> docs: Fix typos in plugins.md

- LICENSE
Issue #224 of missing license file.
I think it is crucial to have a license selection done.
If there is no license or uncertainty of it:
* It is not easy to use Verdaccio in commercial operations.
* It is not easy to contribute to Verdaccio.
I would like to see the license selection discussion and decision taking place sooner than later. Even to be taken into use before the milestone 3.0.0.
Resolves #224
> docs: Add MIT license file

- README.md
- circle.yml
- docs/node-api.md
- index.js
- package.json
- src/index.js
- src/lib/bootstrap.js
- src/lib/cli.js
- test/unit/basic_system.spec.js
- test/unit/cli.spec.js
- website/sidebars.json
Verdaccio can be invoqued programmatically.
```js
import startServer from 'verdaccio';	
startServer(configJsonFormat, 6000, store, '1.0.0', 'verdaccio',
(webServer, addrs, pkgName, pkgVersion) => {
webServer.listen(addr.port || addr.path, addr.host, () => {
console.log('verdaccio running');
});
});
```
> refactor: add node api to launch verdaccio programmatically

- .travis.yml
this is based on !470 and adds travis-ci using npm instead of yarn, so we can check npm and yarn with ci
> add travis as secon ci

- .travis.yml
- CONTRIBUTING.md
- package.json
- yarn.lock
This enforces the conventional commit guidelines described within [CONTRIBUTING.md](https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#git-commit-guidelines) as part of `npm run lint`.
**take care**, this would break the commits made via translation bot service, e.g. https://github.com/verdaccio/verdaccio/commit/3ea7f9a45fa6e64d8fa866996d328730c4fa3897
> chore(lint): use commitlint as part of lint

- src/webui/src/components/PackageDetail/packageDetail.scss
__Description:__
The package name shown on the top of the package detail page is probably the best and more natural way for copying and reusing (e.g. in a `npm install`). However the point is that it's capitalized makes its use less relevant.
Resolves https://github.com/verdaccio/verdaccio/issues/583
> Remove non-relevant capitalization on package name

- docs/ci.md
**Type:** CI Documentation
Circle CI will sunset it's 1.0 builds on 31 August 2018 in favour of the 2.0 builds
> docs: add link to  Circle CI 2.0 npm docs

- docs/docker.md
**Type: documentation**
*  This relates to issue #336
*  No tests are included as it is a trivial documentation change
May not resolve #336, but that issue culminates in a discussion around how the user ID should be 100 and the group ID should be 101. This is contrast to the documentation which says both the user ID and group ID should be 101, but this does not appear to work.
The documentation already makes clear that using bind mount is not the best approach (`docker volume` is) and this PR does not detract from that, but hopefully does make things easier for people who are not able to use `docker volumes` (e.g. people on docker versions <=1.8).
> docs: changed chown uid to 100 for docker

- src/lib/config.js
- src/lib/local-storage.js
- test/e2e/config/config-protected-e2e.yaml
- test/e2e/config/config-scoped-e2e.yaml
**Type:** bug
In situations when we use storage plugins, `storage` property is not mandatory to be added. 
```
....
auth:
htpasswd:
file: ./htpasswd
max_users: 100
store:
memory:
limit: 10
....
```
Resolves #673
> fix: allow do not include storage if uses a storage plugin

- src/lib/utils.js
**Type:** bug
The snippet removed does not have any impact and should be removed
Resolves #702
> fix: remove useless warning ignoring tag

- README.md
- conf/default.yaml
- conf/full.yaml
- package.json
- yarn.lock
This PR allow a built-in usage of `npm audit` command via verdaccio.
```
npm install --global verdaccio@beta    
npm install --global verdaccio-audit
```
To enable it you need to add this to your configuration file.
```
middlewares:
audit:
enabled: true
```
```
➜ verdaccio
warn --- config file  - /Users/user/.config/verdaccio/config.yaml
warn --- Plugin successfully loaded: htpasswd
warn --- Plugin successfully loaded: audit
```
Note: **It's gonna be built-in in next beta but  disabled by default.**
Resolves #689 
Project: https://github.com/verdaccio/verdaccio-audit
track clients issues here: 
* yarn (https://github.com/yarnpkg/yarn/issues/5808)
* pnpm (https://github.com/pnpm/pnpm/issues/1153)
> feat: support for npm audit fix #689

- docs/notifications.md
Being a user of Google Hangouts Chat, I would have be happy to find an example of configuration.
Message format reference : https://developers.google.com/hangouts/chat/reference/message-formats/
This is what the notification looks like:
This also fixes the multi-notification example by adding missing `:`
> docs: Add a notification example for Google Hangouts Chat

- docs/auth.md
**Type:**
documentation
Fix reference to htpasswd plugin in auth docs.
> fix reference to htpasswd plugin in auth docs

- docs/auth.md
- docs/plugins.md
**Type:**
documentation
Fix spelling of authentication in plugins doc
> Fix spelling of authentication in plugins doc

- docs/plugins.md
**Type:** docs
Add *verdacio-profile-api* plugin reference
*  npm profile commands giving 404 error #392
*  No tests are included as it is a trivial documentation change
Referred plugin implements backend API for *npm profile* cli commands, including possibility to change password for *verdaccio-htpasswd* authentification
> docs: add verdaccio-profile-api plugin reference

- docs/windows.md
I believe the path here is wrong. When I install verdaccio with NPM, that `src` folder does not exist. However, there is a `build` folder with a `cli.js`. When I changed `src` to `build` on my machine, the instructions here worked.
> Fix path to cli.js in Windows NSSM documentation

- src/webui/utils/api.js
**Type: fix**
*  Send cookies when using fetch
Previously, when __XMLHttpRequest__ was used, cookies were sent when getting _/-/verdaccio/logo_ and _/-/verdaccio/packages_
After switching to __fetch__ in sha fef7ee75e8a02dc3a6017b70dcb62dabf9183e0f cookies are no longer sent.
This commit configures fetch in the webui to send cookies to the same domain.
> The "same-origin" value makes fetch behave similarly to
> XMLHttpRequest with regards to cookies.
> https://github.com/github/fetch#sending-cookies
**Why cookies?**
I have a proxy in front of Verdaccio that handles authentication (using redirection to Azure AD). It sets a cookie at the end of authentication process. In versions prior to `3.0.0-beta.5` this worked well, but with …
> fix: configure fetch to send cookies

- .circleci/config.yml
The following has been addressed in the PR: 
*  There is a related issue? Part of #612 
*  This PR does not include Unit or Functional tests
This PR is a fix over https://github.com/verdaccio/verdaccio/pull/738 and https://github.com/verdaccio/verdaccio/pull/747. With this fix, we can trigger CircleCI execution on tag push events correctly. For more details on the solution, look at  https://github.com/verdaccio/verdaccio/issues/612#issuecomment-396517868
> chore(ci): fix publish step execution

- docs/notifications.md
- src/webui/src/components/PackageSidebar/index.jsx
- src/webui/src/components/PackageSidebar/modules/Infos/index.jsx
- src/webui/src/components/PackageSidebar/modules/Infos/style.scss
- test/webui/components/PackageSidebar/__snapshots__/infos.spec.js.snap
- test/webui/components/PackageSidebar/infos.spec.js
It's my very first time working with this kind of front end stack. From webpack to react, so I hope I didn't write too terrible code.
I've added a new module to the sidebar that shows a link to the package homepage, repository and license if available in the meta data.
It's a very basic implementation that probably doesn't catch a lot of the edge cases (especially in regards of the repository url), but maybe a starting point?
**Type:**
> feat: Add basic package infos and resource links to sidebar.

- tools/webpack.config.js
Pull request for issue 753.
https://github.com/verdaccio/verdaccio/issues/753
This will add the "ToReplaceByVerdaccio" back into the  /verdaccio/static/index.html on build.
proxy replacements are done bij the nodejs backend. see /verdaccio/src/api/web/index.js line 45
Screen shot of the 404 errors when using reverse proxy at this time.
> fix: replace static endpoint in case of reverse proxy

- tools/getPackageJson.js
- tools/getPackageVersion.js
- tools/webpack.dev.config.babel.js
- tools/webpack.prod.config.babel.js
**Type:** good first issue
**Description:**  Added webpack banner plugin to tag bundles with current version for web ui production build (yarn run build:webui).
e.g. 
```javascript
/*!
* 
*     Name: 1
*     Generated on: 1529912145630
*     Package: verdaccio
*     Version: v3.2.0
*     License: MIT
*     
*/
```  
Resolves #784
> fix: adds webpack banner plugin to tag bundles with version (#784)

- .circleci/config.yml
*  There is a related issue? Part of #612 
*  This PR does not include Unit or Functional tests
**Description:** In this PR, we improve the workflow by executing `publish_gh_pages` step only on release. Also, renamed `ignore_branches` constant to `ignore_not_dev_branches` to be more expressive.
As `publish_gh_pages` will not execute every time, we should unset the check on this step (as we did with release step).
> chore(ci): improve the workflow publishing doc only when releasing

- .circleci/config.yml
*  There is a related issue? Part of #612
*  This PR does not include Unit or Functional tests
**Description:** There was a problem when we chaining the execution of tests and functional tests, duplicating `command` in a single `run`. With this, CircleCI takes the last `command` found as the command to perform, ignoring any other before. That is because YAML treat them as object keys (Js simile) and override every occurence before.
The syntax to chain several commands is:
```yaml
- run:
name: 'Name of the step'
command: |
echo 'first command'
echo 'second command'
echo 'Nth command' 
```
> chore(ci): fix test and functional test execution in same command

- docs/plugins.md
You can use `sinopia-github-oauth` with verdaccio but it throws an error because of missing `Auth.prototype.aes_encrypt` in verdaccio which exists in sinopia. So I published fixed version [verdaccio-github-oauth](https://www.npmjs.com/package/verdaccio-github-oauth). I already applied this to company's private verdaccio repository @aroundus-inc and working well.
- Error log
```plain
fatal--- uncaught exception, please report this
TypeError: auth.aes_encrypt is not a function
at IncomingMessage.<anonymous> (/usr/local/app/node_modules/sinopia-github-oauth/index.js:143:30)
at IncomingMessage.emit (events.js:187:15)
at …
```
> add verdaccio-github-oauth

- src/webui/src/components/Header/index.js
**Type:**
In some places in our code base, I found that we are using componentWillMount for API calls and setting the state. It is better to stop using this because it is an anti-pattern. It will be deprecated in newer react versions.
For api calls use use componentDidMount
Current Issue : facebook/react#7671 (comment)
React docs also states that to use class constructor for initialization.
Docs: https://reactjs.org/docs/react-component.html#unsafe_componentwillmount
- Replace `componentWillMount` with `componentDidMount`
> refactor: replaces componentWillMount with componentDidMount

- docs/config.md
Fixes a few typos (and one bad example) in the config page in the docs.
> docs: fix typos

- src/lib/auth.js
As `_.isFunction[method]` returns always `undefined` the following condition is never fulfilled:
```
if (_.isFunction[method] === false) {
```
This leads to errors like
```
TypeError: plugin[method] is not a function
```
it should be like this imho
```
if (_.isFunction(plugin[method]) === false) {
```
**Type:**
Resolves #849 https://github.com/Alexandre-io/verdaccio-ldap/issues/43
> fix: Authentication Plugins / plugin[method] is not a function (add_user method)

- src/lib/local-storage.js
Unpublishing a specific module version does not remove that version from the local-storage (package.json) "time" object.
This results in the version still being shown in the webui right-pane "Last Sync".
Added delete of the time[ver] object when module version is removed.
> fix: unpublish version does not remove it from timeline

- Dockerfile
installs full-fledged wget in alpine, so that it honors proxy
environment variables
**Type: build**
*  Unit or Functional tests are included in the PR: Same as existing
When building docker behind a corporate proxy, and having proxy environment variables setup, the build cannot be completed because the wget version included in busybox does not honor the envvars. This PR adds the full-fledged wget command that does use the variables when downloading.
This will apply when e.g. a config like this is applied in `.docker/config.json`:
```
"proxies":
{
"default":
{
"httpProxy": "...",
"httpsProxy": "...",
"noProxy": "..."
}
}
```
> chore: fix docker build behind a corporate proxy

- docs/packages.md
make explicit the syntax used in the package configuration directives by
linking to the minimatch npm package used for the implementation
**Type:** docs
No
Unneeded
See commit message
> docs: document package regex syntax

- Dockerfile
The URL used for the sgerrand.rsa.pub pubkey is returning a 404.  Updated to new URL.
See related: https://gitlab.com/gitlab-org/gitlab-ci-yml/merge_requests/185/diffs
> Update glibc package signing key URL

- docs/plugins.md
**Type:**
The following has been addressed in the PR: typo/grammar in docs
*  There is a related issue? no
*  Unit or Functional tests are included in the PR? n/a
The sentence wasn't proper grammar (and still isn't quite, but it's definitely closer) and also had a couple typos in it (double 'the', becames, etc.).
> docs: fix typo/grammar

- .vscode/launch.json
- .vscode/tasks.json
- package.json
- test/functional/lib/environment.js
It updates `launch.json` to provide built-in settings to help contributors to run `verdaccio` in dev mode.
There are 4 launchers
* CLI Babel Registry: runs the registry to compiles on the fly 
* Unit Test: Run unit testing with Jest in debug mode
* Unit Test: Run functional testing with Jest in debug mode
* Verdaccio compiled: transpile code and debug over the compiled code
> chore: improve vscode debugging

- src/lib/config-utils.js
- test/unit/api/config-utils.spec.js
**Type:** bug
*  There is a related issue? yes
*  Unit or Functional tests are included in the PR ye
Wrong migration on refactoring was causing this.
Resolves #981 
⚠️ I'd like to ship this ASAP
> fix: missing properties for default matcher #981

- package.json
- src/api/web/index.js
- src/lib/cli.js
To avoid mistake on usage, we stop execution whether Node.js is less as defined in the package.
For testing
```
nvm install 6.8.0
```
run
```
➜ verdaccio
Verdaccio requires at least Node.js 6.9.0 or higher, please upgrade your Node.js distribution
```
* It redoes `vscode` launch debugging configuration
* add `"verror": "1.10.0"`
* `"lint-staged"` was as `dependency` ⚠️, now is a  `devDependency`
> feat: check for minimum node.js version on start

- src/lib/logger.js
**Type:**
feature
nothing.
I found that it would be ignore local timezone when set `pretty-timestamped`. Default use `Date().toISOString()`. Always i print the error time string in my log files.
I create a function to resolve it. Now it has the crollectly time string show.
> fix: support localTimeZone for logger `pretty-timestamped` format

- package.json
- src/lib/local-storage.js
- src/lib/storage-utils.js
- src/lib/utils.js
- test/unit/api/utils.spec.js
- yarn.lock
**Type:** bug
Contributors field can be `string`, or `array`. But, sadly `npm` does not do a healthy check on the client side and whatever goes to the registry.  This normalizes the field.
If the field is already corrupted on storage, it just normalizes on the fly.
https://docs.npmjs.com/files/package.json#people-fields-author-contributors
Resolves #1022
> fix: normalize contributors field #1022

- conf/docker.yaml
**Type:** fix
The URL given in the docker.yaml file points to a non-existent URL. I updated the link to point to the official docs page/section.
> Fix top link url in example docker.yaml

- docs/plugins.md
**Type:** Documentation
I stumbled across this auth plugin and tested it in my setup.
Adding to the list as suggested here:
https://github.com/bufferoverflow/verdaccio-gitlab/issues/4#issuecomment-425664401
> Add verdaccio-gitlab-ci to authorization plugins

- docs/plugins.md
- test/functional/tags/tags.js
**Type:**
remove all import assert from 'assert'; in favor of Jest matchers in testing in tags.js
> refactor: Awshanks/assertfixes

- test/unit/api/config-utils.spec.js
- test/unit/partials/config/yaml/pkgs-basic-no-access.yaml
- test/unit/partials/config/yaml/pkgs-basic-no-proxy.yaml
- test/unit/partials/config/yaml/pkgs-basic-no-publish.yaml
It provides unit test scenarios where the configuration will normalize those props are missing as empty arrays.
In cases where `proxy`, `publish` or `access` props are missing. Eg:
```
packages:
'@*/*':
access: $all
'foo':
'**':
access: $all
publish: $all
```
The output wil be
```
packages:
'@*/*':
access: $all
publish:
proxy:
'foo':
access: 
publish:
proxy:
'**':
access: $all
publish: $all
proxy:
```
This unit test will confirm that we can remove the `?` for `allow_access`, `allow_proxy`, `allow_publish`,  `proxy`, `publish` or `access` on https://github.com/verdaccio/flow-types/blob/master/src/types.js#L167 types where those values are not optional, actually will exist in any case.
> test: add scenarios where publish or access are missing

- src/lib/bootstrap.js
* Fixes #1061 
pfx config is now handled correctly and the process does not exits.
> Don't exit if using https and pfx is enabled (#1061)

- .circleci/config.yml
**Type:** ci
The following has been addressed in the PR: Fix CircleCI to allow execution in PRs correctly
*  Unit or Functional tests are included in the PR: No
**Description:**  We need to use CircleCI workspaces to share data in the workflow among steps and not use cache for that:
- The **cache** is used to share data between workflow executions, e.g, the workflow execution of this PR is not the same as latest master execution or another PR execution. Some good things to put in cache are packages installed (`node_modules`) or config files like `.npmrc`, as they won't change in short time.
- The **workspace** is used to share data between steps, for example, step prepare will make the installation of packages and build some part of the project, that later …
> ci: use CircleCI workspaces to share data among steps

- src/lib/bootstrap.js
Why we specified `secureProtocol: 'SSLv23_method'` here?
The comment after the code said `"disable insecure SSLv2 and SSLv3"`, but that was what the code next line do: `secureOptions: constants.SSL_OP_NO_SSLv2 | constants.SSL_OP_NO_SSLv3,`.
The default value of `secureProtocol` is [`SSLv23_method` in Node.JS 8 LTS](https://nodejs.org/docs/latest-v8.x/api/tls.html#tls_tls_createsecurecontext_options), but [none and use minVersion in Node.JS 10 LTS](https://nodejs.org/docs/latest-v10.x/api/tls.html#tls_tls_createsecurecontext_options).
`SSLv23_method` was in the OpenSSL manual version 1.0.2, but removed in the version 1.1.0. So it may not works in Node.JS 10.
I think we should remove this line to use the default value of Node.JS.
> fix: remove useless secureProtocol option

- package.json
- src/api/web/api.js
- src/api/web/endpoint/package.js
- src/lib/config-utils.js
- src/lib/utils.js
- src/utils/user.js
- test/flow/plugins/auth/example.auth.plugin.js
- test/unit/api/utils.spec.js
- yarn.lock
**Type:** feat
In order to be fully offline, we allow disabling gravatar support for UI. The fallback support is a bundle in generic user face SVG based on base64.
The new configuration would look like this. **gravatar** by default remains **enabled**.
```
web:
title: Verdaccio
gravatar: false
```
Resolves #1172
> feat: allow disable gravatar #1172

- src/lib/up-storage.js
**Type:**
bug
`processBody` does not use any parameters so there should be none in any invocation.
> Remove unused parameters from processBody method invocation

- conf/default.yaml
- conf/full.yaml
- src/lib/bootstrap.js
Set default timeout to 60 seconds (it's workaround for issue reported in #301).
> feature: introduce server keepAliveTimeout into config files

- src/lib/auth.js
**Type:**
This PR is to at least generate a discussion about the possibility of making the `apiJWTmiddleware` auth overwriteable by Auth plugins. The logic behind why I'd find is useful is I can then tie directly into my token based authentication system and disable login/adduser from the npm registry itself. In my case when users signup & login on our existing system we'll put our token in the `.npmrc` then use that token in our plugin `apiJWTmiddleware` function to validate & create the user appropriately or return an error. 
> Feat auth jwt plugin

- package.json
- src/api/endpoint/api/publish.js
- src/api/endpoint/api/star.js
- src/lib/constants.js
- src/lib/local-storage.js
- src/lib/storage-utils.js
- test/unit/api/__snapshots__/api.publish.spec.js.snap
- test/unit/api/api.publish.spec.js
- test/unit/api/api.spec.js
- test/unit/partials/star-api.js
- yarn.lock
**Type: feature**
* Unit tests are included in the PR
Starring is still unsupported in current version.
This pr will support the star and unstar function by adding star handler in publish.js
**Remarks:**
users field need to be added in @verdaccio/types
```flow
declare type verdaccio$Package = {
_id?: string;
name: string;
versions: verdaccio$Versions;
'dist-tags': verdaccio$GenericBody;
time?: verdaccio$GenericBody;
readme?: string;
users?: verdaccio$GenericBody;
_distfiles: verdaccio$DistFiles;
_attachments: verdaccio$AttachMents;
_uplinks: verdaccio$UpLinks;
_rev: string;
}
```
Already changed base on the previous code review
previous pr: https://github.com/verdaccio/verdaccio/pull/1247
> feat: add star and unstar api for 4.x

- conf/default.yaml
- conf/docker.yaml
**Type:** docs
*  Removes an outdated comment in the `default.yml` and `docker.yml` config files
`audit` has been enabled by default since https://github.com/verdaccio/verdaccio/commit/8df186c5d52d19de9a895ca3c254f1e345f1a9b2.
> docs: remove outdated comment

- src/api/endpoint/api/package.js
Add a new endpoint to allow download scoped tarballs according to the distribution metatada.
```
https://registry.npmjs.org/@verdaccio/streams/-/@verdaccio/streams_2.0.0-beta.0.tgz
```
Resolves #1257
> fix: add new enpoind that allow download tarballs according the standard

- src/api/web/index.js
- src/lib/utils.js
- test/unit/api/utils.spec.js
**Type:** bug
**Description:** As [document](https://verdaccio.org/docs/en/webui) says that the logo field in configuration can be a URI with http(s) scheme, but it is more useful the logo field can specify a local file. Besides, also the example in the document seems like using a local file path.
> fix: logo field in configuration cannot use the local file

- package.json
**Type:**
*  CI release script fails due to missing `octokit/rest` package. This PR adds it.
> Add missing octokit/rest package for the trigger-release script

- package.json
- src/api/web/index.js
- yarn.lock
**Type:** bug
*  There is a related issue? yes
*  Unit or Functional tests are included in the PR no
The bug is well described here  #1297 .
This PR aims to update the `url_prefix` prop that is usually being used when Verdaccio uses under reverse proxy. The documentation suggests using a full URL, which I think is no the best approach, not good for maintenance if the domain changes also configuration file must be updated.  This PR will assume the `url_prefix` is not a URL anymore. 
Here a full repo that proves the new configuration works fine under the NGINX set up
https://github.com/verdaccio/docker-examples/tree/master/reverse_proxy/nginx
```yaml
url_prefix: /verdaccio/
```
Depends on
Resolves #1297
Resolves …
> fix: routing is aware of reverse proxy directory #1297

- package.json
- src/api/index.js
- src/lib/storage.js
- test/unit/api/api.spec.js
- test/unit/partials/mock-store/npm_test/package.json
- test/unit/partials/plugin/filter.js
**Type:**
*  There is a related issue? #818
*  Unit or Functional tests are included in the PR: Not yet, WIP
**Description:** Add a plugin that can filter all packages before being returned. This
enables blocking at the verdaccio level.
The general idea here is that we can have filters that do any type of thing we want. We can have whitelist or blacklist, temporal, keyword,  CVE-based etc. This WIP includes a blacklist filter which allows for one to update it and instantly block packages. This is useful if you want to block something before npm does and stops clients from being able to download it
The riskiest part of this change is what to do with changing `dist-tags`. Any downgrade could be a breaking change, but we need to guess something. …
> Filter packages

- src/lib/cli.js
**Type:** fix
**Description:** warning text is hard to read when running under root.
Using the white text on a yellow background is not a good idea.
I change it to use the red text.
**Discuss:**
Should we exit immediately when detect running under root? and if the user needs to run it under root, we support an argument such as `--unsafe-allow-root` to allow running under root.
> fix: warning text is hard to read when running under root

- src/lib/up-storage.js
**Type:**
bug
*  The `property` check was checking for a boolean but the typings expect a string.
See https://github.com/verdaccio/verdaccio/blob/5a8d92f5f93c16f505f51dddecd1c2d520771971/src/lib/up-storage.js#L53
> fix: correctly check if the proxy setting evaluates to false

- src/lib/bootstrap.js
- test/unit/api/cli.spec.js
- test/unit/partials/config/yaml/server/keepalivetimeout-0.yaml
- test/unit/partials/config/yaml/server/keepalivetimeout-60.yaml
- test/unit/partials/config/yaml/server/keepalivetimeout-undefined.yaml
**Type:**
bug
*  #1352
This correctly checks the `keepAliveTimeout`.
It is either not in the config at all (= undefined) or not set (= null) or set (0 or greater = number / string).
> fix: correctly check the keepAliveTimeout value, fixes #1352

- package.json
- src/lib/cli.js
- yarn.lock
**Type:**
feature
Included a new option which shows up the local environment information, useful while submitting bug reports.
Fixes #1364 
`verdaccio --info`
```bash
Environment Info:
warn --- config file  - /home/james-the-hacker/.config/verdaccio/config.yaml
warn --- Plugin successfully loaded: verdaccio-htpasswd
warn --- Plugin successfully loaded: verdaccio-audit
warn --- http address - http://localhost:4873/ - verdaccio/4.0.4
System:
OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
CPU: (2) x64 Intel(R) Pentium(R) CPU G2020 @ 2.90GHz
Binaries:
Node: 8.11.4 - /usr/bin/node
Yarn: 1.13.0 - /usr/local/bin/yarn
npm: 6.9.2 - /usr/local/bin/npm
Browsers:
Chrome: 72.0.3626.81
Firefox: 65.0
npmGlobalPackages:
verdaccio: 4.0.4
```
> feat(chore): Included provision to show up local environment information

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/issue_template.md
`v4.1.0` features an `--info` option with which the user can get information regarding his local environment.
Hence, it makes sense to update the issue template(s) prompting the user to paste the results as received.
> chore: update issue templates

- .secrets-baseline
- package.json
- yarn.lock
**Type:**
Feature
Adds support through [`detect-secrets`](https://github.com/Yelp/detect-secrets) which wraps Yelp's generic detect-secrets tool, to test for secrets being committed to source control using the pre-commit framework the project already has, and as a result prevent secrets like passwords, tokens and others to leak into source control.
The `detect-secrets` npm package will try different methods of invoking the `detect-secrets-hook` tool to run the secrets test for each file, and if it isn't able to find it will silently fail to not interrupt developer workflow. In a future re-visit of this capability we can update this to be a breaking …
> feat: prevent secrets from leaking to source control

- src/lib/utils.ts
- test/unit/modules/utils/utils.spec.ts
**Description**
In sinopia https://github.com/rlidwka/sinopia/commit/9f662a69e19a15dd90f568fc3a3ebf65b33cbd80#diff-50e3aa130a4f97a42ee2cf111c7b1d9d a validation name a package that start with dashes eg:(`@scope/-my-pkg`) was added with the argument that pattern is reserved by *couchdb*, but, npmjs clearly allows that pattern now. I guess this is not a restriction anymore.
fix: https://github.com/verdaccio/verdaccio/issues/1400
This PR remove such validation.
**Type:**
*  There is a related issue? yes
*  Unit or Functional tests are included in the PR yes
Resolves #1400
> fix: allows pkg names that starts with dash

- package.json
- yarn.lock
- context: https://github.com/verdaccio/verdaccio-audit/pull/12
- related https://github.com/verdaccio/verdaccio/issues/1293
Co-Authored-By: Danny Frencham <dfrencham@users.noreply.github.com>
It adds new property to audit middleware.
```
middlewares:
audit:
enabled: true
strict_ssl: true # optional, defaults to true
```
Helps with #1293
cc: powered by @dfrencham
> feat: add new prop to audit middleware

- package.json
- yarn.lock
http-errors needs to be a prod dependency
as it is used in code.
https://github.com/verdaccio/verdaccio/blob/c1672f7e32658905caa8a5634602723b1b5246c1/src/lib/logger.ts#L9
**Type:**
> fix(deps): add missing prod dependency

- package.json
- yarn.lock
`@types/handlebars@4.1.0`: This is a stub types definition. handlebars provides its own type definitions, so you do not need this installed.
> fix(chore): remove stub type definition for handlebars

- src/lib/utils.js
- test/unit/api/utils.spec.js
Backport #1409 dash in package name fix from v4.2.0.
> V3: Backport #1409 dash in package name fix

- .secrets-baseline
- src/api/endpoint/api/publish.ts
- src/api/endpoint/api/star.ts
- src/api/middleware.ts
- src/lib/auth-utils.ts
- src/lib/auth.ts
- src/lib/constants.ts
- src/lib/local-storage.ts
- src/lib/storage-utils.ts
- src/lib/utils.ts
- test/unit/__helper/api.ts
- test/unit/__helper/expects.ts
- test/unit/__helper/utils.ts
- test/unit/modules/api/__snapshots__/publish.spec.ts.snap
- test/unit/modules/api/api.spec.ts
- test/unit/modules/api/publish.spec.ts
- test/unit/modules/auth/jwt.spec.ts
- test/unit/modules/cli/cli.spec.ts
- test/unit/partials/config/yaml/api.spec.yaml
- test/unit/partials/star-api.js
- types/index.ts
- yarn.lock
**Type:** bug
*  There is a related issue? yes
*  Unit or Functional tests are included in the PR yes
The issue was the npm star use a similar payload, but we did not check properly the shape of the payload, this fix and allow unpublish correctly.
Improve unit testing for publishing and unpublishing
Add new code documentation for future changes.
Resolves #1359
> fix: unpublish and add or remove star colision

- src/api/endpoint/api/user.ts
This is a fix for this: https://github.com/verdaccio/verdaccio/issues/1426
Root cause is that the `auth.authenticate()` method calls back with the arguments `(err, user)` but the method to add a user is expecting `(err, groups)`.
I'd like to also add tests to this PR but i'm not sure the best way to go about it. I didn't see an interface for this kind of callback in the monorepo or flow-types. Is there a preferred method to approach this kind of issue?
Resolves #1426
> fix: fixed user creation endpoint to properly import groups

- contrib/aws/cloudformation-ec2-efs.yaml
**bug**
*  There is a related issue? : no
*  Unit or Functional tests are included in the PR: no
cloud formation template launch successfully on initial ec2/efs sets, but could not recover after 2nd launch.
cloud-init error message indicate mkdir failed.
```shell
$ sudo cat /var/log/cloud-init-output.log
mkdir: cannot create directory '/verdaccio/conf': File exists
```
This PR address cloud formation template to be used for auto scaling environment.
> fix: mkdir failed and ec2 infinitely re-launch

- README.md
**Type:**
documentation
Add snippet to README showing a way to use `verdaccio` without `npm config set registry`
None known
No
`npm config set registry` changes the registry for all `npm` commands until it is unset. This can lead to `http://localhost:4873` being written to `package-lock.json` and `yarn.lock` files unexpectedly. An alternative is provided to run a single command with the registry provided by `verdaccio`.
> Show usage without setting registry globally

- package.json
- src/api/web/endpoint/package.ts
- src/lib/utils.ts
- test/unit/modules/web/api.web.spec.ts
- yarn.lock
* You can browse and click on each version to display detail for such version
* Allows to to browse and download older versions
* Add label of which version is being displayed
* ⚠️ README always point to the latest one (Verdaccio does not save all readme)
Resolves https://github.com/verdaccio/ui/issues/109
> feat: browse web package version

- package.json
- yarn.lock
*  There is a related issue? Not directly, but it is the same described in #1484, in this case, for 4.x version
**Description:** Rollback _express_ 4.18.0 to 4.17.1, introduced by _verdaccio-audit_ plugin
> chore(deps): update verdaccio-audit to fix express version

- conf/default.yaml
- conf/docker.yaml
- test/unit/modules/config/config.spec.ts
The experiment flag is enabled, it is not dangerous since the token is disabled by default, but is wrong. This PR comment it out.
```
warn --- config file  - /Users/user/.config/verdaccio/config.yaml
warn --- ⚠️  experiments are enabled, we recommend do not use experiments in production, comment out this section to disable it
warn ---  - support for token  is disabled
warn --- Verdaccio started
warn --- Plugin successfully loaded: verdaccio-htpasswd
warn --- Plugin successfully loaded: verdaccio-audit
warn --- http address - http://localhost:4873/ - verdaccio/4.3.1
```
> fix: comment out experiments from configuration files

- package.json
- yarn.lock
Fix Cross-site Scripting (XSS) in @verdaccio/readme
https://app.snyk.io/vuln/SNYK-JS-DOMPURIFY-474012
> fix: security vulnerability at readme in dompurify dep

- src/lib/cli.ts
**Type:**
bugfix
*  There is a related issue? NA
*  Unit or Functional tests are included in the PR NA
The `process.exit` code is `1` for the `--info` flag so it will give a nodejs error format at the end instead of silently exiting.
Changed it to `0`
> fix: changed the exit code for info flag

- .circleci/config.yml
- .github/workflows/ci.yml
- codecov.yml
Before check others PR I want to clarify how we are testing, I add Node 13 to be more explicit since the LTS are having a long maintenance https://nodejs.org/en/about/releases/ most likely we will have 4 versions running for a while.
Furthermore reorganize the steps, E2E goes to the end and then coverage. Also updates GitHub CI to use node 13.
E2E will be soon not more UI anymore, rather our own package being tested as we advise to (short future term).
> chore: build add node13

- src/api/middleware.ts
**Type:**
bugfix
*  Prevent issue with leading hyphen / dash in package names
It seems the handling and passing of routes and paths changed. Depending on where we are (-/ping or -/web/detail/kleur) we either geht `-` or `kleur`. If the package contains a leading hyphen / dash this did not work as it was handled as internal couchdb route (using the `charAt(0)` check).
Resolves #1429
> fix: prevent issue with leading hyphen in package name - fixes #1429

- src/lib/utils.ts
- test/unit/modules/utils/utils.spec.ts
**Type:** bug 
Added more unit test cases and fixed `combineBaseUrl` method.
`RegExp` was changed to `slice` for optimization.
> fix: updated combine url fix method

- package.json
- yarn.lock
Fixed at https://github.com/verdaccio/monorepo/pull/312
Co-Authored-By: Daniel Ruf <danielruf@users.noreply.github.com>
Resolves #1639
> fix(deps): bump @verdaccio/local-storage from 8.5.0 to 9.0.0

- package.json
- yarn.lock
**Type:** bug
fixes: https://github.com/verdaccio/verdaccio/issues/1648
Co-Authored-By: Daniel Ruf <danielruf@users.noreply.github.com>
Resolves #1648
> fix(deps): bump @verdaccio/ui-theme from 0.3.11 to 0.3.12 (#1657)

- src/utils/user.ts
**Type:**
refactor
This PR changes the markup from base64 to optimized (svgo) SVG string which is much smaller and less data.
> refactor: use optimized svg for generic gravatar

- src/api/endpoint/api/search.ts
- test/unit/modules/api/api.spec.ts
**Type:** fix
#1697 
Yes
This fix adds the _Content-Type: application/json_ header to responses for _GET /-/all_ requests.  
Unity recently made a change that requires this header to be included in responses for it's package manager to work correctly.  Other package manager clients could also add this restriction in the future.
> fix: adding Content-Type to response in GET /-/all (#1697)

- src/api/endpoint/api/v1/search.ts
- src/api/endpoint/index.ts
**Type:** Feature
*  #310 
Rudimentary implementation of the /-/v1/search endpoint, ignoring any result scoring and only filtering on words and author:xyz qualifiers.
To fully support the [spec](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#get-v1search) the filtering behaviour would need to be expanded.
> Add an incomplete implementation of the v1/search api

- packages/types/index.ts
- packages/utils/src/config-utils.ts
- packages/utils/src/utils.ts
- packages/utils/test/config-utils.spec.ts
**Type:** feat
**Verdaccio 5**
`allow_access`, `allow_publish` and `proxy_access` were supported as package access but this commit drop that support and ignore the properties
> feat: remove support for allow_ prefix

- .github/workflows/docker-publish-pre-check.yml
- .github/workflows/docker-publish.yml
**Type:** build
Updates GitHub action to publish the Docker file under `5.x`. This a first try 🙃 to use more GitHub Registry.
```
docker pull docker.pkg.github.com/verdaccio/verdaccio/verdaccio:5.x
```
https://github.com/verdaccio/verdaccio/packages/13531
> build: publish Docker image to GitHub registry (5.x)

- .babelrc
- conf/default.yaml
- package.json
- src/api/web/index.ts
- yarn.lock
**Type:** feat
* Add i18n on web https://github.com/verdaccio/ui/pull/432 @priscilawebdev 
* feat: spanish translations to UI  https://github.com/verdaccio/ui/pull/440 @juanpicado 
* feat(de-translations): added de-DE translations to the UI  https://github.com/verdaccio/ui/pull/441 @priscilawebdev and @jan-auer
* website docs  https://github.com/verdaccio/website/commit/e241821509bb5dc3308724732430645d15c1b71a
Available translations: `es-ES`, `us-US`, `pt-BR` and `de-DE`.
Thanks @priscilawebdev  for add i18n to the User Interface 👏 👏 👏 👏 
> 🙏  More translations are very welcome.
> feat:  i18n on web

- README.md
- conf/docker.yaml
- package.json
**Type:** fix
At v4.5.0 we shipped some security releases, one of them is JSDOM https://github.com/jsdom/jsdom/releases/tag/16.0.0 and only supports Node.js v10
[Node v8 is out of maintenance so we don't consider this a breaking change.](https://blog.risingstack.com/update-nodejs-8-end-of-life-no-support/)
⚠️  If you are using Node v8 and you have this issue, have on mind you can use only `verdaccio@4.4.4` or less if you cannot upgrade to Node v10.
```
➜ verdaccio
/Users/user/.nvm/versions/node/v8.17.0/lib/node_modules/verdaccio/node_modules/jsdom/lib/jsdom/living/helpers/dates-and-times.js:235
} catch {
^
SyntaxError: Unexpected token {
at …
```
> fix: update docs to support minimum node v10

- conf/default.yaml
- conf/docker.yaml
- package.json
- src/api/web/index.ts
- yarn.lock
**Type:** feat
* Dark mode by @priscilawebdev https://github.com/verdaccio/ui/pull/446
* Chinese UI Translation by @JackyChan https://github.com/verdaccio/ui/pull/448
In your `config.yaml`
* Add Dark mode UI
* Add `web` property for `darkMode`
```
web:
darkMode: true
```
> feat: add dark mode on and chinese translation for web

- src/api/web/index.ts
**Type:** bug
*  There is a related issue?  No
If the color is wrong, the UI crash
```
web:
primary_color: 'blue'
```
The hex color representation must be exact, otherwise, it returns to default. Material-UI only supports hex colors and RGB.
```
web:
primary_color: '#000'
```
> fix: incorrect primary_color crash the ui

- src/lib/logger.ts
fix #1709
**Type:**
*  There is a related issue? #1709
When using https://linux.die.net/man/8/logrotate and the **copytruncate** property is not provided, crash the app. Example of good configuration previous `v4.5.1`, after that the event `SIGUSR2` won't be triggered anymore.
Read more her https://github.com/trentm/node-bunyan#stream-type-rotating-file
```
/root/verdaccio-server.log {
daily
maxsize 100M
create
rotate 100
maxage 90
delaycompress
compress
copytruncate
notifempty
missingok
}
```
> fix: fatal exception and crash when logrotate signal event is called

- package.json
- yarn.lock
This restores support I removed in Verdaccio 4.5.0
This means nothing if you were not using Node v8, this support should be removed in a major release.
> feat: restore Node 8 support

- src/api/endpoint/index.ts
- src/api/index.ts
This can be useful when the middleware plugin has to get access to the request's body.
I tried to make publication and add some field "on the fly" and didn't get access to the request's body. ([link to my example plugin](https://github.com/hydra13/verdaccio-example-plugin))
The reason for this problem was that body-parser was used in `src/api/endpoint/index.ts` and middleware plugins registered before ones.
My PR just moves the call of body-parser from `src/api/endpoint/index.ts` to `src/api/index.ts` (above registration middleware plugins)
> Refactor: move BodyParser to upper level

- README.md
- src/api/endpoint/api/publish.ts
- src/lib/local-storage.ts
- src/lib/utils.ts
- test/unit/__helper/api.ts
- test/unit/__helper/utils.ts
- test/unit/modules/api/api.spec.ts
- test/unit/partials/config/yaml/api.spec.yaml
This is a successor of #1308, so this is highly referenced that PR but with some differences:
- treating deprecation as updating a package so it requires publish and unpublish access
- the way to distinguish a deprecate request: #1308 is done by an empty `_attachements` but this one is by checking if there is any `deprecated` key presented in any version(ref for the implementation of [npm cli](https://github.com/npm/cli/blob/latest/lib/deprecate.js#L63))
- fixed a comment related to starring a package
- fixed a small thing in `getPackage` for the testing utils
Please review, thanks!
> feat: npm deprecation support

- conf/default.yaml
- conf/docker.yaml
- src/api/endpoint/index.ts
the current one has not auth implemented, to avoid the lack of fallback to the original one now is required to be used it by default until the v1 is on shape production ready.
relates https://github.com/verdaccio/verdaccio/pull/1732
If you are using from `v4.5.0` to `v4.7.0` I recommend you update to this patch release. Always backward compatible. 
To force `v1` search endpoint just add the following in your config file.
```
experiments:
search: true
```
> fix: move search v1 endpoint as experimental

- .secrets-baseline
- src/api/endpoint/index.ts
- src/api/index.ts
This reverts commit 67c31b69 
The bug could not be fixed (here is more info) https://github.com/verdaccio/monorepo/pull/371  in order to restore the audit support we revert this.
We will try to find another solution to re-eanble #1841
closes: #1866
> fix: revert move bodyParse to the upper level (#1841)

- contrib/aws/cloudformation-ec2-efs.yaml
While trying to use the cloudformation template I noticed a small issue that can be avoided with the DNS configuration. The zone id for the alias target (the load balancer) should be taken from the load balancer, it's not a template parameter.
See relevant [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget-1.html#cfn-route53-aliastarget-hostedzoneid).
> Fix dns config in cloudformation template

- CONTRIBUTING.md
There were some spelling errors in the `CONTRIBUTING.md` file. Following updates were carried out on the file.
* updated table of content
* corrected spelling and grammar in a few places
* header levels
> fix typos in contributing guidelines

- Dockerfile
Upgrade Docker image to Node 14.15.0 as recommended LTS
https://nodejs.org/es/about/releases/
> feat: update docker base image to node v14.15.0

- src/api/middleware.ts
```
$ docker run -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio warn --- config file  - /verdaccio/conf/config.yaml
warn --- Verdaccio started
warn --- Plugin successfully loaded: verdaccio-htpasswd
warn --- Plugin successfully loaded: verdaccio-audit
warn --- http address - http://0.0.0.0:4873/ - verdaccio/4.9.1
http --> 200, req: 'GET https://registry.npmjs.org/execa' (streaming)
http --> 200, req: 'GET https://registry.npmjs.org/execa', bytes: 0/119164
http <-- 200, user: null(172.17.0.1), req: 'GET /execa', bytes: 0/27224
http <-- 200, user: null(172.17.0.1), req: 'GET /execa', bytes: 0/27224
```
> fix: doubled request logs in node.js >= 11

- conf/default.yaml
- conf/docker.yaml
Add by default the keep alive configuration for the newer installations.
Example: https://github.com/verdaccio/verdaccio/commit/cc5d78613386d70c3e76d4b3acb902fdd004e08f
If this goes well, I'd enabled it directly for older installations which upgrade without have to change configuration in the near future if no troubles are reported.
https://github.com/request/request#requestoptions-callback
https://nodejs.org/api/http.html#http_new_agent_options
From docs
```
keepAlive: true,      // Keep sockets around even when there are no outstanding requests, so they can be used for future requests without having to reestablish a TCP connection. Defaults to false
maxSockets: 40, // Maximum number of sockets to allow per host. Defaults to Infinity.
maxFreeSockets: 10   // Maximum number of sockets to …
```
> feat: enable keep alive on configuration by default

- src/api/middleware.ts
After #2026 the log will create more noise because the static content is smaller and segmented, this PR skip all those entries to the log.
```
warn --- Plugin successfully loaded: verdaccio-htpasswd
warn --- Plugin successfully loaded: verdaccio-audit
warn --- http address - http://localhost:4873/ - verdaccio/4.10.0
http <-- 200, user: null(127.0.0.1), req: 'GET /-/web/detail/@juanpicado/pnpmInit', bytes: 0/564
http <-- 200, user: null(127.0.0.1), req: 'GET /-/static/main.d8631d8e33c2a8ee0307.css', bytes: 0/1180
http <-- 200, user: null(127.0.0.1), req: 'GET /-/static/runtime.2f30ad14d8bc2c72f5e5.js', bytes: 0/2236
http <-- 200, user: null(127.0.0.1), req: 'GET /-/static/main.2f30ad14d8bc2c72f5e5.js', bytes: 0/46404
http <-- 200, user: null(127.0.0.1), req: 'GET …
```
> feat: skip log static content from web

- .github/workflows/docker-publish.yml
- Dockerfile
example:  https://hub.docker.com/r/morlay/verdaccio/tags?page=1&ordering=last_updated
```
docker buildx build --push --platform=linux/amd64,linux/arm64 --tag morlay/verdaccio .
```
github actions setup 
https://github.com/docker/setup-buildx-action
I haven't found the publish workflow.
> publishing multi-arch image

- .dockerignore
- Dockerfile
error on `docker run -it --rm --name verdaccio5x -p 4873:4873 verdaccio/verdaccio:5.x-next`
```
Error: Cannot find module 'kleur'
Require stack:
- /opt/verdaccio/packages/cli/build/cli.js
- /opt/verdaccio/packages/cli/build/index.js
- /opt/verdaccio/packages/verdaccio/bin/verdaccio
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
at Function.Module._load (internal/modules/cjs/loader.js:841:27)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/opt/verdaccio/packages/cli/build/cli.js:5:14)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at …
```
> fix: docker build missing modules

- Dockerfile
Update docker base image due Node.js security updates
https://nodejs.org/en/blog/vulnerability/january-2021-security-releases/
> fix: update docker base image node 14.15.4

- .changeset/neat-toes-report.md
- packages/config/src/conf/default.yaml
- packages/config/src/config.ts
- packages/config/src/serverSettings.ts
- packages/core/types/index.d.ts
- packages/server/package.json
- packages/server/src/server.ts
- pnpm-lock.yaml
Add extra layer of protection using rate limit 
To modify custom values, use the server settings property.
```markdown
server:
rateLimit:
windowMs: 1000
max: 10000
```
The values are intended to be high, if you want to improve security of your server consider
using different values.
https://www.npmjs.com/package/express-rate-limit#configuration-options
> feat: add rate limit to all request

- .changeset/plenty-news-remember.md
- .gitignore
- packages/auth/package.json
- packages/auth/src/auth.ts
- packages/auth/tsconfig.json
- packages/core/htpasswd/src/htpasswd.ts
- packages/core/htpasswd/src/index.ts
- packages/plugins/audit/src/audit.ts
- packages/server/package.json
- packages/server/src/server.ts
- packages/server/tsconfig.json
- packages/standalone/bin/verdaccio
- packages/standalone/build.js
- packages/standalone/package.json
- packages/standalone/scripts/web.ts
- packages/standalone/webpack.config.js
- pnpm-lock.yaml
The whole idea is to publish a package named `@verdaccio/cli-standalone` that does not have any dependency. 
- This will allow run verdaccio in offline mode just as unique requirement to have Node.js installed, (default plugins should be bundled)
- It will speed up the installation
- Fully offline support (even for installation) just copy the tarball in any location and run.
This is just an experiment, let's see how it works out.
> feat: standalone server

- .changeset/spicy-frogs-press.md
- packages/core/htpasswd/README.md
- packages/core/htpasswd/package.json
- packages/core/htpasswd/src/crypt3.ts
- packages/core/htpasswd/src/htpasswd.ts
- packages/core/htpasswd/src/utils.ts
- packages/core/htpasswd/tests/__snapshots__/utils.test.ts.snap
- packages/core/htpasswd/tests/crypt3.test.ts
- packages/core/htpasswd/tests/htpasswd.test.ts
- packages/core/htpasswd/tests/utils.test.ts
- pnpm-lock.yaml
This PR addresses issue #1917.
Algorithms were chosen according to [this document.](https://httpd.apache.org/docs/2.4/misc/password_encryptions.html)
> feat: allow other password hashing algorithms (#1917)

- .github/workflows/e2e-angular-cli-workflow.yml
- .github/workflows/e2e-gatsbyjs-cli-workflow.yml
- .github/workflows/e2e-jest-workflow.yml
Fix CLI E2E
- Gatsby seems does not work well with npm7
- Fix npm 6 for previous versions to avoid future failures
> chore: fix npm version to 6 for gatsby e2e

- Dockerfile
Node 14.16 fixed few security vulnerabilities 
Refer - https://nodejs.org/en/blog/vulnerability/february-2021-security-releases/
> fix: Upgrade Node from 14.15 to 14.16 for security fixes

- package.json
- src/lib/cli.ts
- yarn.lock
Commander is the library to handle the CLI, --info, --config and --help.
According this migration guide https://github.com/tj/commander.js/blob/master/CHANGELOG.md#700-2021-01-15
> fix: upgrade to commander v7

- package.json
- yarn.lock
Fixes #1925 
The default token database now is plain json file `.token-db.json` and is located in the same directory as `.verdaccio-db.json`,  with this format: 
```
{
"jpicado": [
{
"user": "jpicado",
"token": "MWFlM...yZDBl",
"key": "4201e4bc47c31b3434034e40b5c35175",
"cidr": [],
"readonly": false,
"created": 1609512433710
},
{
"user": "jpicado",
"token": "ZjQwZ...wYTE1",
"key": "cc249bc2f4d248308733d70291acdc2a",
"cidr": [],
"readonly": false,
"created": 1609512441024
}
],
"test": [
{
"user": "test",
"token": "M2RiM...0Mzhj",
"key": "2ae85deba977e00fb099d323173c925a",
"cidr": [],
"readonly": false,
"created": 1609533131779
}
]
}
```
Tokens are not being storage, just small part of it, the `key` is just a random `uuid`.
If you were using `npm token` in verdaccio 4, most likely the …
> feat!: npm token support revisited and enabled by default

- docs/env.variables.md
- src/lib/utils.ts
- test/unit/modules/utils/utils.spec.ts
fix https://github.com/verdaccio/verdaccio/issues/990
The default header to identify the protocol is `X-Forwarded-Proto`, but there are some environments which [uses something different](https://github.com/verdaccio/verdaccio/issues/990), to change it use the variable `VERDACCIO_FORWARDED_PROTO`
```
$ VERDACCIO_FORWARDED_PROTO=CloudFront-Forwarded-Proto verdaccio --listen 5000
```
> feat: custom protocol header

- Dockerfile
Node 14.16.1 fixed few security vulnerabilities
Refer: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.16.1
> fix: Upgrade Node from 14.16 to 14.16.1 for security fixes

- package.json
- yarn.lock
Fix broken CSS ok README section at UI
Version: v5 alpha
> fix: ui readme missing css

- src/api/web/index.ts
Custom themes can't be loaded correctly since this [PR](https://github.com/verdaccio/verdaccio/pull/2122
) modified the value of theme plugin.
```
UnhandledPromiseRejectionWarning: Error: sanity check has failed, "xxx" is not a valid plugin
```
```
let { staticPath, manifest, manifestFiles } = loadTheme(config) || require('@verdaccio/ui-theme')();
```
> fix: incorrect sanity check for theme plugin

- package.json
- yarn.lock
* expand allowed protocols for URLs in repository component ([#412](https://github.com/verdaccio/ui/issues/412)) ([b0c5bf8](https://github.com/verdaccio/ui/commit/b0c5bf8556188d5fbaa3f225d4819c3a68e68d59))
* update dependencies ([#615](https://github.com/verdaccio/ui/issues/615)) ([227e8a0](https://github.com/verdaccio/ui/commit/227e8a04db47c530cfe3f8f13ba3db9a2806bf21))
* markdown lists don't render bullet points ([#614](https://github.com/verdaccio/ui/issues/614)) ([990f749](https://github.com/verdaccio/ui/commit/990f749f984a9aa440f75d36a945a2487798e43e))
* package detail sidebar overflow ([#613](https://github.com/verdaccio/ui/issues/613)) ([c12f18f](https://github.com/verdaccio/ui/commit/c12f18feea69b597def802e11369ca91924a8621))
> fix: update @verdaccio/ui-theme

- README.md
**Type:** docs
Fixed bash command to install verdaccio in the main README.md.
The original bash command to install verdaccio didn't work:
```bash
npm install --global verdaccio@6-next --https://registry.verdaccio.org/
```
The command should be with the registry scope options:
```bash
npm install --global verdaccio@6-next --registry https://registry.verdaccio.org/
```
> docs: Fix README.md install command

- .changeset/calm-pants-impress.md
- packages/plugins/aws-storage/src/s3PackageManager.ts
- packages/plugins/aws-storage/tests/s3PackageManagerMockedS3.test.ts
Hi, this PR resolves #1984
The `npm unpublish` operation was removing more packages than it should.
This was happening because of a missing trailing slash at the prefix param.
> Fix the prefix used to delete from s3 when unpublishing packages

- Dockerfile
Node.js docker image 14.17.0
🙈 `node:14.17.0-alpine` not ready yet .... waiting is being published
> feat: update Node.js docker image 14.17.0

- src/api/middleware.ts
- src/api/web/html/renderHTML.ts
- src/api/web/index.ts
- test/unit/modules/web/__snapshots__/template.spec.ts.snap
- test/unit/modules/web/template.spec.ts
After release 5.x the configuration `web.config.logo` loading a local file is unusable, this PR restore the 4.x behavior, loading a logo from local path and https url. 
Additionally add some checks, if the file exist and is readable, otherwise fallback to the original logo and will print a warning in the log in such case.
```
web:
title: Verdaccio
```
> fix: restore using local path web logo

- src/api/endpoint/api/whoami.ts
- src/api/middleware.ts
- src/lib/up-storage.ts
- src/lib/utils.ts
- test/unit/modules/utils/utils.spec.ts
Fix #2190 
It improves how to access to the request headers, instead `req.headers['xxx]` by using `req.get('xxx')` http://expressjs.com/en/api.html#req.get which is does case-insensitive matching.
> fix: improve get headers from request #2190

- .github/workflows/ci.yml
- packages/hooks/jest.config.js
- packages/hooks/package.json
- packages/hooks/src/notify-request.ts
- packages/hooks/src/notify.ts
- packages/hooks/test/notify-request.spec.ts
- pnpm-lock.yaml
- Learning using `undici` / `undici-fetch` by replacing `node-fetch` on small package.
- Replace `nock` on that package by built in mock client.
https://undici.nodejs.org/#/docs/api/MockPool?id=mockpoolclose
https://undici-fetch.dev/#/
Refers: https://github.com/verdaccio/verdaccio/issues/1807
⚠️ `undify-fetch` target Node.js 14 as minimum, disable test on Node v12 (will be completely deprecated in a follow up).
> chore: replace node-fetch by undici hook package

- src/api/endpoint/index.ts
Over the chat was reported the `npm token` was giving 404.
https://discordapp.com/channels/388674437219745793/388675051710447616/864052734457937962
It was forgotten remove the experiment flag.
> fix: remove token experiment flag

- website/docusaurus.config.js
This fixes the issue of displaying results in the search bar that doesn't correspond to the current locale.
If you're in x/es-es/, will return the results from es-es
> fix: add contextualSearch to Algolia Search

- docker-examples/v4/README.md
Some of the links in the readme are broken because of the `v4` prefix.
This PR fixes these links.
> Fix broken Docker Example Links

- CONTRIBUTING.md
I had a leftover hack from time ago that disabled package locks in my global .npmrc and this caused `pnpm build` to fail.
Hopefully the small improvement for pnpm development setup info here this PR will help prevent other devs falling into the same trouble.
> docs: improve pnpm development setup info in CONTRIBUTING.md

- .changeset/little-stingrays-rule.md
- packages/plugins/audit/src/audit.ts
In an effort to fix #2335 I found some issues with the audit plugin. With these changes, `npm audit` works again (tested locally against `npm@6.14.12`, `npm@6.14.15` and `npm@7.21.0`). 
* fixes an ssl error by correcting the host header
* fixes an `413 - entity too large` / `400 -Invalid compressed payload` error by
explicitly setting the content-encoding header
* sends json body to remote registry
* adds new `/advisories/bulk` endpoint
* respects `strict_ssl` setting
I also added some logging output in case the audit fails.
> fix: resolves several issues of audit plugin

- .changeset/proud-jeans-walk.md
- packages/core/htpasswd/package.json
- packages/core/local-storage/package.json
- packages/core/server/package.json
- packages/hooks/package.json
- packages/mock/package.json
- packages/node-api/package.json
- pnpm-lock.yaml
Turns out that `core-js` dep was inadvertently removed from `node-api/package.json` in a prior PR as it appeared to be unused.
However I only looked for it in `*.ts` & `*.tsx` source files not realising that some source files are `*.js`.
Digging in further I found `core-js` is referenced in multiple `*.js` source files in multiple packages so have added it back as a dep to all such packages.
**Real question is:**
Why was this fault not picked up in any local tests or GH CI checks?
[**Curiouser and Curiouser indeed!**](https://www.youtube.com/watch?v=TXvdfDksLdQ)
[Nice 1 minute clip from 2019 exhibition at STALA CONTEMPORARY gallery in Perth Western Australia using the story of Alice in Wonderland.]
> fix(core/hooks/mock/node-api): add missing core-js dep

- packages/core/server/src/endpoints/search.ts
Add some logic for the npm search fastify endpoint, not enough to make it work with `npm search`
```
npm debug -- new
curl http://localhost:4873/-/v1/search?text=npm7&size=2000&from=0&quality=1&popularity=0.1&maintenance=0.1
```
> feat: fastify search endpoint v1 without auth and format

- website/docs/kubernetes.md
The config map parameter is now called "existingConfigMap", using this value worked when I installed the helm chart today. 
When using customConfigMap as per this example, the install worked but the default internal config map was used instead.
> Updated config map param name in helm example

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
This PR upgrades `husky` to `v7.0.2` in the `devDependencies` of the root `package.json`.
The only git commit hook that husky is using is currently using is `pre-commit` which is responsible for invoking `lint-staged`.
To make this upgrade work a `postinstall` script has also been added to invoke `husky install` which is more-or-less what the Husky v7 docs indicate.
As a result a new `.husky` directory in introduced at the same level as the `.git` directory and git is configured with `[core]` property `hooksPath = .husky`.
The pre-commit shell script in the new `.husky` directory uses `npm` to run the new `husky:pre-commit` script in the root `package.json`.
That's all Folks! (tm) Looney Tunes & Bugs Bunny
> Upgrade to husky@7.0.2

- .changeset/shaggy-carrots-unite.md
- packages/logger/src/logger.ts
- packages/logger/test/logger.spec.ts
fixes: #2300
changes default logger from `[DEFAULT_LOGGER_CONF]` to `DEFAULT_LOGGER_CONF` in logger setup to fix the multiple logger deprecation warning thrown when not providing any logger configs in setup call
> fix: do not throw multiple logger deprecation warning if using default logger config

- website/src/css/custom.scss
... by flipping the link text decoration behavior within articles. :upside_down_face:
> website: Improve docs link discoverability

- .github/workflows/changesets.yml
- .github/workflows/ci.yml
- package.json
- crowdin step is irrelevant for builds are not meant to be for prod, so could be skipped (unique side effect is the UI will fallback all languages to english)
- add crowding step missing to the changeset steps
> ci: avoid crowdin step is mandatory

- Dockerfile
The image was using `python` instead `python2` which seems not to be longer available.
Ref 
- https://github.com/nodejs/docker-node/issues/1605
- https://github.com/fossasia/open-event-frontend/pull/8048
> fix: update python dependency on docker image

- .changeset/three-moles-drop.md
- package.json
- packages/api/src/package.ts
- packages/store/src/storage-utils.ts
- packages/store/src/storage.ts
- packages/utils/src/index.ts
- packages/utils/src/utils.ts
- packages/utils/src/versions.ts
- packages/utils/test/utils.spec.ts
- packages/utils/test/utils.version.spec.ts
- packages/utils/test/versions.spec.ts
Improve test of dist-tags normalizers, add documentation and deprecate logic to handle tags which are arrays and scheduled to be removed in the future.
eg:
Valid ✅ 
```
"dist-tags": {
"latest": "1.0.0"
},
```
invalid ❌ (deprecated)  
```
"dist-tags": {
"latest": ["1.0.0"]
},
```
Current behaviour is tags with legacy arra are converted to string. Deprecated and after next major will be completely removed, and will throw an error in the future.
> refactor: improve versions and dist-tag filters

- .changeset/fair-lemons-beam.md
- packages/logger-prettify/src/index.ts
- packages/logger/src/logger.ts
Closes #2649
Related to discussion #2286 
This change fixes the issue where the `msg` property in JSON format logs does not have the template placeholders hydrated with values.
**Without this fix**
```text
{"level":25,"time":1636481904624,"pid":133492,"hostname":"workstation","sub":"in","request":{"method":"GET","url":"/-/verdaccio/packages"},"user":null,"remoteIP":"127.0.0.1","status":200,"bytes":{"in":0,"out":3},"msg":"@{status}, user: @{user}(@{remoteIP}), req: '@{request.method} @{request.url}', bytes: @{bytes.in}/@{bytes.out}"}
```
**With this fix**
```
{"level":25,"time":1636482057018,"pid":135963,"hostname":"workstation","sub":"in","request":{"method":"GET","url":"/-/verdaccio/packages"},"user":null,"remoteIP":"127.0.0.1","status":304,"bytes":{"in":0,"out":0},"msg":"304, user: …
```
> fix: hydrate template placeholders in JSON log messages

- website/docs/reverse-proxy.md
I have updated the docs for reverse proxy, with my fix.
> workaround for invalid checksum

- docker-examples/v6/apache-verdaccio/README.md
- docker-examples/v6/apache-verdaccio/apache_proxy/Dockerfile
- docker-examples/v6/apache-verdaccio/apache_proxy/conf/000-default.conf
- docker-examples/v6/apache-verdaccio/apache_proxy/conf/env.load
- docker-examples/v6/apache-verdaccio/docker-compose.yaml
Migrate docker-apache example to run with the V6 verdaccio image(verdaccio:nightly-master)
> migrate docker-apache v4 to V6

- packages/node-api/src/server.ts
Hello.
This PR aims to refactor the way graceful shutdown is handled by using `process.once()` instead of `process.on()` for signals caption so that it exits on double signals (cf. https://nodejs.org/api/events.html#emitteronceeventname-listener).
> refactor: graceful shutdown using `process.once()` instead of `process.on()`

- .changeset/bright-poems-obey.md
- .changeset/pretty-hounds-tap.md
- .github/workflows/ci.yml
- .prettierignore
- packages/api/package.json
- packages/api/src/index.ts
- packages/api/src/package.ts
- packages/api/test/integration/package.spec.ts
- packages/core/server/src/endpoints/package.ts
- packages/core/server/src/server.ts
- packages/core/tarball/src/index.ts
- packages/plugins/local-storage/package.json
- packages/plugins/local-storage/src/local-fs.ts
- packages/plugins/memory/src/memory-handler.ts
- packages/server/package.json
- packages/store/package.json
- packages/store/src/local-storage.ts
- packages/store/src/storage.ts
- packages/store/src/type.ts
- packages/store/test/search.spec.ts
- packages/store/test/storage.spec.ts
- packages/tools/mock/package.json
- packages/tools/mock/src/config.ts
- packages/utils/src/versions.ts
- packages/verdaccio/package.json
- pnpm-lock.yaml
Much simpler API for fetching a package
```
const manifest = await storage.getPackageNext({
name,
uplinksLook: true,
req,
version: queryVersion,
requestOptions,
});
```
> not perfect, the `req` still is being passed to the proxy (this has to be refactored at proxy package) and then removed from here, in proxy we pass the request instance to the `request` library. 
- `async/await` sugar for getPackage()
- Improve and reuse code between current implementation and new fastify endpoint (add scaffolding for request manifest)
- Improve performance
- Add new tests
- Don't replace completely the `storage.getPackage` due still some refactorings are need it, the default functionality works as expected.
All storage (from this repo, except `verdaccio-memory` and `localstorage`) plugins will stop to …
> refactor: download manifest endpoint and integrate fastify

- src/api/endpoint/api/publish.ts
- test/unit/modules/api/__snapshots__/publish.spec.ts.snap
- test/unit/modules/api/api.spec.ts
When publish with deprecated field in `package.json`, that will make all old versions miss.
Examples:
I have package@1.0.0 and package@1.0.1.
When `npm deprecate package@1.0.0 "xxx"`, Verdaccio will recived:
```json
{
"name": "module_name",
"version": {
"1.0.0": {
"deprecated": "xxx"
},
"1.0.1": {}
}
}
```
⬆️ This make sense
But then publish new version with @1.0.2.
Verdaccio will recived:
```json
{
"name": "module_name",
"version": {
"1.0.2": {
"deprecated": "xxx" // if we set this field in package.json
},
}
}
```
and that metadata will override package.json, make old version miss.
migrate from #2766
> fix: publish with deprecated field

- src/api/index.ts
- src/lib/config.ts
- src/lib/up-storage.ts
To avoid send the version of verdaccio on every request the user agent set is the one declared by client one, furthermore  disable `X-Powered-By` header on web by default unless is enabled by configuration like:
```yaml
// config.yaml
user_agent: true
```
If is enabled the proxy request would be `User-Agent:'npm (verdaccio/5.3.2)` and Web UI request would be have the header `x-powered-by: verdaccio/5.3.2`' otherwise the `x-powered-by` would be disabled and the proxy request would use the client `user-agent` instead.
> feat: user agent is the client by default

- src/api/endpoint/api/user.ts
- src/api/endpoint/api/v1/index.ts
- src/api/endpoint/api/v1/profile.ts
- src/api/endpoint/api/v1/token.ts
- src/api/endpoint/index.ts
- src/api/user-rate-limit.ts
- src/api/web/api.ts
- src/api/web/endpoint/user.ts
Follow up of https://github.com/verdaccio/verdaccio/pull/2799
Refactor and add more limit to key endpoints, update default limits for following endpoints to 1k request peer 15 min.
-  API endpoints
- login or add user
- list token
- delete token
- create token
- npm profile (change password)
-  Web endpoints
- login
- update password
We could parametrize this later, for now let's see how it goes.
> feat: add rate limit to user api endpoints

- src/lib/logger/logger.ts
The documentation https://verdaccio.org/docs/logger/ still states that logfiles can be re-opened using SIGUSR2, but since the move to pino, this stopped working. Probably this was removed together with the type "rotating-logfile" and the introduction of the recommendation to use an external tool like logrotate.
However, pino itself has some documentation on how to do it: https://github.com/pinojs/pino/blob/master/docs/help.md#reopening. IMVHO this is a better approach than using copytruncate, and it also supports systems that do not have it (like newsyslog). It is also trivial to implement, so here you go.
> Fix re-opening log files using SIGUSR2

- docs/env.variables.md
- src/lib/logger/formatter/index.ts
- src/lib/logger/formatter/prettifier.ts
- src/lib/logger/logger.ts
When `VERDACCIO_LOGGER_COLORS` is provided - it's cast to boolean and cascades any config.
When `logs.colors` is provided - it's used.
otherwise - default to `process.stdout.isTTY`
I updated the docs I found, still don't know where to update the site and the reference for the logger config.
> feature: config control  for colors in logs

- .changeset/swift-pumpkins-knock.md
- packages/auth/src/auth.ts
- packages/plugins/htpasswd/README.md
- packages/plugins/htpasswd/src/htpasswd.ts
- packages/plugins/htpasswd/src/utils.ts
- packages/plugins/htpasswd/tests/__fixtures__/htpasswd
- packages/plugins/htpasswd/tests/__mocks__/Logger.ts
- packages/plugins/htpasswd/tests/htpasswd.test.ts
- packages/plugins/htpasswd/tests/utils.test.ts
Related to #3010
* fix: refactor htpasswd plugin to use the bcryptjs `compare` api call instead of `compareSync`
* feat: add a new configuration value named `slow_verify_ms` to the htpasswd plugin that when exceeded during password verification will log a warning message
* chore: update README.md for htpasswd plugin to add additional information about the 'rounds' configuration value and also include the new `slow_verify_ms` configuration value
> Refactor htpasswd plugin to use use bcryptjs async API

- .github/workflows/website.yml
- website/docs/node-api.md
Improving Node API documentation
Maybe add where do the `addrs` comes from / how we can define it from config file ?
Added host and port display cause otherwise user doesn't know which default address and port are.
>  Node JS API Documentation : Working Implementation Code

- .github/workflows/ci.yml
- package.json
- packages/hooks/package.json
- packages/hooks/src/notify-request.ts
- packages/hooks/test/notify-request.spec.ts
- packages/plugins/htpasswd/tests/htpasswd.test.ts
- packages/proxy/package.json
- packages/proxy/src/up-storage.ts
- packages/proxy/test/proxy.search.spec.ts
- packages/store/package.json
- packages/store/test/search.spec.ts
- pnpm-lock.yaml
Remove `undici-fetch` and only `undici` to is easy to upgrade 
ref: #2292 #2340
> chore: migrate to fully undici fetch

- Dockerfile
`v14.18.3` of node fixes a bunch of security vulnerabilities. Originally, I upgraded node to the earliest version possible to avoid any unnecessary breaking changes. In the review, I was recommended to just switch to `node:14-alpine` (latest `v14` version of node) so I did.
Specifically:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22921
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22930
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22918
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22940
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22960
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22959
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44532
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44533 …
> feat: update docker base node to 14.x in 4.x branch

- .changeset/lovely-drinks-argue.md
- packages/loaders/src/plugin-loader.ts
* class plugin transpile with babel contains a function '_classCallCheck',
* will throw an error when a class is invoked without 'new'
* see: https://babeljs.io/docs/en/babel-plugin-transform-classes#examples
> fix(loaders): always create plugin instance with new

- .changeset/thick-readers-hang.md
- CONTRIBUTING.md
- packages/plugins/ui-theme/src/App/Header/Support/Support.tsx
- packages/plugins/ui-theme/src/pages/home/PackageList/Help/__snapshots__/Help.test.tsx.snap
- packages/plugins/ui-theme/src/pages/home/PackageList/Help/styles.ts
- packages/plugins/ui-theme/tools/dev.server.js
- Stop the Help container from exceeding the width of a mobile device or narrow window.
- Use Dialog instead of Modal for the ukraine popup for it to easily render correctly on mobile.
- Use the Link component in the ukraine popup.
https://user-images.githubusercontent.com/16936908/159244831-62b39506-eeda-4451-86d1-44681efcfcab.mp4
https://user-images.githubusercontent.com/16936908/159244847-98a76bba-4eaf-41bd-824a-634b0dafd2ac.mp4
Also contains two minor changes I stumbled across while working on this:
- Couldn't access the server from my phone because of the binding to `localhost` instead of `0.0.0.0`.
- Minor doc changes that will hopefully help people not misunderstand things the way I did.
> fix: improve mobile styles

- packages/cli/src/utils.ts
- packages/core/url/src/index.ts
- packages/logger-prettify/src/formatter.ts
- packages/plugins/htpasswd/src/utils.ts
- packages/plugins/local-storage/src/local-fs.ts
- packages/utils/src/utils.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> refactor: replace deprecated String.prototype.substr()

- .changeset/slow-carrots-relate.md
- packages/config/src/conf/default.yaml
- packages/config/src/conf/docker.yaml
- packages/web/src/renderHTML.ts
- website/docs/web.md
Now html cache is always enable, I can't set it disabled, so this character will bring some problems.
For example:
My website supports HTTP & HTTPS at the same time. a developer visit website by use [http://npm.XX.com，so](http://npm.xx.com%2Cso/) the verdaccio's will save http://npm.xx.com/ to the html cache. And then the developer to visit this website by [https://npm.XX.com，the](https://npm.xx.com%2Cthe/) page will report an error of cross-origin;
In fact, the situation I'm facing is more complicated.
So I need to let the user of verdaccio can select whether enable the html cache by himself.
> feat(web): add a config item to web，let the developer can select whether enable the html cache

- .github/workflows/ci.yml
> chore: node 18 on 5.x ci

- website/docs/kubernetes.md
- website/docs/uplinks.md
* Update Uplinks Documentation to refer to the Helm Chart's new
`secretEnvVars` value
* Update Kubernetes Documentation with the new `secretEnvVars` helm
value
https://github.com/verdaccio/charts/pull/95
> chore (docs): Update Uplinks/K8s doc to reference `secretEnvVars`

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- packages/auth/src/utils.ts
fix `undefined` string in log
was:
```
verdaccio    |  info --- auth/allow_action: access granted to: undefined
```
> fix logging in utils/allow_action

- .github/workflows/e2e-jest-workflow.yml
- src/lib/auth-utils.ts
- src/lib/auth.ts
- test/unit/modules/auth/auth-utils.spec.ts
Until verdaccio@5.10.0 the JWT token seems duplicates the groups, eg: https://jwt.io/
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWFsX2dyb3VwcyI6WyJ0ZXN0IiwiJGFsbCIsIiRhdXRoZW50aWNhdGVkIiwiQGFsbCIsIkBhdXRoZW50aWNhdGVkIiwiYWxsIl0sIm5hbWUiOiJ0ZXN0IiwiZ3JvdXBzIjpbInRlc3QiLCIkYWxsIiwiJGF1dGhlbnRpY2F0ZWQiLCJAYWxsIiwiQGF1dGhlbnRpY2F0ZWQiLCJhbGwiLCJ0ZXN0IiwiJGFsbCIsIiRhdXRoZW50aWNhdGVkIiwiQGFsbCIsIkBhdXRoZW50aWNhdGVkIiwiYWxsIl0sImlhdCI6MTY1MTY5OTc0NiwibmJmIjoxNjUxNjk5NzQ2LCJleHAiOjE2NTE3ODYxNDZ9.vXeZvuaw3qafNYW4oTeWoP1zLYAVmCli_7PNF0KsOpE
```
```
{
"real_groups": [
"test",
"$all",
"$authenticated",
"@all",
"@authenticated",
"all"
],
"name": "test",
"groups": [
"test",
"$all",
"$authenticated",
"@all",
"@authenticated",
"all",
"test",
"$all",
"$authenticated",
"@all",
"@authenticated",
"all"
], …
```
> fix: duplicated groups on use jwt tokens

- website/docs/install.md
This fixes a **very** minor typo: Heroku spells them as *dyno* instead of *dino*.
> Fixes Heroku typo in README

- .changeset/chilled-ways-fetch.md
- packages/plugins/memory/src/memory-handler.ts
- packages/plugins/memory/test/memory.spec.ts
The memory plugin was not correctly writing tarballs that have the same name but are from different packages and have different content.
I noticed this when using the memory plugin and installing `json-buffer` and `@types/json-buffer`.
This resulted in two things:
First verdaccio memory-plugin was logging a warning:
```
this package is already present
```
and secondly, yarn was throwing an error on subsequent installs:
```
error http://localhost:7460/json-buffer/-/json-buffer-3.0.0.tgz: Integrity check failed for "json-buffer" (computed integrity doesn't match our records, got "sha512-3YP80IxxFJB4b5tYC2SUPwkg0XQLiu0nWvhRgEatgjf+29IcWO9X1k8xRv5DGssJ/lCrjYTjQPcobJr2yWIVuQ== sha1-hcH/DwlI/BWYENS1vjW/jCCHX2Q=")
```
The underlying issue is that both of these packages have the tarball named …
> fix: Fix storing same named files from different pkgs in memory plugin

- .github/workflows/website.yml
Website preview fails for forks because cannot have access to secrets, so disable for all forks
https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#example-only-run-job-for-specific-repository
> ci: skip preview for website on forks

- Dockerfile
https://securityonline.info/cve-2022-32212-node-js-arbitrary-code-execution-vulnerability/
Also I changed python version to python3, because newest alpine-image (3.16.0) doesn't support python2 anymore. It looks like it is working. 
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0
> update nodejs to 14.20.0 to fix CVE-2022-32212

- .pnp.js
- conf/default.yaml
- conf/docker.yaml
- package.json
- src/api/index.ts
- yarn.lock
Related to [Rate limiting when behind a proxy or load balancer](https://github.com/verdaccio/verdaccio/discussions/3269) discussion.
I was able to test this change and verify manually while running Verdaccio locally.
I did attempt to add some unit tests for this to [test/unit/modules/api/api.spec.ts](https://github.com/verdaccio/verdaccio/blob/5.x/test/unit/modules/api/api.spec.ts) as well. I ran into issues in that regard as it doesn't appear the `app.set('trust proxy', config.server.trustProxy);` has any effect when [supertest](https://www.npmjs.com/package/supertest) is being leveraged. I'm not sure why this is the case. I've provided an example unit test below. No matter what I tried, the following issues were encountered:
1. When providing an `X-Forwarded-For` header, the `req.ip` …
> Allow express 'trust proxy' to be set

- packages/core/types/index.d.ts
According to [`npm`](https://docs.npmjs.com/about-registry-signatures): _"Signatures are provided in the package's `packument` in each published version within the `dist` object"_
Here's an [example of a package version from the public npm registry with `dist.signatures`](https://registry.npmjs.org/light-cycle/1.4.3).
> feat: add dist.signatures to core/types

- packages/core/types/README.md
The code samples had no syntax highlighting, so I added languages and fixed some minor formatting
> docs: fix formatting in packages/core/types/README

- website/docs/ci.md
Fixes #3291
- Deleted broken link for GitLab with no known replacement (there's [this page](https://docs.gitlab.com/ee/user/packages/npm_registry/#authenticate-to-the-package-registry) but it's about connecting to GitLab's own registry)
- Updated broken Circle CI links
- Added link for GitHub Actions (it mentions GitHub's own registry, but shows examples of using different registries)
> docs: update links in ci.md

- packages/api/src/dist-tags.ts
- packages/logger-prettify/src/levels.ts
```
Status: Downloaded newer image for verdaccio/verdaccio:nightly-master
node:internal/modules/cjs/loader:959
throw err;
^
Error: Cannot find module 'kleur'
Require stack:
```
regresion at https://github.com/verdaccio/verdaccio/pull/3308
> chore: fix missing dep on master

- README.md
Altered the `npm` global installation command i.e. `npm i -g` and `npm install --global` to `npm i --location=global` and `npm install --location=global` respectively. Also added methods for installing using `yarn` and `pnpm`
> Changed the deprecated installation method

- website/docs/what-is-verdaccio.md
OWASP is explicitly mentioning Verdaccio in their recommendations for npm security best practices. 
It's high praise so should be mentioned in a central place. If not here, you might find another page to add it.
> Add statement about npm security best practices

- docker-examples/v6/docker-local-storage-volume/conf/config.yaml
Update config.yaml to use log property instead of the depreciated logs
When using logs the following error occurs
```
Error: Error: the property config "logs" property is longer supported, rename to "log" and use object instead
```
> Update config to use log property

- .changeset/moody-clocks-roll.md
- packages/cli/src/commands/version.ts
small issue on `Verdaccio --version` display a `%` at the end.
> fix: version output with breakline

- .changeset/sour-maps-live.md
- packages/plugins/ui-theme/src/i18n/crowdin/ui.json
- packages/plugins/ui-theme/src/pages/Version/DetailContainer/Versions/Versions.tsx
- packages/plugins/ui-theme/src/pages/Version/DetailContainer/Versions/VersionsTagList.tsx
- Adds links to tags under "Current Tags" jumping to the corresponding version 
- Sorts the tags in descending order, which will always bring "latest" to the top and result in the same order as the "Version History"
Example for "tap" package:
Before:
After:
> feat: Improve "Current Tags" version list

- .changeset/modern-maps-lie.md
- packages/plugins/ui-theme/src/App/Header/styles.ts
Avoids showing two search options 
Regression of https://github.com/verdaccio/verdaccio/commit/d43894e8f692ff59a11b7c376f41d939b06a5b0c
Closes #3396
> fix: hide search icon on medium or larger devices

- .changeset/unlucky-hairs-wonder.md
- packages/plugins/ui-theme/src/i18n/crowdin/ui.json
- packages/plugins/ui-theme/src/pages/Version/DetailContainer/Versions/VersionsHistoryList.tsx
- packages/plugins/ui-theme/src/pages/Version/DetailSidebar/DetailSidebar.tsx
- packages/plugins/ui-theme/src/pages/Version/DetailSidebar/DetailSidebarTitle.tsx
- Show the publication time next to the version on the sidebar
- Bonus: display the full date and time on hover (also in version history)
Example:
> feat: Display publication time on sidebar

- .github/workflows/ci.yml
Enable Node 19 for CI testing latest releases
> chore: add node 19 to ci

- Dockerfile
https://nodejs.org/en/blog/release/v18.12.1/
> fix(sec): update base image to v18.12.1-alpine

- .github/workflows/changesets.yml
- .github/workflows/docker-publish.yml
- .github/workflows/static-data.yml
- .github/workflows/website.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- website/docs/e2e.md
Change this:
> **Programtically** Examples
To this:
> **Programmatically** Examples
> fix typo in e2e.md

- website/docs/docker.md
removed https://github.com/snics/docker-verdaccio-gitlab (not longer maintained) added https://github.com/johanneslosch/verdaccio-auth-gitlab
> updated gitlab auth (docker)

- packages/api/src/package.ts
`pkg` parameter brokes `can('access')` middleware, which wants `package`
> fix package parameter

- .changeset/eight-bottles-own.md
- package.json
- packages/middleware/jest.config.js
- packages/middleware/package.json
- packages/middleware/src/middlewares/error.ts
- packages/middleware/src/middlewares/log.ts
- packages/middleware/test/log.spec.ts
- packages/server/express/src/server.ts
- packages/tools/helpers/package.json
- packages/tools/helpers/src/initializeServer.ts
- packages/tools/local-publish/src/index.ts
- pnpm-lock.yaml
The idea is use this module in 5.x without forcing use logger yet due has pino v8 and seems might not be fully compatible with node 12
> refactor middleware dependencies

- .changeset/poor-suns-film.md
- packages/core/core/src/validation-utils.ts
- packages/core/core/test/validation-utilts.spec.ts
It should return false when input is a boolean
This bug will case
[request](https://github.com/verdaccio/verdaccio/blob/bae430fe24c9bb63dcf7b7b9e5f9f0dbf3f42669/src/lib/up-storage.ts#L157) has a body when options.json is `true`.
fix #3601
> fix(core): fix bug about isObject function

- packages/verdaccio/test/config.yaml
I found a typo where instead of `publish/unpublish` it says `publish/publish`
> fix: typo in config.yaml file

- .changeset/rare-planets-travel.md
- packages/config/src/config-path.ts
- packages/config/src/config.ts
- packages/config/src/token.ts
- packages/config/tsconfig.json
- packages/core/core/src/warning-utils.ts
- packages/core/types/src/configuration.ts
- packages/node-api/test/run-server.spec.ts
- packages/signature/src/legacy-signature/index.ts
- packages/signature/src/signature.ts
- packages/tools/helpers/src/initializeServer.ts
Improve `@verdaccio/config`  adding `forceEnhancedLegacySignature` property. This property allows legacy secret key generation for v5 compatibility but at the same time also allows verdaccio 5 uses improved token generation with IV support by default
> feat: add forceEnhancedLegacySignature

- package.json
https://github.com/verdaccio/verdaccio/pull/3689 introduced what seems to be typo and not intented change.
Result of it is that `require('verdaccio')` now imports https://unpkg.com/browse/verdaccio@5.23.0/index.js instead of CJS file and it started to cause failures for us:
```
/usr/local/share/.config/yarn/global/node_modules/verdaccio/index.js:1
export { default as startVerdaccio } from './build/index';
^^^^^^
SyntaxError: Unexpected token 'export'
at Object.compileFunction (node:vm:360:18)
at wrapSafe (node:internal/modules/cjs/loader:1049:15)
at Module._compile (node:internal/modules/cjs/loader:1084:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
at Module.load (node:internal/modules/cjs/loader:998:32)
at Module._load (node:internal/modules/cjs/loader:839:12) …
```
> fix: package.json main field

- src/lib/auth-utils.ts
When I debug registry, I found that the log always outputs "auth/allow_action: access granted to: undefined", which is strange, and then I found this problem in the code, which will always output undefined
```javascript
logger.info({ remote: user.name }, `auth/allow_action: access granted to: @{user}`);
```
> fix: fixed an issue where logger.info in allow_action always output undefined

- docker-examples/README.md
To get started with verdaccio, I found a typo while reading the docker example document and created this PR :)
`adtional` -> `additional`
Please take a look.
> Fix typo in docker examples README.md

- .changeset/silver-needles-drum.md
- .changeset/silver-spoons-nail.md
- packages/core/core/src/error-utils.ts
- packages/hooks/package.json
- packages/hooks/src/notify-request.ts
- packages/hooks/test/notify-request.spec.ts
- packages/proxy/package.json
- packages/proxy/src/agent.ts
- packages/proxy/src/proxy.ts
- packages/proxy/test/headers.auth.spec.ts
- packages/proxy/test/noProxy.spec.ts
- packages/proxy/test/proxy.metadata.spec.ts
- packages/proxy/test/proxy.search.spec.ts
- packages/proxy/test/proxy.tarball.spec.ts
- packages/store/package.json
- packages/store/src/lib/uplink-util.ts
- packages/store/src/storage.ts
- packages/store/test/fixtures/config/syncDoubleUplinksMetadata.yaml
- packages/store/test/search.spec.ts
- packages/store/test/storage.spec.ts
- packages/web/package.json
- pnpm-lock.yaml
One more step to move the refactored code from 6.x to 5.x and slow under-hood migration, the packages proxy and hooks are the prev steps before moving the `storage` (which causes some known issues/bugs), this will help with double maintenance in a big chunk of code. It removes `undici` because cannot be used in Node.js 12 in favour of got wrapped for common-js.
This PR aims to
-  prepare the `@verdaccio/proxy` module to be used at `5.x` and at the same time get rid of the `request` #1807 library
- prepare the `@verdaccio/hooks` module to be used at `5.x` and at the same time get rid of the `request` #1807 library
> feat: refactor upstream proxy and hooks with got v12

- .changeset/chilled-carrots-guess.md
- packages/ui-components/src/components/Link/Link.tsx
- packages/ui-components/src/components/Package/Package.tsx
At present, attempting to download the "tar" file from the Package List on the homepage does not work as expected. Clicking on the link only opens a new tab, but no download action occurs.
The root cause of this problem lies in the `Link` Component within @verdaccio/ui-components. It lacks a necessary `onClick` prop, preventing the execution of the `handleDownload` function in `Package.tsx`.
> Missing "onClick" prop in @verdaccio/ui-components Link component preventing handleDownload call in Package.tsx #3988

- .changeset/angry-trees-tie.md
- packages/ui-components/jest/unit/components/__mocks__/token.ts
- packages/ui-components/package.json
- packages/ui-components/src/store/models/login.test.ts
- packages/ui-components/src/store/models/login.ts
- packages/ui-components/src/utils/index.ts
- packages/ui-components/src/utils/token.test.ts
- packages/ui-components/src/utils/token.ts
- pnpm-lock.yaml
Header menu shows user as authenticated even token is expired. Уou need to logout/login for view packages.
The reason for this is storage, where the `defaultUserState` of the user is always taken from the localstorage, regardless of the expiration of his token.  As a result, the list of packages is not displayed. because the server requires authentication.
The `isTokenExpire` function has been restored from a pre-January 3, 2023 version.
Closes  #3163, #3980,
> fix: ui expired token

- .changeset/eight-squids-judge.md
- packages/plugins/ui-theme/src/i18n/crowdin/ui.json
- packages/ui-components/src/components/Engines/Engines.tsx
Fixes the following issues with the engine component (in the sidebar):
- Spelling of "NODE JS"
- Display of "node version" under "NPM Version"
- Incorrect title for "Yarn Version" and "Pnpm Version" 
Corrections:
- Changed "NODE JS" to the official "[Node.js](https://nodejs.org/en/about)" spelling 
- Display the correct npm version for the "Npm Version" box
- Added proper titles for "Yarn Version" and "Pnpm Version" 
PS: It shows as "Node.Js" instead of "Node.js" because of `text-transform: capitalize;` CSS. Not sure if you want to correct this.
> fix: display labels for engine versions

- .changeset/weak-fans-explain.md
- packages/server/express/src/server.ts
Request for `favicon.ico` on root for server failed with 404.
Looks like cause was redirect to a `png` which does not exist
> fix: Avoid 404 error when getting favicon on root

- src/api/endpoint/api/package.ts
- test/helpers/initializeServer.ts
- test/unit/modules/api/_helper.ts
- test/unit/modules/api/config/experiments.yaml
- test/unit/modules/api/experiments.spec.ts
- test/unit/modules/api/legacy/api.__c.ts
PR to able to generate a tarball redirect url asynchronously. ref https://github.com/verdaccio/verdaccio/pull/1688
usage example:
```javascript
experiments: {
tarball_url_redirect: async (packageName, filename) => {
return aws.createPresignedUrl({
Key: `verdaccio/${packageName}/${filename}`,
});
},
}
``` 
`config.js`
> feat(experiment): accept async tarball_url_redirect function

- .github/workflows/ci.yml
- .github/workflows/e2e-ci.yml
- .github/workflows/e2e-ui.yml
- .github/workflows/ui-components.yml
- CONTRIBUTING.md
- package.json
It appears that `corepack` has deprecated the `prepare` command and recommends the use of `install` command instead. Running `corepack use pnpm@8.9.0` locks the version in the `package.json` file and set the following property:
```json
{
"packageManager": "pnpm@8.9.0+sha256.8f5264ad1d100da11a6add6bb8a94c6f1e913f9e9261b2a551fabefad2ec0fec"
}
```
Running `corepack install` will then install and configure the correct package manager. I have also updated the documentation to reflect this change.
[Corepack doc](https://nodejs.org/docs/latest-v20.x/api/corepack.html)
> chore: remove deprecated corepack command

- .changeset/popular-nails-behave.md
- scripts/addon-update.ts
- website/sidebars.js
- website/src/components/EcosystemSearch/AddonCard.tsx
- website/src/components/EcosystemSearch/CardLogo.tsx
- website/src/components/EcosystemSearch/FilterControl.tsx
- website/src/components/EcosystemSearch/Icon.tsx
- website/src/components/EcosystemSearch/addons.json
- website/src/components/Header.tsx
- website/src/components/Logo.tsx
- website/versioned_sidebars/version-5.x-sidebars.json
- website/versioned_sidebars/version-6.x-sidebars.json
- Change navigation and page title to "Search for Plugins and Tools"
- Add Verdaccio logo to core plugins
- Show "type of plugin" on icon hover
- Clarify that the number is "Monthly downloads"
- Clarify that version is the "Latest version"
- Clarify that "Visit" opens npmjs.com
Ref #3539
Some screenshots:
Also 
- Remove two duplicate entries in `addons.json` which caused weird search results:
- Replace any HTML tags and markdown links in addon descriptions in `addon-update.ts` to fix these:
PS: This was a nice opportunity to learn more about react. And GH copilot... that's just killer!
> chore(website): enhance plugin search ui

- website/docusaurus.config.js
Version is switched via drop-down so it should not appear hardcoded in the website title anymore.
Before:
After:
> fix: remove version from website title

- docker-examples/v5/plugins/docker-build-install-plugin/docker.yaml
- docker-examples/v5/plugins/docker-local-plugin/docker.yaml
- docker-examples/v6/plugins/docker-build-install-plugin/docker.yaml
- docker-examples/v6/plugins/docker-local-plugin/docker.yaml
- packages/config/src/conf/default.yaml
- packages/config/src/conf/docker.yaml
- website/docs/config.md
- website/sidebars.js
- website/versioned_docs/version-5.x/config.md
- website/versioned_docs/version-6.x/config.md
- website/versioned_sidebars/version-5.x-sidebars.json
- website/versioned_sidebars/version-6.x-sidebars.json
Fixed some typos in config examples, config docs and the website sidebar.
- "Uses cases" → "Use cases"
- "publish/publish" → "publish/unpublish"
- "loding" → "login"
> docs: fix typos in different areas

- .changeset/slow-wasps-glow.md
- packages/logger/logger-prettify/src/prettify.ts
I noticed this strange "prettify pipeline error undefined" line while using verdaccio in our project (cf [our logs](https://github.com/AmadeusITGroup/AgnosUI/actions/runs/8359565541/job/22883350927#step:21:1007) and [our usage of verdaccio](https://github.com/AmadeusITGroup/AgnosUI/blob/938b178fd2d8063f1e9f0024f10adf733444ad3f/verdaccio/publish.js)). It does not cause any specific error, but, when looking at the logs, I was wondering if there was an error. Note that, as documented [here](https://nodejs.org/docs/latest/api/stream.html#streampipelinesource-transforms-destination-callback) the callback is `called when the pipeline is fully done.` (whether there is an error or not), but I think it is confusing to display `error` when there is no error.
> Avoid displaying "prettify pipeline error" if there is no error

- .changeset/silent-shirts-knock.md
- packages/config/README.md
- packages/config/src/builder.ts
- packages/config/test/builder.spec.ts
when you pass create a builder with a partial config, then there might be some required fields left empty and methods will fail because of this.
```ts
const builder = new ConfigBuilder({ publish: { allow_offline: true } })
builder.addUplink(/* ....*/) // <= This will fail. Since we're passing in a config, it is assign to `this.config` and it doesn't have this.config.uplinks yet.
```
> fix config builder erroring when passed partial config

- .changeset/eighty-lobsters-study.md
- packages/plugins/ui-theme/src/i18n/crowdin/ui.json
- packages/ui-components/.storybook/preview-head.html
- packages/ui-components/jest/jest.config.js
- packages/ui-components/package.json
- packages/ui-components/src/Theme/theme.ts
- packages/ui-components/src/components/Engines/Engines.tsx
- packages/ui-components/src/components/Install/InstallListItem.tsx
- packages/ui-components/src/components/Repository/Repository.tsx
- packages/ui-components/src/components/Versions/HistoryList.tsx
- packages/ui-components/src/components/Versions/Versions.test.tsx
- packages/ui-components/src/components/Versions/Versions.tsx
- packages/ui-components/src/sections/Detail/Tabs.tsx
- packages/ui-components/src/sections/Detail/__snapshots__/Detail.test.tsx.snap
- pnpm-lock.yaml
- Fix dark mode style issues
- Icons with white background (icons on sidebar)
- Dark mode text dark by default (Tabs on Version page)
> feat: versions filter by semver range

- .github/workflows/smok-test-module.yml
- .npmignore
- Dockerfile
https://nodejs.org/en/blog/vulnerability/april-2024-security-releases/
> fix: upgrade docker file base image to v20.12.1

- .changeset/quick-buses-scream.md
- packages/store/src/storage.ts
The fix avoids setting a timestamp for a version when creating the initial local package. The timestamp is set properly when publishing the version.
Before:
After:
> fix: avoid warning "time for version x already exists"

- .changeset/unlucky-cycles-sparkle.md
- packages/plugins/local-storage/src/local-fs.ts
- packages/plugins/local-storage/tests/local-fs.test.ts
This addresses issue https://github.com/openupm/verdaccio-storage-proxy/issues/30 (also a TODO here) which happens if `writeTarball` or `writeTempFileAndRename` are called before the folder is created.
> fix: error when writing tarball (missing folder)

- .github/workflows/ci-windows.yml
- .github/workflows/ci.yml
- .github/workflows/docker-publish.yml
- .github/workflows/static-data.yml
- .github/workflows/ui-components.yml
- .github/workflows/website.yml
This avoids failing workflows in forks (like [here](https://github.com/mbtools/verdaccio/actions)). 
These workflows are relevant to main verdaccio repo only (and typically require secrets available in main repo). 
Also contain a fix for CI-windows (side effect of https://github.com/verdaccio/verdaccio/pull/3726).
> chore: limit workflows to verdaccio repo

- .changeset/itchy-mangos-wink.md
- packages/core/url/src/index.ts
- packages/middleware/src/middlewares/web/utils/renderHTML.ts
This PR adds more types to `renderHTML()` and related functions to make it more type safe
> chore(types): Improve TS types for renderHTML and related functions

- .changeset/dry-shoes-report.md
- packages/logger/logger-commons/test/logger.spec.ts
- packages/logger/logger-prettify/src/formatter.ts
- packages/logger/logger-prettify/src/utils.ts
- packages/logger/logger-prettify/test/__snapshots__/formatter.spec.ts.snap
- packages/logger/logger-prettify/test/index.spec.ts
- packages/logger/logger-prettify/test/utils.test.ts
fixes: #4630
Previously, when colors were enabled, the log message always had a single space padded to the left, otherwise a single space was always padded to the right. This padding of the full log message seemed to be entirely unnecessary. Also, there was no explicit space set to appear between the timestamp and the log message, although when colors were enabled, the padding mentioned above would include a space, but only in that case.
Now, there's always a space between the timestamp and the log message, and there are no unnecessary spaces inserted at the beginning or end of the log message.  I tested locally with all four combinations of `format: pretty`, `format: pretty-timestamped`, `colors: false`, and `colors: true`, and I believe the spacing now appears correct.
`format: pretty` …
> fix: log spacing depending on the FORMAT and COLORS options

- .changeset/stupid-dancers-relate.md
- packages/core/url/src/index.ts
- packages/core/url/tests/getPublicUrl.spec.ts
`requestOptions.headers` are of type `IncomingHttpHeaders`. This is a dictionary whose values can be `string | string[] | undefined`. Looking at all the keys we can see that only `"set-cookie?"` allows a value of type `string[]`. 
`requestOptions.headers` is used like this: `requestOptions.headers[protoHeader]`. So only if `protoHeader` has the value `"set-cookie"` can the returned value ever be an array. For all other values it's either going to be `undefined` or a string. So only for `"set-cookie`"  will this code ever potentially throw this new error that is added in this PR.
So. If for some very very weird reason 🙃 some user of Verdaccio has configured `VERDACCIO_FORWARDED_PROTO` to have the value "set-cookie" this is before and after this PR:
Before:
`forwardedProtocolHeaderValue` is …
> patch(core/url): Throw if VERDACCIO_FORWARDED_PROTO resolves to an array

- website/docs/who-is-using.md
[OpenUPM](https://openupm.com) is a fascinating use case of Verdaccio for something completely unrelated to node or npm: A public website and repository for [Unity](https://unity.com) packages which is interactive, real-time 3D content.
> Add OpenUPM to Verdaccio use cases

- .changeset/rich-shrimps-check.md
- packages/core/types/src/manifest.ts
- packages/store/src/storage.ts
- packages/store/test/storage.spec.ts
After comparing to [npm docs](https://github.com/npm/registry/blob/main/docs/responses/package-metadata.md#abbreviated-version-object) and running tests comparing npm fetches to Verdaccio, I found some fields missing in the abbreviated manifest format like `cpu` and `os`. Also `description` is included but should not be since it's not relevant for package installation.
> fix: update fields for abbreviated manifest

- .changeset/chilly-rivers-chew.md
- packages/cli/src/commands/init.ts
Showing some more useful infos during startup:
> chore: add config location and loglevel to startup log

- Dockerfile
- docker-examples/v5/plugins/docker-local-plugin/Dockerfile
- docker-examples/v6/plugins/docker-build-install-plugin/Dockerfile
- docker-examples/v6/plugins/docker-local-plugin/Dockerfile
Recent versions of Docker raise the following warning:
```
2 warnings found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 3)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 19)
```
Solution: Change the `as` keyword to be in uppercase `AS`
> fix: Dockerfile warning FromAsCasing

- .changeset/thin-snails-flow.md
- packages/config/src/conf/default.yaml
- packages/config/src/conf/docker.yaml
- website/docs/config.md
The option is called `check_owners` (since there could be several maintainers). Code was correct but the docs were missing the 's'.
> fix: typo in config docs regarding check_owners

- .changeset/many-bees-tickle.md
- packages/config/src/conf/default.yaml
- packages/config/src/conf/docker.yaml
- packages/plugins/audit/README.md
- packages/plugins/audit/src/audit.ts
- packages/plugins/audit/src/types.ts
- website/docs/config.md
- website/versioned_docs/version-5.x/config.md
For exec `npm install` hangs. #2335
> feat: verdaccio-audit support timeout option

- website/docs/logger.md
- website/versioned_docs/version-5.x/logger.md
- website/versioned_docs/version-6.x/logger.md
docs: update logger level precedence stated in docs, moving http between `info` and `debug`
Fixes #4654
> docs: update logger level precedence stated in docs

- .changeset/mighty-gorillas-fail.md
- packages/core/url/tests/getPublicUrl.spec.ts
- packages/middleware/package.json
- packages/middleware/src/middlewares/web/utils/manifest.ts
- packages/middleware/src/middlewares/web/utils/template.ts
- packages/middleware/test/__snapshots__/template.test.ts.snap
- packages/middleware/test/manifest.test.ts
- packages/middleware/test/template.test.ts
- Fix double slash in favicon URL (regression #4727)
- Remove trailing spaces in template
- Add and adjust related tests
Closes https://github.com/verdaccio/verdaccio/issues/4736#issuecomment-2255274651
> fix(middleware): link to favicon in template

- .changeset/thick-avocados-provide.md
- packages/auth/src/auth.ts
- packages/cli/src/commands/init.ts
- packages/core/core/src/constants.ts
- packages/core/core/src/index.ts
- packages/loaders/src/plugin-async-loader.ts
- packages/node-api/src/server.ts
- packages/plugins/local-storage/src/local-database.ts
- packages/server/express/src/server.ts
- packages/store/src/local-storage.ts
- packages/store/src/storage.ts
- packages/web/src/middleware.ts
- added list of successfully loaded plugins with plugin category
- a few cosmetic changes to the output
- allow middleware plugins to use plugin prefix (like the other categories)
- added list of registered routes to debug output for "verdaccio:node-api"
Example startup log:
Example route list (some active plugins):
> chore: improve startup logging

- .changeset/angry-doors-tan.md
- packages/middleware/src/middlewares/allow.ts
- packages/middleware/test/allow.spec.ts
If a specific version is requested from the registry, the version is now passed on to the auth plugin for the allow check.
Example: http://localhost:4873/pacman/1.0.0
Before: 
```js
allow_access( { packageName: 'pacman', packageVersion: undefined } );
```
After: 
```js
allow_access( { packageName: 'pacman', packageVersion: '1.0.0' } );
```
> fix(middleware): pass version to allow check

- .github/workflows/codeql-analysis.yml
We can't have both `paths` and `paths-ignore`. 
Ref https://github.com/verdaccio/verdaccio/pull/4888
> fix: code scan issues

- .changeset/silent-bags-listen.md
- packages/core/core/src/file-utils.ts
- packages/logger/logger-commons/test/logger.spec.ts
- packages/plugins/local-storage/tests/local-database.test.ts
- packages/plugins/local-storage/tests/local-fs.test.ts
- packages/plugins/local-storage/tests/token.test.ts
- packages/tools/helpers/src/index.ts
- packages/tools/helpers/src/utils.ts
- packages/verdaccio/src/server/registry.ts
This improves the naming of temp folders. You can more easily identify them to clean up leftovers.
PS: There's a little bug in the promise version that doesn't replace the XXXXXX properly (
https://github.com/nodejs/node/pull/53776).
> chore(tests): temp folder naming

- .changeset/healthy-ducks-drive.md
- packages/config/src/user.ts
- packages/core/types/src/plugins/storage.ts
Ref https://typedoc.org/guides/doccomments/#escaping-comments
Fixes the following warnings:
```
/home/runner/work/verdaccio/verdaccio/packages/config/src/user.ts:28:20 - warning Encountered an unescaped open brace without an inline tag
28     * @return {Object} { name: xx, pluginGroups: [], real_groups: [] }
/home/runner/work/verdaccio/verdaccio/packages/config/src/user.ts:28:66 - warning Unmatched closing brace
28     * @return {Object} { name: xx, pluginGroups: [], real_groups: [] }
/home/runner/work/verdaccio/verdaccio/packages/config/src/user.ts:45:20 - warning Encountered an unescaped open brace without an inline tag
45     * @return {Object} { name: xx, groups: [], real_groups: [] }
/home/runner/work/verdaccio/verdaccio/packages/config/src/user.ts:45:60 - warning Unmatched closing …
```
> chore: fix typedocs warnings

- .changeset/healthy-zoos-lie.md
- packages/store/src/local-storage.ts
The local storage plugin was missing from the startup log messages.
> chore: add info to log when local storage is used

- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-publish.yml
- .github/workflows/shared-docker-publish.yml
Ref #4887
FYI, I was confused that GH shows a different version of the CodeQL *tool* than is used in the CodeQL *action*. But it's ok (https://github.com/github/codeql-action/issues/2608).
> chore(deps): update version comments in actions

- vitest.config.mjs
Renaming to `.mjs` removes the warnings during test execution:
"The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details."
> chore: avoid vitest warning

- website/docs/who-is-using.md
neutrinojs.org doesn't appear to be owned by mozilla anymore, as it is now an Indonesian gambling website?
> docs: Change neutrinojs.org to GitHub repository

- README.md
- SECURITY.md
- VERSIONS.md
The update to the readme and a table with the historical details clarifies the current state. I understand that there will be some consolidation of versions/branches. I will update the table when the time comes.
I think you should update the npm tags a bit. 
Currently:
```bash
> npm dist-tag ls verdaccio
4-next: 4.13.2
latest-6: 6.0.0-rc.1
latest: 6.0.1
next-7: 7.0.0-next-7.20
next-8: 8.0.0-next-8.3
previous: 4.12.2
```
Suggested:
```bash
> npm dist-tag rm verdaccio 4-next
> npm dist-tag rm verdaccio previous
> npm dist-tag rm verdaccio latest-6
> npm dist-tag add verdaccio@6.0.1 latest-6
> npm dist-tag add verdaccio@5.32.2 latest-5
> npm dist-tag add verdaccio@4.13.2 latest-4
> npm dist-tag add verdaccio@3.13.1 latest-3
> npm dist-tag add verdaccio@2.7.4 latest-2
```
> chore: version details and history

- .changeset/rude-socks-walk.md
- packages/core/types/src/configuration.ts
- packages/store/src/lib/storage-utils.ts
- packages/store/src/storage.ts
- packages/store/test/storage-utils.spec.ts
- packages/store/test/storage.spec.ts
You can now configure which readmes to store in Verdaccio. The default remains the same: only the latest readme is stored.
New options are to keep all readmes or only readmes for tagged versions which can be a good compromise.
```yaml
publish:
keep_readmes: latest | tagged | all
```
Todo:
> feat: keep_readmes option when publishing packages

- .changeset/curvy-rockets-camp.md
- packages/core/core/src/plugin-utils.ts
This should make it easier to understand the plugin interfaces:
- No functional changes
- Grouping of types/interfaces by plugin category
- Added some comments and links to docs
- Consistent naming of parameters
- Replace `any` type
> chore(core): typing, naming, and docs of parameters

- .changeset/stupid-camels-build.md
- packages/api/test/integration/package.spec.ts
- packages/api/test/integration/publish.spec.ts
- packages/api/test/integration/star.spec.ts
Fixes tests that have void return like this:
`Argument of type 'Response' is not assignable to parameter of type 'void | PromiseLike<void>'.`
> chore(api): fix void return for some tests

- .changeset/green-eagles-boil.md
- packages/api/src/user.ts
- packages/auth/src/utils.ts
- packages/auth/test/auth-utils.spec.ts
- packages/auth/test/auth.spec.ts
If neither `adduser` nor `add_user` are implemented by the authentication plugin, we assume that users are added by an external system and no error is raised.
Closes #3734
Also fixes an unexpected error that can happen if the implementation of `authenticate` is incomplete:
> fix: error E409 "username is already registered" (adduser)

- .changeset/clean-beds-wash.md
- packages/logger/logger-commons/src/logger.ts
This avoids getting debug messages like `"http (25) was changed to http (25)"`
Ref: https://getpino.io/#/docs/api?id=event-39level-change39
> chore(logger): avoid message if level remains the same

- .changeset/fifty-falcons-design.md
- packages/middleware/src/middlewares/media.ts
- packages/middleware/test/media.spec.ts
Avoid errors when using `"Content-type: application/json; charset=utf-8"` 
(instead of just `"Content-type: application/json"`)
> fix(middleware): allow content-type with charset

- src/api/web/api/package.ts
The changes in #5000 breaks package scopes
In v6.0.3 `@myscope/package` become `@yscope/package`.
> fix(api): fix scope handling in package routes

- .changeset/strange-pants-chew.md
- packages/web/src/api/readme.ts
- packages/web/test/api.readme.test.ts
- packages/web/test/config/keep-all-readmes.yaml
Follow-up to #4961
If `keep_readmes` tracks version-specific readmes, the UI will show them correctly. Otherwise, it will show the latest readme (as usual).
> feat: show version-specific readmes in web ui

- .changeset/real-seahorses-change.md
- packages/ui-components/src/components/Package/styles.ts
This color was fixed in #4687 and looks too dark.
Use the original hover color defined in [@mui/material](https://github.com/mui/material-ui/blob/v5.16.5/packages/mui-material/src/styles/createPalette.js#L36)
Old:
New:
> feat(ui-components): update hover background color of package list

- .changeset/eleven-rocks-dream.md
- packages/verdaccio/package.json
- packages/verdaccio/src/server/request.ts
- Updates user agent to a recent node version.
- Increased hooktimeout (to make it run on slower Windows)
Closes #4947
> chore: bump user agent

- packages/api/src/user.ts
Imported `USER_API_ENDPOINTS` from `@verdaccio/middleware` to use constants for API endpoints. This is just for consistency.
> refactor(api): update user routes to use constants for endpoints

- .changeset/ninety-geese-do.md
- packages/signature/package.json
- pnpm-lock.yaml
Currently, when `@verdaccio/signature` is loaded, in particular the `signature.js` file, th
`@verdaccio/config` module is being loaded but it's not an explicit dependency. 
It's just a dev dependency. This is problematic with e.g. pnpm as package manager which
intentionally tries to prevent such "leaking"/"escaping" of dependencies.
> fix: runtime dependency missing as explicit dependency

- .gitattributes
vitest snapshots are showing up with diffs after test runs on my win machine. This fixes the eol for snap files (and the default which was a typo).
> fix: set eol default in `.gitattributes`

- .changeset/quick-avocados-type.md
- packages/ui-components/tsconfig.build.json
- packages/ui-components/tsconfig.json
- packages/ui-components/vitest.config.mjs
- packages/ui-components/vitest/server-handlers.ts
- packages/ui-components/vitest/setup-env.ts
- packages/ui-components/vitest/setup.ts
- packages/ui-components/vitest/testing-library.d.ts
Error in VSC occur because TypeScript doesn't recognize the custom matchers provided by `@testing-library/jest-dom`, such as `toBeInTheDocument()`. 
TypeScript doesn't automatically recognize these custom matchers because the type definitions aren't being properly extended.
- Create declaration file `testing-library.d.ts` that extends Jest's matcher interface with all the custom matchers from `@testing-library/jest-dom`.
- Added references to this declaration file in Vitest setup files.
Updated `tsconfig.json`:
- Move the "types" array inside compilerOptions (it was incorrectly placed at the root level)
- Add an "include" section to ensure TypeScript processes your Vitest directory
- Exclude "build" sub-folders (it was running tests in build/.../*.js files)
PS: `server-handler.ts` is just …
> fix(ui-components): typings for vitest/jest-dom

- .changeset/dirty-moles-smash.md
- .changeset/proud-houses-switch.md
- packages/web/src/api/package.ts
- packages/web/test/api.packages.test.ts
Fix "??" operator warning and handling of anonymous user:
```bash
2025-03-01T16:38:50.5417412Z packages/web test: 4:38:50 PM [vite] warning: The "??" operator here will always return the left operand
2025-03-01T16:38:50.5422632Z packages/web test: 23 |  
2025-03-01T16:38:50.5423679Z packages/web test: 24 |  function addPackageWebApi(storage: Storage, auth: Auth, config: Config): Router {
2025-03-01T16:38:50.5424943Z packages/web test: 25 |    const isLoginEnabled = config?.web?.login === true ?? true;
...
// FIXME: this logic does not work, review
// const remoteUserAccess = !isLoginEnabled ? anonymousRemoteUser : remoteUser;
```
> fix(web): anonymous user handling

- .changeset/popular-trees-grin.md
- packages/ui-components/src/AppTest/AppRoute.test.tsx
- packages/ui-components/src/components/ActionBar/ActionBar.test.tsx
- packages/ui-components/src/components/Package/Package.test.tsx
- packages/ui-components/src/components/Search/Search.tsx
- packages/ui-components/src/utils/url.ts
- packages/ui-components/tsconfig.json
- packages/ui-components/vitest/vitestHelpers.ts
Fixes the following warnings/errors:
```bash
2025-03-01T16:37:08.1098894Z packages/ui-components test: stderr | src/components/Search/Search.test.tsx > <Search /> component > handleSearch: when user type package name in search component, show suggestions
2025-03-01T16:37:08.1123228Z packages/ui-components test: Warning: A props object containing a "key" prop is being spread into JSX:
2025-03-01T16:37:10.4798144Z packages/ui-components test: stderr | src/components/ActionBar/ActionBar.test.tsx > <ActionBar /> component > when there is a button to open an issue
2025-03-01T16:37:10.4800409Z packages/ui-components test: error on download TypeError: URL.createObjectURL is not a function
2025-03-01T16:37:10.4802788Z packages/ui-components test:     at Module.downloadFile …
```
> fix(ui-components): remove test warnings

- .changeset/violet-bobcats-allow.md
- packages/core/core/src/plugin-utils.ts
- packages/store/src/storage.ts
Avoid side effects between storage plugin `constructor` and `removePackage`/`hasPackage` calls.
> chore: add package parameter to storage plugin interface

- website/blog/2018-09-06-verdaccio-and-deterministic-lock-files.md
- website/blog/2018-10-21-verdaccio-4-alpha-release.md
- website/blog/2018-11-19-setting-up-verdaccio-on-digitalocean.md
- website/blog/2019-02-08-the-crazy-story-of-verdaccio.md
- website/blog/2019-02-24-migrating-verdaccio.md
- website/blog/2019-04-19-diving-into-jwt-support-for-verdaccio-4.md
- website/blog/2019-05-13-the-new-docker-image-verdaccio-4.md
- website/blog/2019-05-19-15-verdaccio-4-release.md
- website/blog/2019-07-08-verdaccio-410-release.md
- website/blog/2019-07-30-verdaccio-420-release.md
- website/blog/2019-09-07-managing-multiples-projects-with-lerna-and-yarn-workspaces.md
- website/blog/2019-09-30-verdaccio-430-release.md
- website/blog/2019-10-05-verdaccio-4-with-ldap-and-docker.md
- website/blog/2021-04-14-verdaccio-5-migration-guide.md
- website/blog/authors.yml
- website/docusaurus.config.js
- Create `authors.yml`
- Add truncation markers
- Replace non-ascii quotes
```
[WARNING] Some blog authors used in "2021-04-14-verdaccio-5-migration-guide.md" are not defined in "authors.yml":
- {"name":"Juan Picado","key":null,"page":null}
Note that we recommend to declare authors once in a "authors.yml" file and reference them by key in blog posts front matter to avoid author info duplication.
But if you want to allow inline blog authors, you can disable this message by setting onInlineAuthors: 'ignore' in your blog plugin options.
More info at https://docusaurus.io/docs/blog
[WARNING] Docusaurus found blog posts without truncation markers:
- "blog/2021-04-14-verdaccio-5-migration-guide.md"
```
> fix: warnings when building website

- .changeset/purple-planes-do.md
- packages/ui-components/src/utils/utils.test.ts
There's no "about" for `dayjs`. Just test for "a year ago".
> fix(ui): format date distance test

- .changeset/twelve-games-wonder.md
- packages/core/i18n/src/index.ts
- packages/core/i18n/src/loadTranslationFile.ts
If language is English, load crowdin json directly.
> fix(i18n): avoid fallback for en-us

- .changeset/red-dolls-repair.md
- packages/loaders/src/plugin-async-loader.ts
- packages/loaders/src/utils.ts
- Make it easier to spot plugin loads in debug log
- Add call stack to identify issues with failing plugin loads (require)
> chore: debug messages in loader

- .changeset/tender-buckets-smoke.md
- packages/ui-components/.npmignore
- packages/ui-components/README.md
- Fix badge in readme
- Switch to `.npmignore` used in other packages
> chore: fix ui-component npmignore and readme

- .changeset/nasty-experts-bow.md
- packages/config/src/conf/default.yaml
- packages/config/src/conf/docker.yaml
- packages/core/types/src/configuration.ts
- packages/middleware/src/middlewares/web/utils/renderHTML.ts
- packages/middleware/src/middlewares/web/utils/template.ts
- packages/middleware/test/__snapshots__/template.test.ts.snap
- packages/middleware/test/template.test.ts
- packages/server/express/src/server.ts
- packages/server/express/test/config/web-enabled.yaml
- packages/server/express/test/server.spec.ts
- packages/ui-components/src/Theme/theme.ts
Closes #1925
Small changes to config types:
- Add `web.enabled`, deprecate `web.enable` 
- Add `web.scriptBodyBefore`, deprecate `web.scriptbodyBefore`
- Change `primaryColor` to optional since it has a default 
- Change `flags` to optional
- Allow other values for `PackageManager`
Also improves comments in default config and updates links to docs
> chore(config): harmonize configuration options

- .changeset/early-trainers-grin.md
- packages/api/src/index.ts
Closes #2451 
If a middleware plugin registers a JSON parser, the current api package would register another one. Such double registration would lead to worse performance or possible other side effects. 
The change avoids the second registration of a parser. It also allows the middleware plugin to use define the settings of the parser.
> chore(api): avoid double registration of JSON bodyParser

- src/api/index.ts
- src/lib/config.ts
- src/lib/storage.ts
This pull request includes several changes to the `src/api/index.ts`, `src/lib/config.ts`, and `src/lib/storage.ts` files to improve plugin handling and configuration management. The most important changes are as follows:
* [`src/api/index.ts`](diffhunk://#diff-764761d79ed791ea154187526b088322dba3bebe94f9d38ab22120554aba77c7L67-L72): Removed unnecessary middleware plugin registration parameters and added a boolean flag to the `asyncLoadPlugin` function call for middleware plugins. [[1]](diffhunk://#diff-764761d79ed791ea154187526b088322dba3bebe94f9d38ab22120554aba77c7L67-L72) [[2]](diffhunk://#diff-764761d79ed791ea154187526b088322dba3bebe94f9d38ab22120554aba77c7R76)
* [`src/lib/storage.ts`](diffhunk://#diff-69a5c2bf4322fa6dd3eb08beb1de557902ba44c75a00910bb25e2e46b6f35dc3R84): Added a …
> fix: add legacy getMatchedPackagesSpec to config

- docker-examples/v6/README.md
- docker-examples/v6/amazon-s3-docker-example/README.md
- docker-examples/v6/amazon-s3-docker-example/docker-compose.yaml
- docker-examples/v6/amazon-s3-docker-example/init-s3.py
- docker-examples/v6/amazon-s3-docker-example/localStack-resources/Dockerfile
- docker-examples/v6/amazon-s3-docker-example/localStack-resources/entry.sh
- docker-examples/v6/amazon-s3-docker-example/s3Plugin/Dockerfile
- docker-examples/v6/amazon-s3-docker-example/s3Plugin/config.yaml
This pull request introduces a new example setup for running Verdaccio with Localstack to simulate AWS S3 functionality. The setup includes necessary configurations, scripts, and documentation to help users get started.
New example setup for Verdaccio with Localstack:
* [`docker-examples/v6/README.md`](diffhunk://#diff-f9153f26374f90d54aa5d853e4f470049848d88d77edb30523ec032972d8c434R14): Added a link to the new Docker + Localstack S3 + Verdaccio example.
* [`docker-examples/v6/amazon-s3-docker-example/README.md`](diffhunk://#diff-5fca6753527e8a06bf96d1a3b7b3d8c6262e35f8de447b9384d33fba91b9eec6R1-R17): Added documentation for setting up Verdaccio with Localstack S3, including usage instructions and reference articles.
Configuration and setup files:
* …
> chore: add locakstack example s3 aws plugin

- .changeset/large-turkeys-change.md
- packages/auth/src/auth.ts
This pull request introduces a new feature to the `@verdaccio/auth` package, adding support for the `legacyMergeConfigs` option. This change involves updating the `Auth` class to include and utilize the new option.
Key changes include:
* `packages/auth/src/auth.ts`: 
* Added a new `options` property to the `Auth` class to store the `legacyMergeConfigs` option.
* Updated the `Auth` class constructor to accept the `options` parameter, with a default value setting `legacyMergeConfigs` to `false`.
* Modified the use of the `legacyMergeConfigs` option in the `Auth` class logic to apply the new configuration setting.
ref: https://github.com/verdaccio/verdaccio/issues/5160#issuecomment-2765312581
> feat: add legacyMergeConfigs as option

- .changeset/swift-zebras-cheer.md
- packages/api/src/v1/token.ts
npm expects `cidr_whitelist` for token list (not `cidr`).
https://github.com/npm/cli/blob/04f53ce13201b460123067d7153f1681342548e1/lib/commands/token.js#L151C18-L153
> fix(api): cidr whitelist for tokens

- .changeset/breezy-toys-judge.md
- packages/server/express/test/config/web-enabled.yaml
Repair the failing express test (in #5196).
The test was added in https://github.com/verdaccio/verdaccio/pull/5166 and passed. 🤷
> fix(server): web-enabled test

- .changeset/thick-dolphins-rule.md
- packages/middleware/src/middlewares/web/utils/renderHTML.ts
Include template rendering options that change depending on the request header in the cache key
Fixes #5195
> fix(middleware): properly derive the html cache key

- .changeset/pink-pants-try.md
- packages/loaders/src/plugin-async-loader.ts
- packages/server/express/src/server.ts
Regression #5170
Fixes error loading middleware plugin:
`error - package not found, try to install verdaccio-theme-audit using a package manager`
PS: It loads the correct plugin on second attempt.
> fix(express): error loading middleware plugins

- website/docs/install.md
An attribution to thedevlife for their video tutorial about Verdaccio on the docs/installation page pointed to a converted domain nowoffering malware. The commit changes the link destination to the bio link thedevlife uses in their YouTube profile.
> update dangerous website link

- .changeset/silver-insects-train.md
- packages/ui-components/tsconfig.json
`tsconfig.base.json` excludes `test` folders. This change overwrites the setting for `ui-components` to fix these:
> chore(ui): fix ts errors due to excluded test folder

- Dockerfile
Update Dockerfile to reflect that alpine updated yarn to 1.22.22. 
Saves about 5.1MB image size:
Issue found [here](https://github.com/orgs/verdaccio/discussions/5213#discussioncomment-12989512).
Alpine image for node 22 [here](https://github.com/nodejs/docker-node/blob/b3d8cc15338c545a4328286b2df806b511e2b31b/22/alpine3.21/Dockerfile#L81)
> chore: update yarn version in Dockerfile

- website/docusaurus.config.js
Remove a link to the documentation page `api/node-api/index` that does not exist.
> fix: link to API page

- .changeset/nine-onions-talk.md
- packages/ui-components/src/components/Search/SearchItem.tsx
If uplinks are disabled for the web UI (`web.showUplinks: false`, ref [#4687](https://github.com/verdaccio/verdaccio/pull/4687)), then the "Private", "Remote", and "Cached" chips in search are not useful and therefore hidden.
> fix(ui): search chips when `showUplinks: false` 

- website/docs/docker.md
- website/versioned_docs/version-6.x/docker.md
I added a new v6 version of the Docker + Verdaccio repository address for updating docker.md, 
hoping it will be helpful.
> docs: add a new link to the Docker custom image list

- .changeset/afraid-cheetahs-rule.md
- packages/ui-components/src/sections/Header/Header.test.tsx
- packages/ui-components/src/sections/Header/Header.tsx
This fixes a longtime issue: users stay logged into the web ui although their token has expired. 
What was missing:
- There was no effect or logic in any React component (including Header, App, or providers) that checked token validity on app load or periodically, and logged out the user if the token had expired.
- The only check was at initial Redux state setup, so if the token expired after that, the UI did not react.
What's new:
The web app checks the token on page refresh and again every hour (see `useEffect` in `Header` component). 
This timeout is independent of the validity of the JWT token. Let me know if it should be configurable (`config.web.timeout`?).
Closes https://github.com/verdaccio/verdaccio/issues/3748
Closes https://github.com/verdaccio/verdaccio/issues/4078 
Related …
> fix(ui): check token expiry on refresh/timer

- .changeset/modern-llamas-know.md
- website/docs/uplinks.md
- website/versioned_docs/version-6.x/uplinks.md
This PR updates the documentation about making AWS CodeArtifact work with Verdaccio and an example configuration
PR create by @saurabh-gohil
> docs(uplinks): updated the documentation for an example of AWS CodeArtifact in uplinks

- .changeset/afraid-cars-sneeze.md
- packages/loaders/src/plugin-async-loader.ts
- packages/loaders/test/partials/config/absolute-scoped-plugins.yaml
- packages/loaders/test/partials/config/custom-prefix-auth.yaml
- packages/loaders/test/partials/config/npm-plugin-auth.yaml
- packages/loaders/test/partials/config/npm-plugin-not-found.yaml
- packages/loaders/test/partials/config/npm-plugin-scope-auth.yaml
- packages/loaders/test/partials/config/plugins-folder-fake.yaml
- packages/loaders/test/partials/config/relative-plugins.yaml
- packages/loaders/test/partials/config/relative-scoped-plugins.yaml
- packages/loaders/test/partials/config/scope-auth.yaml
- packages/loaders/test/partials/config/valid-plugin-store.yaml
- packages/loaders/test/partials/config/valid-plugin.yaml
- packages/loaders/test/partials/test-plugin-storage/@verdaccio-scope/verdaccio-plugin/index.js
- packages/loaders/test/partials/test-plugin-storage/@verdaccio-scope/verdaccio-plugin/package.json
- packages/loaders/test/plugin_loader_async.spec.ts
Now you can add scoped plugins to your plugin folder. The scope is just another folder level:
```bash
./plugins
./plugins/verdaccio-plugin         # prefix plugin
./plugins/@scope/verdaccio-plugin  # scoped plugin
```
- Added tests for this option 
- Fixed the custom prefix case
- Added comments to the test configs explaining the require logic 
- Renamed `scope-auth.yml` to `npm-plugin-scope-auth.yml`
> feat(loader): support scoped plugins in plugin folder

- .changeset/swift-mangos-grab.md
- packages/api/src/user.ts
- packages/api/src/v1/profile.ts
- packages/auth/src/auth.ts
- packages/config/src/config.ts
- packages/core/core/src/constants.ts
- packages/core/core/src/index.ts
- packages/loaders/src/plugin-async-loader.ts
- packages/server/express/src/server.ts
- packages/store/src/local-storage.ts
- packages/store/src/storage.ts
- packages/web/src/api/user.ts
- packages/web/src/index.ts
- packages/web/src/middleware.ts
There was some confusion between `serverSettings` and `server`. After the constructor it looked like this, for example:
```
serverSettings: { rateLimit: { windowMs: 1000, max: 10000 }, keepAliveTimeout: 60 },
server: { pluginPrefix: 'customprefix' },
```
It now uses `config.server` consistently like in yaml.
> fix(config): server settings

- .changeset/few-beds-itch.md
- packages/core/types/src/manifest.ts
- packages/store/src/storage.ts
Improve `types` to support Web UI (#5234):
- Use `Person` instead of `Author` which allows for [string format](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#people-fields-author-contributors) like 
`"Barney Rubble <b@rubble.com> (http://barnyrubble.tumblr.com/)"`.
- Add `_avatar` to `Author`
- Add `WebManifest` for use in `@verdaccio/web`
> chore(types): use "Person" instead of "Author", add WebManifest

- .github/workflows/ci.yml
- .github/workflows/e2e-ci.yml
- Dockerfile
- Enable CI Node.js 24 
- Docker build on v24
- E2E CI on 24 (mostly because npm 11 is enabled by default)
Node.js 22 remains default for other branches, until October 2025
https://nodejs.org/en/about/previous-releases
> chore: enable CI Node.js 24

- .github/workflows/docker-publish.yml
- Update build and push pipeline to docker official actions
- Test on master first, moved later to 6.x branch
- Explicit to push an image on each commit to master
- Latest tag disabled
- No semver support on master branch
- ✅  Setup already tested in another repo
```
type=raw,value=nightly-master
type=raw,value=latest,enable=false
```
> chore: update docker publish action

- .github/workflows/smoke-test-docker.yml
Looks like this was never working in 6.x
https://github.com/verdaccio/verdaccio/actions/runs/14802762748
> fix: docker smoke test (6.x)

- src/api/web/api/package.ts
- test/unit/partials/config/yaml/api.web.spec.yaml
If `config.web.login` is not set, assume `true`.
Regression #5250
> fix: config web login default (6.x)

- .changeset/tricky-kiwis-thank.md
- e2e/cli/cli-commons/src/process.ts
- e2e/cli/cli-commons/src/utils.ts
- e2e/cli/cli-commons/src/yarn-modern-utils.ts
- e2e/cli/e2e-npm10/package.json
- e2e/cli/e2e-npm10/utils.ts
- e2e/cli/e2e-npm11/package.json
- e2e/cli/e2e-npm11/utils.ts
- e2e/cli/e2e-npm6/utils.ts
- e2e/cli/e2e-npm7/utils.ts
- e2e/cli/e2e-npm8/utils.ts
- e2e/cli/e2e-npm9/package.json
- e2e/cli/e2e-npm9/utils.ts
- e2e/cli/e2e-pnpm-commons/package.json
- e2e/cli/e2e-pnpm10/package.json
- e2e/cli/e2e-pnpm10/utils.ts
- e2e/cli/e2e-pnpm8/utils.ts
- e2e/cli/e2e-pnpm9/package.json
- e2e/cli/e2e-pnpm9/utils.ts
- e2e/cli/e2e-yarn1/utils.ts
- e2e/cli/e2e-yarn2/utils.ts
- e2e/cli/e2e-yarn3/package.json
- e2e/cli/e2e-yarn3/utils.ts
- e2e/cli/e2e-yarn4/package.json
- e2e/cli/e2e-yarn4/utils.ts
- pnpm-lock.yaml
Update package managers used for test to latest versions. For example, this replaces `pnpm 10.0.0-alpha.2` with `10.12.1`.
> chore(deps): e2e-cli

- Dockerfile
Changes the ownership of the config directory from root to Verdaccio user. This way you can make config changes and restart the server more easily.
> fix: allow config changes in docker image (6.x)

- .changeset/seven-peas-obey.md
- packages/core/core/package.json
- packages/core/core/src/file-utils.ts
- packages/core/core/src/plugin-utils.ts
- packages/core/core/src/stream-utils.ts
- packages/core/core/src/tarball-utils.ts
- packages/core/core/src/validation-utils.ts
- packages/core/core/test/mystreams.spec.ts
- packages/core/file-locking/package.json
- packages/core/file-locking/src/legacy/readFile.ts
- packages/core/file-locking/src/legacy/utils.ts
- packages/core/file-locking/src/utils.ts
- packages/core/file-locking/tests/lock.legacy.spec.ts
- packages/core/file-locking/tests/lock.spec.ts
- packages/core/tarball/package.json
- packages/core/tarball/src/getTarballDetails.ts
- packages/core/tarball/tests/getTarballDetails.spec.ts
- packages/core/url/package.json
- packages/core/url/src/index.ts
- pnpm-lock.yaml
Packages under `/packages/core`:
- Remove unused deps
- Add missing deps
- Consistently use `node:deps`
Will do the same for other packages
> chore(deps): clean up core modules

- Dockerfile
Changes the ownership of the config directory from root to Verdaccio user. This way you can make config changes and restart the server more easily.
> fix: allow config changes in docker image

- .changeset/cuddly-paws-laugh.md
- packages/config/src/conf/default.yaml
- packages/config/src/conf/docker.yaml
- packages/core/types/src/configuration.ts
- packages/logger/logger-commons/src/logger.ts
- packages/logger/logger-commons/test/logger.spec.ts
- website/docs/logger.md
Allow configuring [pino log redaction](https://getpino.io/#/docs/redaction) to remove or mask sensitive data.
Example:
```yaml
log: 
type: stdout
format: json
level: http
redact:
paths: ['req.header.authorization','req.header.cookie','req.remoteAddress','req.remotePort','ip','remoteIP','user','msg']
censor: '<redacted>'
```
Also fixes passing the `sync` option to pino (which isn't [documented](https://verdaccio.org/docs/logger)). 
Authorization and cookies are already redacted by [middleware](https://github.com/verdaccio/verdaccio/blob/5fef0b629a430a27b714489abd1ee377231e479e/packages/middleware/src/middlewares/log.ts#L18-L26). This code could be deleted if we set `log.redact.paths.` to this default:
```yaml
log:
redact:
paths: ['req.header.authorization','req.header.cookie']
censor: …
```
> feat(logger): support redacting sensitive data

- .changeset/pretty-beds-destroy.md
- packages/core/core/package.json
- pnpm-lock.yaml
minimatch 10 requires ESM breaks 6.x old versions
> fix: restore minimatch major version

- website/docs/setup-npm.md
- website/versioned_docs/version-6.x/setup-npm.md
The link doesn't work in translations. The `{#troubleshooting}` needs to be added to the translations as well.
> chore(docs): troubleshooting link

- .changeset/beige-timers-greet.md
- packages/config/test/config-parsing.spec.ts
- packages/core/core/src/file-utils.ts
- packages/core/file-locking/src/utils.ts
- packages/loaders/src/plugin-async-loader.ts
- packages/plugins/local-storage/src/fs.ts
- packages/verdaccio/src/server/registry.ts
All files now use modern ES module imports from `node:fs/promises` instead of the legacy conditional require pattern, which provides better compatibility and cleaner code.
> chore: replace conditional `require(fs/promises)` pattern

- website/docs/kubernetes.md
* referenced issue was closed in 2020
* correct chart is referenced below - so believe this is no longer needed
* feel free to decline if maintainers disagree
> docs (kubernetes install): remove deprecated warning

- website/docs/docker.md
- website/versioned_docs/version-6.x/reverse-proxy.md
* beginning on this page - https://verdaccio.org/docs/reverse-proxy/ selecting Docker examples repository link took you to nowhere
* pr changes to route directly to the docker-examples v6 code
> docs: fix link path to resolve correctly

- website/src/components/Header.tsx
- website/src/css/custom.scss
This PR fixes the color contrast issue on the special button to ensure it meets accessibility standards. The button's text color has been updated to provide better readability against its background.
befor : 
after:
both in the dark and the light mode
> fix: improve button color contrast for accessibility

- package.json
- yarn.lock
> chore: remove dev dependency pinst

- .changeset/friendly-worms-drum.md
- .github/workflows/plugin-generator-e2e.yaml
- packages/config/src/conf/default.yaml
- packages/config/src/config-path.ts
**Configuration and Type Safety Improvements:**
* Added TypeScript types to the `createConfigFolder` function in `config-path.ts`, improving code reliability and maintainability.
* Documented new authentication options in `default.yaml`, including configurable hash algorithms and bcrypt rounds, to help users better secure their installations.
**Release Documentation:**
* Added a changeset entry to document the patch release for the new types in `createConfigFolder`.
> chore: add types for createConfigFolder
